### ISSUE TITLE
[Bug] Buttons in find bar is hidden behind status bar

### ISSUE THREAD

**Issue by JohnJacobT** [SlRvb/Obsidian--ITS-Theme#100]
### Describe the bug
The "Previous", "Next" and "All" buttons on the find bar are half hidden under the status bar showing word count, backlinks, edit mode etc. See picture in the screenshots section.

**Expected behavior**
The buttons on the find bar should be visible

### To Reproduce
1. Open an obsidian vault
2. Open a note
3. Press Ctrl/Cmd + F to bring up the Find Bar

### Screenshots
![image](https://user-images.githubusercontent.com/20123851/161987653-4669f6da-4ca5-4e84-9e02-88baea58acea.png)

### OS
Windows 10 / Desktop

Obsidian Version: v0.14.2

### Additional context
A recommendation: Some themes use search bar on the top of the page. Search bar on top of the page is also consistent with the "global search". My personal preference is search bar on the top :) and moving the bar to the top could solve the current issue.

**Comment by SlRvb** [comment]
I believe toggling on `Workspace > Raise Right Sidebar & Doc Search` should help with that :)

**Comment by JohnJacobT** [comment]
Interesting. Pardon my ignorance. Can I as a user toggle it? If yes, where do I do that from?

**Comment by SlRvb** [comment]
Oh, do you have the style settings plugin installed?

**Comment by JohnJacobT** [comment]
Got it. Installed Style Settings, and enabled the option. It works!

BTW, I love this theme!
