### ISSUE TITLE
Banners (Community Plug-in): Mis-Alignment

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#101]
### Describe the bug
The banner alignment is covering the main text. It just happened recently

**Expected behavior**
The banner should not cover the main text in preview mode

### To Reproduce
1. Install Community Plug-in: Banners 
2. Copy an image link
3. Command palette: Banners: Paste banner from clipboard 
4. See error in Reading mode

### Screenshots

- Reading mode: I have Heading 1 (iOS Apps) & Heading 2 (Owned)
![Screenshot - 2022-04-11 20 42 06 (Obsidian)](https://user-images.githubusercontent.com/98799613/162877660-688cc1b7-701f-4bff-9f7f-0d05961617f8.jpg)

- Preview mode: The Heading 1 is covered by the banner & The Heading 2 is partially covered.
![Screenshot - 2022-04-11 20 40 10 (Obsidian)](https://user-images.githubusercontent.com/98799613/162877670-b8781291-da30-42d9-ac16-274cb38a7e8f.jpg)

- Pop-up window: It's fine with this one.
![Screenshot - 2022-04-11 20 44 47 (Obsidian)](https://user-images.githubusercontent.com/98799613/162877642-4716fd7b-c51f-4cfa-9565-451ad23f40fc.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.14.6

**Comment by SlRvb** [comment]
Oh, do you happen to have the breadcrumbs plugin installed and displaying the trail?

**Comment by Missionary2112** [comment]
Oh yeah, I disable the trail view and it goes back to normal. I guess I would issue this to Breadcrumb author. Thank you for pointing that out.

**Comment by SlRvb** [comment]
Actually, can you update the theme? I think I fixed this issue 396d7ea

**Comment by Missionary2112** [comment]
Oh yes, thank you for fixing that. Also if you wanna move the banner down to see the Breadcrumb trail use this css sniper
`.obsidian-banner {
	transform: translateY(60px);  /* or whatever amount you need to move it */
}`
