### ISSUE TITLE
[Bug] Bullet/numbers list and relationship lines not support RTL text

### ISSUE THREAD

**Issue by Alexnoj** [SlRvb/Obsidian--ITS-Theme#103]
Hope you can fix it. Thanks!
![image](https://user-images.githubusercontent.com/30004592/164643960-ad4ed36f-1f2e-4ca3-8ccb-d5555880bdcf.png)

**Comment by SlRvb** [comment]
I think I've pushed a fix for this acda133. Can you update the theme and let me know if it works as it should?

**Comment by SlRvb** [comment]
If this issue isn't fixed, feel free to reopen the issue.
