### ISSUE TITLE
[Bug] External Images in Image Adjustments Snippet wont align

### ISSUE THREAD

**Issue by StormsForDragon** [SlRvb/Obsidian--ITS-Theme#104]
When using just the Image Adjustments snippet, I cannot get the external images to float or to position on the right or left sides. The only part that manages to work that I've found is the resizing and the color inversion. I can't get the grid to work either.

When I'm using internal images, it works perfectly fine. I know the formatting is correct (in theory) because when I've got the ITS theme installed, it works as described.

Things I've tried:
- using only the single snippet. (turned off community plugins, made a completely separate vault to do all my testing in too.)
- going through all the core editor settings for anything that has to do with images.
- Using the ITS theme - which works beautifully it's just not the theme I want to work with.
- Using the base obsidian dark theme. 

Did not try:
Mobile. Didn't see the point if I can't get it to work on desktop!
Changing versions. I'm on v0.14.6

I've got a sort of working secondary snippet running to do the aligning/float, but it's kind of awful compared to what I know this snippet can do! It's the first time I'm posting anything on github, let me know if I've missed something!

**Comment by SlRvb** [comment]
Hmmm, that shouldn't be happening 🤔

Do you have an example of the note and the images you're trying to get working? Also which theme you're working with?

**Comment by StormsForDragon** [comment]
My apologies for the delay, life happened. I hope this helps?

![SIRvb Image Adjustment Snippet example](https://user-images.githubusercontent.com/103970156/167518817-0752b46e-cda0-47c7-86dc-59266aeb2777.PNG)

**Comment by SlRvb** [comment]
Okay, if you update the snippet it `locr` and `locl` should now work! \:)

**Comment by StormsForDragon** [comment]
Thank you so much! Would you be able to check on the grid as well, it also doesn't seem to work by itself with external images. (I swear I meant to put that in the original post but was apparently too focused on the floating-location.) It's the same circumstance, only works within the theme, but not in the snippet by itself.

**Comment by SlRvb** [comment]
Interesting that it works in my theme as I've always had some trouble with the inline grid and external images 🥴 

I'll see what the difference between my theme and the snippet is 👍🏽

**Comment by SlRvb** [comment]
Hmmm, I don't think grid works with external images in general, I can't get it to align well enough even with my theme. If you have an example of that working do let me know, but I can't recreate that myself to check what's going on 🙈

**Comment by SlRvb** [comment]
Feel free to reopen this issue if it's not fixed.
