### ISSUE TITLE
[Bug] Why can't the Heading Colors be changed using style settings?

### ISSUE THREAD

**Issue by SlRvb** [SlRvb/Obsidian--ITS-Theme#107]
### Discussed in https://github.com/SlRvb/Obsidian--ITS-Theme/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **bearcai** May 12, 2022</sup>
If you want to change the code, how do you change it</div>

**Comment by SlRvb** [comment]
@bearcai could you show a screenshot of that error and what settings you're trying to change?

**Comment by bearcai** [comment]
> 

![](https://tu.bearcai.com/2022/05/95b993da1a2d7.gif)
```
h1, .cm-s-obsidian .HyperMD-header {
	color:red;
}	
h2, .cm-s-obsidian .HyperMD-header {
	color:orange;
}	
h3, .cm-s-obsidian .HyperMD-header {
	color:yellow;
}	
h4, .cm-s-obsidian .HyperMD-header {
	color:green;
}	
h5, .cm-s-obsidian .HyperMD-header {
	color:aqua;
}	
```
As you can see, color titles cannot be displayed in edit mode

**Comment by SlRvb** [comment]
Oh, you could try changing this in the Style Settings of the theme using the Style Settings plugin from the community themes. That should work and be smoother than using a css snippet to do so.

**Comment by SlRvb** [comment]
Wait have you turned on the `Specific Heading Adjustments` toggle? It needs to be toggled on or it won't work 🤔

**Comment by bearcai** [comment]
> 



> Wait have you turned on the `Specific Heading Adjustments` toggle? It needs to be toggled on or it won't work 🤔

Oh, my God. It needs to be opened. Thank you very much
