### ISSUE TITLE
[FR] Changing Readable Line Length Width

### ISSUE THREAD

**Issue by SakethKanchi** [SlRvb/Obsidian--ITS-Theme#108]
## Is your feature request related to a problem? Please describe.
- Having table with a lot of rows makes it difficult to edit them. 

## Describe the solution you'd like
- Ability to adjust Readable Line Length.

## Describe alternatives you've considered
- Making line length consistent.

**Comment by SlRvb** [comment]
This is possible with the Style Settings plugin. In the theme settings `Workspace > Workspace Resize > Note Width` should get you there I think.

**Comment by SlRvb** [comment]
Hmm that looks like some _very_ strange behavior 🤔 I have to wonder if maybe other snippets might be interfering.

This is what it should look like on default:
![Obsidian_ZIB0jXybeX](https://user-images.githubusercontent.com/54087190/170576362-a1503b78-32ba-4320-84a2-76fc8cd13915.gif)

**Comment by SakethKanchi** [comment]
> Hmm that looks like some _very_ strange behavior 🤔 I have to wonder if maybe other snippets might be interfering.
> 
> This is what it should look like on default: ![Obsidian_ZIB0jXybeX](https://user-images.githubusercontent.com/54087190/170576362-a1503b78-32ba-4320-84a2-76fc8cd13915.gif) [ ](https://user-images.githubusercontent.com/54087190/170576362-a1503b78-32ba-4320-84a2-76fc8cd13915.gif) ![Obsidian_ZIB0jXybeX](https://user-images.githubusercontent.com/54087190/170576362-a1503b78-32ba-4320-84a2-76fc8cd13915.gif) [ ](https://user-images.githubusercontent.com/54087190/170576362-a1503b78-32ba-4320-84a2-76fc8cd13915.gif)

Yep some snippet or setting maybe doing this🤔... Also is there anyway to change the width to more than 1000px?

**Comment by SlRvb** [comment]
I guess I could make it wider, I guess I'm just not sure why you wouldn't want to toggle off the Readable Line length setting toggle instead under the regular obsidian settings: `Editor > Readable Line Length` 🤔

**Comment by SakethKanchi** [comment]
Yeah but i only use a single pane for editing and viewing. And mostly use is in a minimized with weird resolutions. And with a lot of tables while adding data. For now while adding data i enable Readable Line Length and add data so i don't have to scroll or check which rows I'm writing into.

**Comment by SlRvb** [comment]
Oh I think the Advanced Table plugin doesn't *fully* support live preview so I think the padding it adds for that mode breaks

**Comment by SakethKanchi** [comment]
Yep. So to partially fix that. Turning on the Readable Line Length helps a bit. But the Width is too small as you can see..

**Comment by SlRvb** [comment]
I've upped the max width value to about 1500px 4343b2e9ccd82948e22b1e74062ab2e8692ffc59

Do let me know if that's enough width 😂

**Comment by SakethKanchi** [comment]
Yep thank you. I've tried it out with a fresh vault and it's working. And the Width is perfect for me. Now I need to check what is preventing the width in my vault.
