### ISSUE TITLE
[Bug] Lists in callouts acting weird

### ISSUE THREAD

**Issue by YesterKo** [SlRvb/Obsidian--ITS-Theme#109]
### Describe the bug
Lists in callouts add columns, showing text side-by-side (See screenshots)

**Expected behavior**
I'd expect to see them as they are in editing mode, (list after some text, for example, not next to it)

### To Reproduce
1. Make new vault
2. Paste following:
```
> This is a very long sample text to illustrate a bug
> - Here
> - Is
> - A
> - List
```
3. go to view mode

### Screenshots
![image](https://user-images.githubusercontent.com/12015722/171224703-9ddf3dee-f22d-4603-8904-19fc56be3411.png)

![image](https://user-images.githubusercontent.com/12015722/171225987-469e137e-5879-4046-9283-c627af5f99aa.png)

```
> This is a very long sample text to illustrate a bug
> - Here
> - Is
> - A
> - List
> 
> Notice that I'm actually a new line
> - Hi!
> - My 
> - Name
> - Is
```

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

Obsidian Version: v0.14.5

**Comment by SlRvb** [comment]
Ah, shoot, I've reverted the change I made to blockquotes. 

Do update the theme and let me know if that fixes this issue :)

**Comment by YesterKo** [comment]
Perfect! Thank you so so much!!! This is the perfect theme, you've done a very great job!
