### ISSUE TITLE
Header Fold Icon Showing Behind Callout

### ISSUE THREAD

**Issue by AmbushXXVI** [SlRvb/Obsidian--ITS-Theme#111]
I'm currently using the ITS - WotC - Dark theme and native callouts. If I use a left aligned callout box near foldable headers, the arrow to fold shows behind the callout and is unclickable.

![image](https://user-images.githubusercontent.com/44707760/172901790-f65f08c8-6773-4f05-b9d1-4dd14b7f319e.png)

### OS
Windows - Desktop
Obsidian Version: 0.14.15

**Comment by SlRvb** [comment]
I think I've managed a fix for this. Do let me know if that helps with this 🙏🏽  da2242f

**Comment by AmbushXXVI** [comment]
Hrm. I updated my theme through Obsidian and then restarted the app. I'm still seeing the issue, so my first question is: did I get the update as expected? If I clicked the update button from within themes, would that pick up the change?

**Comment by SlRvb** [comment]
Hmm, you're still seeing the issue? 🤔 Update my theme one more time and if it's still broken could you screenshot what it looks like this time?

**Comment by AmbushXXVI** [comment]
Unfortunately. If it helps, I could probably create a tiny vault that does this. I've included the markdown that does it.

![image](https://user-images.githubusercontent.com/44707760/175558736-42b3f99c-0ec9-41d6-9121-17f892af7d42.png)


`
---
tag: pc
alias: Example
table-common: Example
class: My Class
session-ref: Example
species: Human
class: Cleric, Paladin
background: Guild Artisan
---

> [!infobox|left]  
> # `= this.file.name `
> ![[token_example.png|cover hsmall]]  
> <br/>
> ###### Sheet
> [Beyond](https://www.dndbeyond.com/characters/1234567)
> <br/>
> ###### Stats  
> Type |  Stat |  
> ---|---|  
> Species | `= this.species ` |  
> Class | `= this.class ` |  
> Background | `= this.background ` |  


#### **Childhood**

_Got Some Issues_ 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

#### **Teenage Years**

_Got Some More Issues_ 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

#### **Adulting**

_Yup_ 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
`

**Comment by SlRvb** [comment]
Hmmm, strangely enough I still can't seem to recreate this error even on the sandbox vault 🤔

![Obsidian_bszsoKjsHI](https://user-images.githubusercontent.com/54087190/176396873-c9df685d-d9d8-432a-884a-ec42de4a889a.png)

Could you export your style settings and put that with the ITS theme css here to see if maybe something's going wrong with any of those?

**Comment by AmbushXXVI** [comment]
progress has been made! while going over the export of the ITS changes i've made, i decided to go poke around my appearance snippets. lo and behold, there's a callouts.css. and when i turn that snippet off, the fold icons push out to where they are supposed to be. it's definitely callouts from here, but an older version (from 6/9). 

if i'm using the ITS theme, is it safe to assume that i don't need to manually add anything (and that i'd only need to enable that callouts.css if i'm using a different theme)?

**Comment by SlRvb** [comment]
Aaah, I thought perhaps a rogue callout.css snippet was the case. 

Yes, if you use my theme, the same callouts from the snippet are already included in it so no need for the snippet. If you use other themes then you would need the separate snippet toggled on. Sorry for the confusion, I didn't realize I didn't include that under the `Snippets Already Included` section of the readme 🙈

**Comment by SlRvb** [comment]
I've also pushed that fix for the separate callout snippet if you need that snippet 05b0ec4

**Comment by AmbushXXVI** [comment]
Not that it super matters, but I *think* what happened was that I was using minimal, Josh did his video bit about the callouts, so I grabbed it, and then I was like, "his theme is way better than mine, i need to go get that thing" and didn't think about the fact that i already had a snippets piece loaded. 

FWIW, sorry I had you running around looking for a ghost that only existed on my end. I know that pain well.
