### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by HyperEpsilon** [SlRvb/Obsidian--ITS-Theme#113]
### Is your feature request related to a problem? Please describe.
When editing a large table in the default theme, the text extends beyond the right border of the screen. This is good because it means all columns are lined up with the columns above (if using Advanced Tables).

However, in the ITS theme the table text is wrapped, making it very hard to know which column I am editing for from a glance

### Describe the solution you'd like
Add a toggle that turns off table text wrapping in both Source Mode and Live Preview

### Describe alternatives you've considered
There isn't really an alternative other than turning ITS off when using large tables.

### Additional context
![Obsidian_2022-06-22_17-05-56](https://user-images.githubusercontent.com/6267244/175169688-3c41895d-da1f-46c2-b957-3ae6df29397a.png)
![Obsidian_2022-06-22_17-06-15](https://user-images.githubusercontent.com/6267244/175169694-d6d10a51-eb4f-4ae9-9e52-c88fc2bf76bb.png)

**Comment by SlRvb** [comment]
I've added a toggle for that under `Note Elements > Tables > Unwrap Table` 59058bb

Do update the theme and let me know if it works :)

**Comment by HyperEpsilon** [comment]
Works fantastically, thank you!
