### ISSUE TITLE
New page is cut in half in Read Mode

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#114]
### Describe the bug
Create a new file, and the page is cut in half.

**Expected behavior**
It should display a smooth uncut page in Read Mode

### To Reproduce
1. Create a new file (command N)
2. Turn on Read mode
3. See error. 

### Screenshots
![Screenshot - 2022-06-28 18 14 11 (Obsidian)](https://user-images.githubusercontent.com/98799613/176330405-816e7827-3eb0-406a-85b0-f0db71cbbccd.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.15.3

**Comment by SlRvb** [comment]
I think I've fixed the issue dde9092, do update the theme and let me know if that fixed it and if anything else might've gone awry
