### ISSUE TITLE
[Bug] Unable to use parameters on some Callouts including Infobox

### ISSUE THREAD

**Issue by maskedmage77** [SlRvb/Obsidian--ITS-Theme#116]
I have attempted to add different properties including left and no-t but they do not have any effect on an Infobox. II have added the callout css file to my snippets. The only example that would work as intended was the Collapse example.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/39139848/177078799-fe0c8a29-0512-46b4-8894-d445af938e16.png">

**Comment by SlRvb** [comment]
That infobox also looks very strange in its styling 🤔

Do you happen to have the callout snippet and my theme installed at the same time?

**Comment by maskedmage77** [comment]
I apologize if this is not a bug and actually just user error. 

I do have your D&D theme and the "S - Callouts.css" snippet both active. I have slightly tweaked some of the styling using the plugin Style Settings. I have changed heading fonts and colors, and center titles on callouts. I have actually noticed that left does affect the callout somewhat, however it only shifts it slightly to the left. 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/39139848/177184618-ea99ff3b-c531-4df7-977a-de5edb68236e.png">

**Comment by maskedmage77** [comment]
[test-vault.zip](https://github.com/SlRvb/Obsidian--ITS-Theme/files/9040850/test-vault.zip)

I have created a quick test in a new vault using the default ITS theme and the callout snippet if you would like to take a look.

**Comment by SlRvb** [comment]
Hmm, so some options only work in Reading mode (left / right), but you definitely shouldn't be seeing the title for the infobox there. I see this with the test vault loaded up which is the correct styling:
![Obsidian_kDJvrXmuKJ](https://user-images.githubusercontent.com/54087190/177193026-d9034eb8-309c-48d3-beae-127f45080e64.png)

**Comment by maskedmage77** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/39139848/177194476-ba1c8af7-caa2-4850-8cf3-69bd299fdb71.png">

It displays the same with and without the snippet. It looks like we are testing in different builds of obsidian. Maybe it could be an issue with my current obsidian version. 

If it would work for you, we could jump on a call and investigate the issue further.

**Comment by maskedmage77** [comment]
I just did a
