### ISSUE TITLE
Embedded Inline Code oversized 

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#118]
### Describe the bug
Embedded files with Inline Code will display the code in bigger font than normal.

**Expected behavior**
The embedded Inline Code should display normal font size

### To Reproduce
1. Create a new file with Inline Code 
2. Embed the file 
3. See error: The Embedded Inline Code displayed bigger font.

### Screenshots
![Screenshot - 2022-07-08 20 39 55 (Obsidian)](https://user-images.githubusercontent.com/98799613/178090303-07288594-5832-4130-95d0-993b2b64f135.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.15.5

**Comment by SlRvb** [comment]
I can't seem to replicate the issue 🤔 Does this happen in the sandbox vault?

![Obsidian_TcsCXxVfPn](https://user-images.githubusercontent.com/54087190/178163368-94e08a32-2a7d-4b41-a1e5-ab09c367f150.png)

**Comment by Missionary2112** [comment]
I mean using ` ` ` `
![Screenshot - 2022-07-10 16 26 25 (Obsidian)](https://user-images.githubusercontent.com/98799613/178166099-41e783d3-fea8-4c4a-ba8b-0b375620faca.jpg)

**Comment by SlRvb** [comment]
Still can't seem to replicate that on my end 🤔 
![Obsidian_FjWJGIfPbt](https://user-images.githubusercontent.com/54087190/178176161-ac37fa16-5ff8-4884-9174-55ec99f6a90e.png)

Please try doing that in the Sandbox vault and let me know if the size is still large in embeds

**Comment by Missionary2112** [comment]
Yeah it's weird 🤔. Only my main vault is affected.
- Turn off Community Plug-ins: The bug still exists
![Screenshot - 2022-07-10 22 27 11 (Obsidian)](https://user-images.githubusercontent.com/98799613/178195011-32322b8a-b5de-46ff-833e-cbf10c8d28da.jpg)

- Default Theme
![Screenshot - 2022-07-10 22 20 44 (Obsidian)](https://user-images.githubusercontent.com/98799613/178195128-f5fe3a1d-9cb8-49e5-9546-743d02b0f44e.jpg)

- Cyber Glow Theme
![Screenshot - 2022-07-10 22 21 13 (Obsidian)](https://user-images.githubusercontent.com/98799613/178195290-8f1a0b55-5bf7-4b14-9674-9fc67219b144.jpg)

- Other vault seems to work fine
![Screenshot - 2022-07-10 22 34 16 (Obsidian)](https://user-images.githubusercontent.com/98799613/178195582-732fe8fa-66da-4ead-9fa5-5e40ad6ecd3b.jpg)

**Comment by SlRvb** [comment]
I'd say if you turn on restricted mode/safe mode, reload your vault and see if it's still happening. I think a plugin might be causing this strange behavior but not sure which one 🤔

**Comment by SlRvb** [comment]
I think I know what's going wrong and I should fix it without needing an option for it 🤔

**Comment by SlRvb** [comment]
Should be fixed now \:) 9b7fb35f6b3063fb95d08a56fc5b56c2a11d6cfb
