### ISSUE TITLE
[Bug] Heading centering always applied in Preview mode

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#119]
### Describe the bug

Some headers gets centered while they should not when switching to Live Preview mode.

They are correctly rendered in Source and Reading mode.

**Expected behavior**

Live preview mode should be in sync with reading mode.

### To Reproduce

Set the following settings under Note Elements:
- Heading Underlines : Hiding (all unchecked except for H3 through H6)
- Header Styling : Center Heading with lines - Checked, others left unchecked

Create a note with H1, H2 and H3.

H1 and H2 should be centered.
H3 should be left aligned.

### OS
Where does the bug occur?

- [x] Desktop, Windows

Obsidian Version:

0.14.15

### Additional notes:

While I like the fact that some headers are not centered when I select those options, I find it not obvious.

Maybe having a separate settings for header alignment for each header type would be an option ?

**Comment by SlRvb** [comment]
Yeah it would have to be a new set of options. Underline styling only affects the line not text alignment and the center headings just targets them all.

I'll add new options for text alignment 👍

**Comment by stecydube** [comment]
Wow! You're fast 😎
Works beautifully.
Only thing, right alignment does not seem to work, it always aligns to the left.

Thank you very very much. ❤
