### ISSUE TITLE
Pictures aren't centered and clickable

### ISSUE THREAD

**Issue by Javelot** [SlRvb/Obsidian--ITS-Theme#12]
Hi there,

It seems pictures aren't centered and clickable anymore.

Here's a screenshot of a page with a picture aligned on the left side of the page.

![2021-07-16 09_31_18-Window](https://user-images.githubusercontent.com/64957468/125909860-8fd12e30-3ec4-4c47-b099-3b19c526ab29.png)

And here is the picture I was trying to add into the page to reproduce the issue.

https://cdn.cloudflare.steamstatic.com/steam/apps/272600/capsule_616x353.jpg?t=1424562757

I tried turning on safe mode to see if any plugin was interfering, to no avail. Is anyone facing the same issue ?

Thank you very much for your help, I really appreciate the design of this theme and the constant improvements that have been made to it.

**Comment by SlRvb** [comment]
Pictures now use `ctr` to center images rather than just `c` to prevent problems. To have it be clickable, you can toggle `Image Zoom` in the Style Settings under the Plugins section.
