### ISSUE TITLE
"Left/Right Aligned Callout Boxes" issue + altered snippet request

### ISSUE THREAD

**Issue by train-con** [SlRvb/Obsidian--ITS-Theme#120]
I have been using the "Left/Right Aligned Callout Boxes" snippet for a while now and I'm overall satisfied with it! I use it to replicate a sort of Wikipedia-esque interface for my Obsidian and it does its job.

Issue:
When the box becomes too long (e.g. I create longer lists in a cell), I notice whenever I scroll down the entire thing disappears until I scroll back up again. This may be a problem for me in the future when my database becomes larger.

Requests:
• Slightly extended width boxes
• Remove subheading ("Stat | Info") and leave only the heading

Thanks a million for this snippet!

**Comment by SlRvb** [comment]
I'm not sure what you mean by Stat and Info 🤔 that's not a part of the snippet just stuff you can add, change, or remove in the markdown itself.

For width I'll be adding info on the callout guide about callout sizing.

**Comment by train-con** [comment]
I haven’t made it too far yet 😂

But I will make an example box! Can you send videos through GitHub or is it
only images?

**Comment by train-con** [comment]
Update: I looked at the guide and altered the widths. It helped!

**Comment by SlRvb** [comment]
> Can you send videos through GitHub or is it only images?

You can send video :) It helps me know what might be going on if I see the error.

**Comment by train-con** [comment]
Unfortunately

> > Can you send videos through GitHub or is it only images?
> 
> You can send video :) It helps me know what might be going on if I see the error so I can try to replicate it on my end.

Hello! Unfortunately I cannot send a video because my system has a limit. Here's the text from the page instead (I added lines so you can see where the disappearing happens) :)

> [!infobox]
> ****
> ![[miscstock.png]]
>
> ||
> ---|---|
> **Test** | Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test |
> **Test** | Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test |
> **Test** | Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test |

---

Test Test Test 1
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 2
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 3
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 4
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 5
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 6
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 7
<br>
<br>
<br>
<br>
<br>

**Comment by train-con** [comment]
> > Can you send videos through GitHub or is it only images?
> 
> You can send video :) It helps me know what might be going on if I see the error so I can try to replicate it on my end.
<img width="719" alt="Screen Shot 2022-07-18 at 1 07 08 AM" src="https://user-images.githubusercontent.com/107587112/179448690-dbb3d5de-b688-4ae0-9194-84d673d6b841.png">

Unfortunately I can't seem to send videos at this time. But below is the text I used to test out the problem (by scrolling up and down; slow + fast). I hope this may help as an alternative :)
<img width="719" alt="Screen Shot 2022-07-18 at 1 07 08 AM" src="https://user-images.githubusercontent.com/107587112/179448711-76504a8a-0743-4f55-87cf-b51635f48acd.png">

**Comment by SlRvb** [comment]
Is it possible to paste this notes contents here so I can see what's going on in my own vault?

**Comment by train-con** [comment]
> Is it possible to paste this notes contents here so I can see what's going on in my own vault?

Of course! Here it is:

> [!infobox]
> ****
> ![[miscstock.png]]
>
> ||
> ---|---|
> **Test** | Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test |
> **Test** | Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test |
> **Test** | Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test <br>Test |

---

Test Test Test 1
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 2
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 3
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 4
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 5
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 6
<br>
<br>
<br>
<br>
<br>

---

Test Test Test 7
<br>
<br>
<br>
<br>
<br>

**Comment by SlRvb** [comment]
Hmmm, I do see the error. Unloading the note content the further you scroll is something obsidian does for performance reasons. So unfortunately I think this is not something that's possible to fix with css alone.

I might recommend keeping the infobox short and maybe putting the long database query under a heading if you really need to see all that information. Sorry!  🙈

**Comment by train-con** [comment]
> Hmmm, I do see the error. Unloading the note content the further you scroll is something obsidian does for performance reasons. So unfortunately I think this is not something that's possible to fix with css alone.
> 
> I might recommend keeping the infobox short and maybe putting the long database query under a heading if you really need to see all that information. Sorry! 🙈

Thank you for your response, I guess it is what it is.. 😮‍💨

My infoboxes will become quite long in the future so I'm curious on how to implement the long database query under a heading! I'm not exactly the most proficient in coding things, hahah.

**Comment by SlRvb** [comment]
Ah it's not too technical really, just a regular note with a heading and the query under it:
````
# Your heading name here

```dataview
LIST
FROM [[]]
```
````

Unless you're making really long tables without dataview then it would just be a regular table under that. 🙈

**Comment by bojtalepenye** [comment]
So, is there, or will be a solution to this error?
