### ISSUE TITLE
[FR] Multi row Grid

### ISSUE THREAD

**Issue by Catnap63** [SlRvb/Obsidian--ITS-Theme#121]
### Is your feature request related to a problem? Please describe.
Is there a way to use the "|grid|" to make a multi row grid of images?  

### Describe the solution you'd like
To display an actual grid of images, like a chess or checker board?

**Comment by SlRvb** [comment]
I'd recommend using the [callout grids](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Guide/Callouts.md#image-grid) for that instead of the `|grid` from the image adjustments snippet
