### ISSUE TITLE
[FR] Keep wrapped text when using an Infobox while scrolling

### ISSUE THREAD

**Issue by TheAussieTinker** [SlRvb/Obsidian--ITS-Theme#122]
### Is your feature request related to a problem? Please describe.
When I'm using an infobox it renders great in preview mode but when I scroll to a certain point it seems to unload and the text wrapping gets messed up.

### Describe the solution you'd like
Keep the text wrapping when scrolling

### Describe alternatives you've considered
I don't know if it's related to a core function of obsidian unloading the page when you scroll but if it is, is it possible to put some boundaries like a vertical boundary that is the same distance from the side of the page as the edge of the infobox that extends to the entirety of the page.

**Comment by SlRvb** [comment]
#122 Seems to be the same issue. Unfortunately nothing I can really fix with css 😔

https://github.com/SlRvb/Obsidian--ITS-Theme/issues/120#issuecomment-1192040136
