### ISSUE TITLE
Special Blockquote renders weird format with bold/italic text

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#126]
### Describe the bug
The special blockquote `<b> ... </b>` does render weird format with **bold** / *italic* text.

**Expected behavior**
The **bold** text should stay where it's supposed to be.

### To Reproduce
1. Type any text in `<b> ... </b>`
2. Make some texts bold
3. See error, especially in long paragraph.

### Screenshots
- Preview mode
![2022-08-14_17 14 05_CSX](https://user-images.githubusercontent.com/98799613/184560255-813aad2d-e1b5-4fad-bc5f-9900096f65d7.jpg)

- Edit mode
```
<b> Humility engenders learning because it beats back the arrogance that puts blinders on. It leaves you open for truths to reveal themselves. You don’t stand in your own way. . . . Do you know how you can tell when someone is truly humble? I believe there’s one simple test: because they consistently observe and listen, the humble improve. They don’t assume, 'I know the way.' _ **Wynton Marsalis** </b>
```

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.15.9

**Comment by SlRvb** [comment]
Are you actually using the `<b>` blockquote syntax? I'm planning on removing that from my theme in the big rewrite since we now have callouts 🙈🙈

**Comment by Missionary2112** [comment]
Okay cool. I'm just trying out new syntax and wondering what's going on. Can't wait to see your work. Cheers 👍
