### ISSUE TITLE
Table alternative weird format color

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#128]
### Describe the bug
The table is alternated with blank color. 

**Expected behavior**
The table should alternate with another color not blank color

### To Reproduce
1. Create a simple table
2. See error: table alternates with blank color.

### Screenshots
- In MacOS
![2022-08-30_14 07 33_CSX](https://user-images.githubusercontent.com/98799613/187543682-880e2df0-e386-422f-af8e-e306299714fe.jpg)

- In iOS
![IMG_0162](https://user-images.githubusercontent.com/98799613/187544869-8cff96b6-d2f2-4950-a026-4174ca5bc9ed.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v.0.16.0

### Additional context
Since Obsidian launched the newest version 0.16.0, the table alternative color has changed.

**Comment by SlRvb** [comment]
Ah yeah obsidian's default css has overridden that. Should be fixed now though :) 079c9d5

**Comment by Missionary2112** [comment]
Thank you!

**Comment by Missionary2112** [comment]
I just realized the Dataview Table is now alternated.
![2022-09-01_18 41 45_CSX](https://user-images.githubusercontent.com/98799613/188041258-2115f758-dfe7-4bae-8014-ee0aad6cd40d.jpg)

It used to be like this
![image](https://user-images.githubusercontent.com/98799613/188041300-ccefbdb5-9a8a-4b7c-aba4-d9e7c79922b2.png)

**Comment by SlRvb** [comment]
Could you update to v0.6.0+ of my theme? I think I fixed that :)

**Comment by Missionary2112** [comment]
Nice, thank you for the quick update 👍
