### ISSUE TITLE
How do I set the icons?

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#13]
![icon](https://user-images.githubusercontent.com/30563826/126415335-38576268-2dbe-49b7-9af1-96a5afed0183.png)

My current icon doesn't look good

![image](https://user-images.githubusercontent.com/30563826/126415462-a9e736b9-3eb8-4e35-9113-f4dece5c0802.png)

**Comment by SlRvb** [comment]
For this, I'm using the Icon Swapper plugin and this [file](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/ITS%20Icons.yml) imported into it.

[This](https://forum.obsidian.md/t/theme-its-dark-light-theme/12838/83) might also help if you're not sure how to do it.

**Comment by Borber** [comment]
> For this, I'm using the Icon Swapper plugin and this [file](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/ITS%20Icons.yml) imported into it.
> 
> [This](https://forum.obsidian.md/t/theme-its-dark-light-theme/12838/83) might also help if you're not sure how to do it.

Thanks, I'm already using it. Thank you for developing such a great theme!
