### ISSUE TITLE
Issues in 0.16.2

### ISSUE THREAD

**Issue by TayThorian** [SlRvb/Obsidian--ITS-Theme#131]
Hi.

Minor issue with the latest build.

If I go to settings, Appearance, I can't scroll down to the bottom of that list past 'Advanced' and see CSS Snippets.

If I change back to the default theme, it's okay.

**Comment by SlRvb** [comment]
What version of the ITS theme are you on?

**Comment by TayThorian** [comment]
Hi

Theme is Version 0.6.4

**Comment by SlRvb** [comment]
Can you replicate this in the sandbox vault? Click the `I`, then open Sandbox vault and install my theme 🙏🏽

**Comment by TayThorian** [comment]
Yes, same in Sandbox. Its actually slightly worse. Cannot scroll down on Appearance at all.

***@***.***



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SlRvb** [comment]
I can't seem to recreate this, are you viewing this on a laptop? 🤔

**Comment by TayThorian** [comment]
I use a laptop with a 36" monitor

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SlRvb** [comment]
Any chance I could get a video/gif of this issue?

**Comment by JarradTait** [comment]
Scroll is broken for me too. This is as far as I can scroll on my setting page with ITS Theme

![image](https://user-images.githubusercontent.com/13686225/192080554-6c1ede17-85e9-4dc9-93e6-6a25bb77b0da.png)

This is how far I should be able to scroll

![image](https://user-images.githubusercontent.com/13686225/192080570-440cd2ab-c62b-4c0f-ab1a-ec8eb16d978f.png)

**Comment by JarradTait** [comment]
> Any chance I could get a video/gif of this issue?

![2022-09-27 19-24-22](https://user-images.githubusercontent.com/13686225/192661044-22c2dcbf-6470-4f82-a853-5a6ba808d6e1.gif)

**Comment by 23maverick23** [comment]
I could be off base (I've only spent a few minutes tinkering), but it seems to be that the `--setting-h` variable is causing this issue on the modal window itself. The snippet is here:

```css
.modal.mod-settings .vertical-tab-content-container, .modal.mod-settings .vertical-tab-header {
    height: var(--setting-h);
    padding: 0;
}
```

If you completely disable the height property here, you get full/normal scrolling back. Funny enough, changing this setting in Style Settings to `100vh` still doesn't solve the issue - you need to remove/disable the setting completely.

I'm not sure where to adjust this as I haven't done any theme development for Obsidian, but thought this might help :)

**Comment by SlRvb** [comment]
Alright I believe I've fixed the issue, do let me know if it works 🙈
