### ISSUE TITLE
Quote " gets in the way

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#132]
### Describe the bug
Quote shows icon `"` overlapping on the text section

**Expected behavior**
The icon`"` should not overlap on the text section.

### To Reproduce
1. Create a quote `>`
2. Write / insert a phrase long enough to see the error
3. See error: The quote icon `"` overlaps on the text section

### Screenshots
<img width="1078" alt="BDDB286B-9C99-45E2-9EA1-F6D184863F35" src="https://user-images.githubusercontent.com/98799613/188500350-7d2f1814-c5c1-41dd-9671-b746a547889a.png">

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.16.2

**Comment by SlRvb** [comment]
Should be fixed now in theme version v0.6.1 :)

**Comment by Missionary2112** [comment]
<img width="1067" alt="2022-09-06_17 46 03_CSX" src="https://user-images.githubusercontent.com/98799613/188764454-547af0db-33e8-4fca-8079-1bbbc2501930.png">

- But single-line quote has the icon `"` quite off the box, compared to multiple-lines quote.

**Comment by SlRvb** [comment]
The padding issues for the quote icon should be fixed now on ITS v0.7.0
