### ISSUE TITLE
[Bug] Overlapping floating callout block

### ISSUE THREAD

**Issue by Wenzelgood** [SlRvb/Obsidian--ITS-Theme#134]
Hi, I have a problem. Note elements overlap the floating Callout block. Setting a flow-root on these elements solves the problem, but I think you can find a more elegant solution. 
![image](https://user-images.githubusercontent.com/35866885/189167761-0a73b924-5c9a-4f9d-aeb9-5a9d960be997.png)

**Comment by Proshyak** [comment]
Could this be linked to my bug? we're both using callouts (https://github.com/SlRvb/Obsidian--ITS-Theme/issues/133)

**Comment by SlRvb** [comment]
Hmm, no that's a different kind of issue. This one, I think I might have to set my callouts to flow-root like my blockquotes as you've suggested 🥴

**Comment by SlRvb** [comment]
I've added the suggestion, callouts should no longer overlap behind a floating callout anymore.
