### ISSUE TITLE
Colored line is uneditable 

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#136]
### Describe the bug
I used Style Setting Plug-in to edit ITS Theme to hide the grey line. Now it doesn't work anymore.

**Expected behavior**
Style Setting should hide the grey line from the list.

### To Reproduce
1. Create a multiple list structure
2. Go to Style Setting > Colors > Other > Change the `Lines` color 
3. See error: The grey line, regardless of which color you change

### Screenshots
- iPad Version
![IMG_0165](https://user-images.githubusercontent.com/98799613/189505754-1c5a3104-584a-455e-9065-f0c8daecebb0.png)

- MacOs Version
<img width="1040" alt="2022-09-10_16 47 12_CSX" src="https://user-images.githubusercontent.com/98799613/189505536-35e34031-a2f0-40e7-8651-0c535102549a.png">

- Style Setting: Note Elements > Lists
<img width="652" alt="2022-09-10_16 47 37_CSX" src="https://user-images.githubusercontent.com/98799613/189505543-525ff90c-67d1-4e77-b396-5c8dbcf684d6.png">

- Style Setting: Colors > Other
![2022-09-10_16 49 10_CSX](https://user-images.githubusercontent.com/98799613/189505546-c8e8432f-42f0-4ccf-8c28-aa2899c24e07.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.16.2

**Comment by SlRvb** [comment]
You might want to disable `Editor > Show Indentation Guides`

**Comment by Missionary2112** [comment]
Wow! Thank you 🙏 for showing me `Show Indentation Guides`.
