### ISSUE TITLE
[Bug] Editing mode is not centered

### ISSUE THREAD

**Issue by Nedreow** [SlRvb/Obsidian--ITS-Theme#138]
### Describe the bug
When editing a note (Live Preview or Source Mode) the text is left justified instead of centered.

**Expected behavior**
The text should be centered in al modes, just like it is in Read mode.

### To Reproduce
1. Open any note.
2. Ensure it is in Editing Mode

### Screenshots
![Left Justified](https://user-images.githubusercontent.com/9559930/189697717-42694e82-0e21-468b-a693-f54016b39555.PNG)

### OS
Where does the bug occur?

- [ ] Windows 10

Obsidian Version: 0.15.9

**Comment by SlRvb** [comment]
I think I've fixed this. Do update the theme and let me know if that fixes it :)

**Comment by Nedreow** [comment]
It's fixed, thanks
