### ISSUE TITLE
Sub unordered list bullet symbol

### ISSUE THREAD

**Issue by zcysxy** [SlRvb/Obsidian--ITS-Theme#14]
Thanks for your great theme again! Smooth on the mobile. A tiny bug with bullet symbols:

![B013DC6C-2F77-4404-9648-ED19943FB059](https://user-images.githubusercontent.com/48207708/127162233-bfab3620-9ad9-444a-8f90-695aa30f9349.jpeg)

**Comment by zcysxy** [comment]
I think it is due to the older version of CodeMirror on mobile

**Comment by SlRvb** [comment]
Oh strange, I can't seem to replicate this,  what kind of device are you using?

**Comment by zcysxy** [comment]
iPadOS (iPhone is fine, strange 😵). And it is in the preview mode

**Comment by SlRvb** [comment]
Ah _dang_, I don't have an iPad to test it. Seems like it's undoing the css I had for bullets which is strange 🤔

**Comment by zcysxy** [comment]
Np. Let me do some test 🤔

**Comment by zcysxy** [comment]
Turned out to be an OS version specific bug. I updated the system and the bug is gone. 🥳
