### ISSUE TITLE
[Bug] Overlapping Callouts in Viewing Mode

### ISSUE THREAD

**Issue by ordinarysimplicity** [SlRvb/Obsidian--ITS-Theme#142]
### Describe the bug
When including transclusions in notes, Right side infobox is hidden behind transclusions in viewing mode.

**Expected behavior**
Transclusions should wrap in the available space instead of covering infoboxes.

### To Reproduce
1. Add an infobox with several items.
2. Add transclusions to the note.
3. Switch to viewing mode.

### Screenshots

![Screenshot (136)](https://user-images.githubusercontent.com/55848900/193177315-c728d0a8-1dc8-4923-a80c-0bf13ab00f8b.png)

### OS
Where does the bug occur? Windows 10

- [ x ] Desktop
- [ ] Mobile

Obsidian Version: 0.15.9

**Comment by SlRvb** [comment]
This should be fixed now with ITS v0.6.9
