### ISSUE TITLE
[Bug] The callout editor interface is strange and has a reference formatting style

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#144]
### Describe the bug
The callout editor interface is strange and has a reference formatting style

### Screenshots
![image](https://user-images.githubusercontent.com/30563826/194688063-db71b9cf-c200-4405-beaa-6aed25259807.png)

![image](https://user-images.githubusercontent.com/30563826/194688099-2c184f0f-5575-4fd5-bd89-ac8cfee9ec15.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.16.5

**Comment by SlRvb** [comment]
Hmm that does look very strange and I can't recreate it, can you put the markdown for this so I can try to replicate this issue?

**Comment by Borber** [comment]
Yes, it's great.
