### ISSUE TITLE
Vertical note names not displayed when using 'Stacked' tabs in Obsidian v1.0

### ISSUE THREAD

**Issue by Frosty017** [SlRvb/Obsidian--ITS-Theme#149]
### Describe the bug
When a number of notes are open in Stacked view in Obsidian, a void is displayed instead of the names of the notes displayed vertically (see attached screenshot).
![image](https://user-images.githubusercontent.com/60009713/195722898-6ba5844b-f02b-4005-93f4-e9a2598eaa25.png)

### To Reproduce;
1. Open a number of notes in Obsidian
2. Ensure that Stacked Tabs is enabled
3. Horizontally scroll the notes such that they accumulate to the left of the interface

### OS;
Windows 10

- [X] Desktop
- [ ] Mobile

Obsidian Version: v1.0

**Comment by SlRvb** [comment]
If you open the sandbox vault with my theme, does this occur? I can't seem to recreate this error on my theme. I wonder if it might be a rogue plugin or something.

**Comment by Frosty017** [comment]
Good day,

I don't know what to tell you, it's fixed itself;
![image](https://user-images.githubusercontent.com/60009713/195993073-fef65c58-fafe-4d64-877a-1ba31919007e.png)

Sorry for wasting your time :)
