### ISSUE TITLE
Unable to adjust font size

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#15]
I can't seem to adjust the font size, either by setting or Ctrl + scroll wheel

**Comment by SlRvb** [comment]
Yeah, font size adjustments are actually possible using the Style Settings plugin, you can adjust it there.

**Comment by Borber** [comment]
> Yeah, font size adjustments are actually possible using the Style Settings plugin, you can adjust it there.

Okay, I'll try it.
