### ISSUE TITLE
Having issues with quotes and tab spacing...

### ISSUE THREAD

**Issue by SlRvb** [SlRvb/Obsidian--ITS-Theme#150]
### Discussed in https://github.com/SlRvb/Obsidian--ITS-Theme/discussions/148

<div type='discussions-op-text'>

<sup>Originally posted by **Frosty017** October 13, 2022</sup>
Hello and good day. Love the theme very much; been using it for months. 

I updated Obsidian to 1.0 and the theme as well and quotes now display strangely; the symbol is very far from the actual text,

![image](https://user-images.githubusercontent.com/60009713/195714359-a284a5b5-81c4-4280-a680-f8d0cb60ee55.png)

Additionally, I've always had this issue where text inserted after a tab spacing would have a grey line impaling what's written below it,

![image](https://user-images.githubusercontent.com/60009713/195714570-b978dc50-21ff-44dc-a797-d951c4b8b6f9.png)

Would appreciate some help on this. Thanks in advance!</div>

**Comment by SlRvb** [comment]
@Frosty017 Update my theme to v0.7.2+, is this fixed?

**Comment by Frosty017** [comment]
@SlRvb Sorry for the late reply, updated to 0.7.4 and the quote symbols are completely gone now. So, effectively, that's fixed.

The second issue, the grey line through tabbed paragraphs is still seemingly present;
![image](https://user-images.githubusercontent.com/60009713/197066145-5d37b198-68de-4905-b95d-4f04fca7e791.png)

Thank you very much for your reply, I greatly value your work.

**Comment by SlRvb** [comment]
I believe this should be fixed now in v0.7.5, do let me know if this is fixed

**Comment by Frosty017** [comment]
It indeed did work;
![image](https://user-images.githubusercontent.com/60009713/197251662-13e12d79-f62e-4af9-aa5e-8a1abeafcb83.png)

Looks very nice if you have indented lists too; 
![image](https://user-images.githubusercontent.com/60009713/197251931-40e24b8a-4ed8-4a02-a37c-0988d42deff0.png)

Thanks a lot for your work and prompt responses. Feel free to close the issue. 🙏
