### ISSUE TITLE
[Bug] Broken Timeline Callout

### ISSUE THREAD

**Issue by EdualcLaiv** [SlRvb/Obsidian--ITS-Theme#152]
### Describe the bug
The timeline callout is not rendered properly.
It's not correctly centered (especially the 🕛icon), and the vertical line looks broken.

**Expected behavior**
It should look as showed in your guide:
![image](https://user-images.githubusercontent.com/4270058/196251494-cac9979e-bbb8-4635-96d2-6b2aca84a88b.png)

### To Reproduce
1. Install the theme in a new vault
2. Use following code:

```markdown
> [!timeline|t-l] **Title** _Subtitle_
> Left aligned timeline piece

> [!timeline|t-r] **Title** *Subtitle*
> Right aligned timeline piece

> [!timeline|t-l] **Title** _Subtitle_
> Left aligned timeline piece

> [!timeline|t-r] **Title** *Subtitle*
> Right aligned timeline piece

```

### Screenshots
![image](https://user-images.githubusercontent.com/4270058/196251275-a684ad68-8f3e-490f-a617-9502986c8bb8.png)

### OS
Where does the bug occur?

- [x] Desktop
  - Windows 10
- [ ] Mobile
  - I didn't test it on mobile

- **Obsidian Version**: V1.0
- **Theme Version**: 0.7.0

**Comment by EdualcLaiv** [comment]
I forgot to point out that I tried to use the snippet without the whole theme and got same problems.

**Comment by SlRvb** [comment]
Should be fixed now with ITS v0.7.4 :) 

Let me know if it worked!

**Comment by EdualcLaiv** [comment]
The theme is fixed! 👍 

But it seems you didn't updated the snippet :
https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Callouts.css

Could you copy and paste your fix here as well? 🙏

**Comment by SlRvb** [comment]
I've pushed the fix for the snippet as well now, do let me know if that works there as well :)

**Comment by EdualcLaiv** [comment]
It works fine with default theme now.

Thanks a bunch!

**Comment by viluon** [comment]
I think there are still glitches in the theme, shouldn't the timeline stretch between events?
![image](https://user-images.githubusercontent.com/7235381/199047261-496dc875-9d36-4f8e-a2f2-df2b0c3f6e9a.png)

**Comment by viluon** [comment]
@EdualcLaiv did you experience the issue above?

**Comment by EdualcLaiv** [comment]
Nope. What's your exact markdown here?

**Comment by viluon** [comment]
@EdualcLaiv
```md
> [!timeline|t-l t-3] **foo** _744 AI_

> [!timeline|t-r] **bar** _734 AI_

> [!timeline|t-l t-2] **oof** _702 AI_
```
renders as
![image](https://user-images.githubusercontent.com/7235381/202893427-a6b975a1-2d0b-49e7-9324-4ac10f52d970.png)
