### ISSUE TITLE
Numbered list with disappeared number

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#155]
### Describe the bug
Numbered list does not show number. It just happened recently. 

**Expected behavior**
Numbered list should show number.

### To Reproduce
1. Create a bullet list
2. Create numbered list as sublist in the bullet list
3. See error

### Screenshots
- Edit mode
<img width="79" alt="2022-10-22_19 01 34_CSX" src="https://user-images.githubusercontent.com/98799613/197369585-95c27eab-cfe4-4cae-8d23-26cf1bebc115.png">

- Reading mode
<img width="89" alt="2022-10-22_19 01 44_CSX" src="https://user-images.githubusercontent.com/98799613/197369591-bf6b5de6-a0b7-4a3c-a8c8-dae3e9e6aad7.png">

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v1.0.2

**Comment by SlRvb** [comment]
I think I've seen this bug crop up in the insider circles that wasn't using my theme, so I think I'll wait and see if that gets fixed there.

**Comment by SlRvb** [comment]
Is this still an issue? Feel free to reopen the issue if it still is, I can't seem to replicate it.

**Comment by Missionary2112** [comment]
It's working fine now. Thank you.
