### ISSUE TITLE
[Bug] Embed or transclude blocks of lists/tasks are rendered strangely in Obsidian v1.0.2

### ISSUE THREAD

**Issue by vishae** [SlRvb/Obsidian--ITS-Theme#156]
When I enter an embed of a list of items, this is what I expect to see:

Example embed using Default theme (Live Preview)
<img width="690" alt="image" src="https://user-images.githubusercontent.com/6110232/197579740-b173b0ca-dc23-437d-a619-05b946514fb4.png">

However, this is what I see with ITS theme (Live Preview):
<img width="721" alt="image" src="https://user-images.githubusercontent.com/6110232/197580020-acb43ab2-c93a-4c3d-87d7-2729ddf07c3b.png">

As you can see, the first checkbox is missing a border (this persists even if I'm in reading mode), and the bullet points are duplicated (this disappears in reading mode).

Not sure if this is a problem with Obsidian v1.0 since I'm currently running Obsidian v1.0.2.

**Comment by SlRvb** [comment]
Should be fixed in v0.7.6 :)
