### ISSUE TITLE
[Bug] Title/Path Bar wraps long paths causing wide bar at the top of the screen

### ISSUE THREAD

**Issue by vishae** [SlRvb/Obsidian--ITS-Theme#157]
### Describe the bug
If a file has a long pathname, the title bar at the top of the page attempts to wrap the text, causing the title bar to take up a lot of room at the top of the page. Please see screenshot:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/6110232/197582321-25cd19eb-097b-4cfa-983a-2f1ba624cfb0.png">

This may not be an issue on large monitors but can make the theme hard to use on smaller monitors/zoomed-in resolutions/mobile.

**Expected behavior**
Unwrap the text in the title bar.

Example in the default theme:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/6110232/197582832-e8d671b2-d812-455c-8278-9fbf8fa60b05.png">

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

Obsidian Version: 1.0.2

**Comment by SlRvb** [comment]
You'll probably want to go into the Style Settings and toggle off `Note Elements > Note Title > Wrap Note Title`
