### ISSUE TITLE
[Bug] Headings won't collapse!!!

### ISSUE THREAD

**Issue by AKasera** [SlRvb/Obsidian--ITS-Theme#159]
Obsidian version 1.0.3

Headings won't collapse and the line numbers and headings are kind of in each other's way

![image](https://user-images.githubusercontent.com/15956410/199154094-258ffa87-03ad-47b5-bf9a-6f753416d933.png)
This is what it looks like
And the big problem is every time I try to click the little arrow that normally collapses or reveals the content within the heading, it won't respond. It works on other themes except ITS but I really like ITS.

**Comment by SlRvb** [comment]
Should be fixed now with v0.7.9 :)

**Comment by joleen-bothma** [comment]
I have updated to the latest version as of yesterday. However, for me, the collapse arrows are overlapping with the heading indicator (H2/H3/etc.)

<img width="267" alt="Screenshot 2022-11-04 at 10 18 01" src="https://user-images.githubusercontent.com/40122335/199925545-0dadfcd4-16ed-4c64-acd7-799d6a4c458a.png">
