### ISSUE TITLE
Support for side-by-side display of images and Auto Scaling Size

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#16]
like this https://github.com/iEchoxu/obsidian_orange

![image](https://user-images.githubusercontent.com/30563826/127453313-2ecec7f3-ba71-47f1-9df9-6a87b8016aa8.png)

**Comment by SlRvb** [comment]
ITS now supports using image grid! Just reupdate the theme in the Community Themes Tab and it should work.

**Comment by Borber** [comment]
https://github.com/radekkozak/discordian/blob/master/.theme/mixins/images-addons.css  I found a more powerful css. that can replace the one above, and if oh I want to do magic on your theme, what should I do, I didn't find something like package.json.

**Comment by Borber** [comment]
And, I want the image to be centered by default
