### ISSUE TITLE
[Bug] Spacing in numbered lists is awkward and too large

### ISSUE THREAD

**Issue by AKasera** [SlRvb/Obsidian--ITS-Theme#160]
The spacing between the text and the numbering of the list is too large and looks awkward

**Expected behavior**
![image](https://user-images.githubusercontent.com/15956410/199154854-10a3b9c5-b1d1-4597-a491-8a4178a6a72b.png)

### To Reproduce
Create a Numbered List

### Screenshots
![image](https://user-images.githubusercontent.com/15956410/199154913-481680a0-0fa3-4b31-a605-ce87bca20764.png)

### OS

- [ x] Desktop
- [ ] Mobile

Obsidian Version: 1.0.3

**Comment by SlRvb** [comment]
Are you sure you don't have a snippet affecting that? I can't seem to recreate that spacing 🤔
![Obsidian_uqq9K1ypxq](https://user-images.githubusercontent.com/54087190/199634554-c3e0838b-4a9a-49a8-8cdc-6c91197711c0.png)
