### ISSUE TITLE
[Bug] Hover editor cannot be resizec

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#164]
### Describe the bug
Using the theme, the Hover Editor pane cannot be resized fully in height.

**Expected behavior**
Using the default Obsidian theme, the pane can be resized normally, not limited in height.

### To Reproduce
1. Use ITS theme
2. Install Hover Editor plugin
3. Hover a page link, hover editor shows
4. Resize the pane, you are limited in height

### OS
Windows 10

Obsidian Version: 1.0.3

### Additional context

Seems your theme is not the only one affected, see the last post in this issue:

https://github.com/nothingislost/obsidian-hover-editor/issues/194

**Comment by SlRvb** [comment]
Should be fixed in the ITS beta. Feel free to reopen if it's not fixed.
