### ISSUE TITLE
[Bug] Image positioning Snippet doesn't work in Live Preview

### ISSUE THREAD

**Issue by ThiagoRangel7** [SlRvb/Obsidian--ITS-Theme#165]
### Describe the bug
Trying `![[image.png|right]]` or `![[image.png|left]]` doesn't work in Live Preview mode. `center` appears to work.

**Expected behavior**
Image should float to the left or to the right depending on the keyword used.

### To Reproduce
Insert an image with the `right` or `left` modifier **in the default theme** (not ITS theme)

### OS
Windows 10 LTSC 2021

- [ x ] Desktop
- [ ? ] Mobile

Obsidian Version:
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.3
	Operating system: Windows 10 Enterprise LTSC 2021 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Mathpad v0.8.6
		2: Advanced Tables v0.18.0
		3: Editing Toolbar v2.2.2

**Comment by SlRvb** [comment]
Should work now on theme v0.8.8 (and snippet) if you add `lp` to your images. 

```
![[image.png|left lp]]
```

I will warn that if editing in Live Preview gets weird and/or becomes hard target around the image to remove `lp`.
