### ISSUE TITLE
[FR] Apply dark theme to editor

### ISSUE THREAD

**Issue by Blackhawke** [SlRvb/Obsidian--ITS-Theme#166]
I'm not sure why this is true, but in every theme I've looked at, even the "dark" ones, the editor has a light background, not the same, or similar dark background used in Preview.

For the rewrite, I'd like to see the ITS honor "dark mode" in the editor too. It's really blinding to go from the nice dark scheme to the blindingly light background and hard-to-read off-white text in the editor. I'm not suggesting the two be identical. That could create confusion. But *similar* would be nice.

**Comment by SlRvb** [comment]
I'm a bit confused, are you asking for a black background for darkmode?

**Comment by Blackhawke** [comment]
I'm asking for the editor to have a "dark mode" too. Or, at least a a dark
background.

**Comment by SlRvb** [comment]
The editor does have a darkmode 🤔. If yours doesn't, then something is very wrong on your end 🤔. If I could see a screenshot of your editor not having darkmode that would be very helpful as well as if you're using the legacy editor maybe? That should also have a darkmode background so not sure what could be going wrong there.

**Comment by Blackhawke** [comment]
Hmm...

Well, you may be right. I've noticed that there are a lot of plugins that won't even work on this tablet (Tab S6 Lite) and, I use it for a lot of art and the dev of the app I use says this particular tablet is a pain in the a$$ sometimes.

Anyway, I've attached a screenshot. If you can tell me, where are the controls to set dark mode in the editor? I've looked. I don't find them.

![Screenshot_20221231_113620_Obsidian.jpg](https://user-images.githubusercontent.com/1757829/210154277-c523d5eb-de59-4724-ae6e-30e7e24fd883.jpg)

**Comment by SlRvb** [comment]
Oh gosh, that's pretty bad. Any change to toggle on restricted mode and disable snippets to see if something might be going wrong there?

**Comment by Blackhawke** [comment]
Bingo! You nailed it. The CardView plugin was overriding the theme settings.

Thanks for your help!
