### ISSUE TITLE
[FR] Flex to Function on Columns Callout without SubCallout Header.

### ISSUE THREAD

**Issue by sigrunixia** [SlRvb/Obsidian--ITS-Theme#168]
Not sure if this is a feature, or a bug. It works on text and non-stat block text but I did not try it on other code blocks so it may be a bug? Anywhere, here I go!

### Is your feature request related to a problem? Please describe.
Currently in both snippet and theme form, If you define `[!columns|#]` You can use Individual columns without secondary subcolumns callout boxes `>>[!info] Hello!`.

However, if using `[!columns|flex]`or `[!columns|flex #]`, the individual columns must have have a secondary callout box ignorer for the snippet or theme to load and apply flex correctly.  

If `[!columns|flex|#]` is used, the columns will load and flex function will be ignored. 

### Describe the solution you'd like
Uniformity between how the column callouts function is expected. If I can have no subcolumns callouts on `[!columns|3]`, I expect the same on flex. 

### Describe alternatives you've considered
If that is not doable, then you may need to add in a statblock call similar to how you added a dataview one. That seems like it could get out of hand real quick though on your end. 

### Additional context
<img width="702" alt="Just-fine" src="https://user-images.githubusercontent.com/68425372/209682367-96c114d3-5be7-4981-b149-cb42d7e78175.png">
Columns Flex working as normal

<img width="702" alt="columns-flex-broken" src="https://user-images.githubusercontent.com/68425372/209682515-092338df-43b0-4b24-b172-76ed9479a195.png">

Flex Broken

<img width="702" alt="columns-flex4-broken" src="https://user-images.githubusercontent.com/68425372/209682677-6d615630-02f0-4127-8059-3b561f70d5c1.png">

Flex 4 Also Broken, but happy quotes load.

![columns-3-yay](https://user-images.githubusercontent.com/68425372/209683115-bd476132-10eb-4f16-9ca9-35b3138ce67e.png)

Columns 3 Loads fine. My apologizes for the different screenshot view as the Acolyte and Goblin in 1 and 2 loaded perfectly; it is necessary to display how it did load the first three horizontally and placed the Orc on the next line. 

### Obsidian Info
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.0.3
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 22.2.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: ITS Theme v0.8.86
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 20
	Plugins enabled: 1
		1: TTRPG Statblocks v2.23.4

**Comment by SlRvb** [comment]
Technically, the way I made the snippet is only really supposed to work with the subcallouts, not without 😬 The template on the guide includes the subcallouts, reason being that if you have different types of elements under each other (ie. p, ul, blockquote), each of those then get put into a column of their own when they're supposed to be in 1 column.

**Comment by sigrunixia** [comment]
I figured that was the unwitting case. :) I'm all for uniformity so whichever you choose to do, works for me. It's your theme, after all. :D
