### ISSUE TITLE
[FR] Allow aligned right images have "boxes"

### ISSUE THREAD

**Issue by f3ss1** [SlRvb/Obsidian--ITS-Theme#169]
Hey!

The idea might not really be straightforward from the text so it's better to relate to the picture.

It is what I have now:

![image](https://user-images.githubusercontent.com/48713543/210358134-6ce59382-13ba-41b5-b7ac-0cd8c3753e06.png)

What I want is the ruler to be complete and below the image. So any text which would come after it would be below the image too and would use all the text width kinda like that:

![image](https://user-images.githubusercontent.com/48713543/210357999-1cde420f-3f66-48b6-906c-ec8df288e32a.png)

So I really would like this to be an option (maybe a magic word in image?) since it really looks kinda ugly now.

I hope it makes sense. This might already be a feature but I really did not find anything up at the moment.

**Comment by SlRvb** [comment]
Added feature in the ITS Beta as a [cssclass](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Image+Adjustments#CSS+Classes) and as a toggle in the style settings under:
`In The Shadows Settings > Note > Images > Clear Images With Horizontal Lines`

**Comment by f3ss1** [comment]
For some reason, I cannot see the "Images" setting so there is no option to toggle this for me. What am I doing wrong? Updated the ITS theme from obsidian, nothing else done.
