### ISSUE TITLE
Indented list weird rendering

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#170]
### Describe the bug
Indented list renders incorrectly. Initially, I thought the issue was about the indented list in highlight `== ... ==`.

**Expected behavior**
Indented list should renders normally

### Screenshots
**Edit Mode**
![2023-01-11_20 18 48_CSX|200](https://user-images.githubusercontent.com/98799613/211975193-2b04b61f-6c53-4990-bd9b-6eb2dbf2883f.jpg)

**Read Mode**
![2023-01-11_20 18 59_CSX|200](https://user-images.githubusercontent.com/98799613/211975204-3884f87a-b664-4f42-bf63-943fc456d658.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v1.1.11

**Comment by SlRvb** [comment]
I can't seem to recreate this in the beta so I think this might be a fixed issue. Feel free to reopen if it's not
