### ISSUE TITLE
[FR]How do I remove this pesky underlining of titles?

### ISSUE THREAD

**Issue by linfengtongxue70** [SlRvb/Obsidian--ITS-Theme#171]
Dear developer, 
         Hello! I am a big fan of the ITS theme and even recommended it to my friends. however, I found the underline in this theme so annoying that I wanted to remove it. i was not sure where the option to remove it was and I even went to learn HTML and CSS in order to do this. however, after two days of learning, I have to admit that I am not good at coding. 
         I hope I can get your help and continue my original work as soon as possible.

尊敬的开发者，
你好！
我是ITS主题的忠实粉丝，甚至还向我的朋友推荐它。然而，我发现这个主题的下划线如此让人讨厌，我希望删除它。我不清楚哪里有选项可以删除它，我甚至为了做到这件事，去学习HTML和CSS。然而，经过两天的学习后，我得承认，我不擅长代码。
我希望能得到你的帮助，并且尽快地继续我原本的工作。

![image](https://user-images.githubusercontent.com/91956234/216030110-ae2e85d3-9f0d-4b30-8067-d70ca732bce6.png)

**Comment by SlRvb** [comment]
In the Style Settings: `In The Shadows Settings > Note Elements > Headers > Heading Underlines > Hide Header Underline`
