### ISSUE TITLE
[Bug] text of monster names in TTRPG Statblocks plugin wrong style applied

### ISSUE THREAD

**Issue by Zorgatone** [SlRvb/Obsidian--ITS-Theme#172]
### Describe the bug
See bug https://github.com/valentine195/obsidian-5e-statblocks/issues/136

Wrong style is applied on titles for statblock monster names.

I'm using Obsidian v1.1.9 on Windows 10, with TTRPG Statblocks v2.24.5, and with the ITS - WOTC/Beyond - Alternate Theme

**Expected behavior**
I expect the red line not to be there and the name taking the full space on the same line

### To Reproduce
1. Install and apply on latest Obsidian Theme: ITS - WOTC/Beyond - Alternate
2. Install plugin obsidian-5e-statblocks and activate it
3. Make statblock with a creature name of medium length
4. See styling

### Screenshots
![image](https://user-images.githubusercontent.com/2664036/216775011-c81c80ed-b7e2-469a-a1d7-f5da570ab52b.png)

### OS
Windows 10

- [x] Desktop
- [ ] Mobile

Obsidian Version:
I'm using Obsidian v1.1.9 on Windows 10, with TTRPG Statblocks v2.24.5, and with the ITS - WOTC/Beyond - Alternate Theme

**Comment by SlRvb** [comment]
Fixed in the ITS v1 beta. If you wish to access that feature now, you can download the ITS v1 Beta by following the instructions in the link about the beta under the Guide in the Readme.
