### ISSUE TITLE
[Bug] ITS image size CSS classes interfere with the Obsidian mobile 'Image Zoom' feature

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#174]
### Describe the bug
Obsidian mobile has a built-in equivalent of the ITS 'Image Zoom' option. The feature normally centers the image over the page and shows it at full size or fills the screen. While it ignores the native Obsidian image size adjustments (`![[image.jpg|100x100]]`) it doesn't handle the ITS image size CSS classes and the image is shown at the size specified through the ITS CSS classes instead of the full image size.

e.g. `![[image.jpg|htiny cover]]` will show the image with a height of `100px` even if the source image is much larger.

**Expected behavior**
Ideally ITS size & positioning adjustments should be disabled when the image is viewed with the mobile image viewer. Currently only the size is causing issues but disabling positioning stuff in that viewer is probably the safe choice as well.

### To Reproduce
* Add a note with an embedded image using an ITS size CSS class.
* Tap the image on mobile.

### OS
Obsidian Mobile 1.4.1 on iPad OS 16.3

### Additional context

The mobile image viewer seems to use the `mobile-image-viewer` CSS class which can be used to gate CSS based on whether one is in the image viewer or not.

I am currently using the following hacky CSS snippet as a workaround but this can probably be solved more cleanly in ITS itself by disabling the relevant adjustments when the image is in the image viewer.

```css
.mobile-image-viewer img {
    height: 100% !important;
    width: 100% !important;
    object-fit: contain;
}
```

**Comment by SlRvb** [comment]
Should be fixed now in the ITS Beta update 🥳  c878dbcb15376ef68454e89404085dd539b44fb3
