### ISSUE TITLE
[Bug] `infobox` callout doesn't react to screen size in the mobile client

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#175]
### Describe the bug

The `infobox` callout normally creates a sidebar on desktop as long as the note area is wide enough for it to float next to the main body.

In the mobile client, it never seems to display as a floating sidebar even on larger tablet screens.

**Expected behavior**

On tablet screens, when the document area is wide enough, `infobox` should show as a floating sidebar like in the desktop version.

### OS

Obsidian Mobile 1.4.1 on iPad OS 16.3 on an iPad Pro (12.9'')

### Additional context

The floating sidebar CSS stuff is probably simply disabled when on mobile. This probably makes sense for phone size screens but not on large tablet screens.
I don't know if obsidian has any CSS classes that indicate phone vs. tablet devices but I assume that at least media queries should just work as usual to restrict this based on document width like on desktop.
But I haven't really looked into it so these are just assumptions.

**Comment by SlRvb** [comment]
You can use the `|mobile` adjustment to override that and get it working on mobile. I will add the ability to check screen size to allow it to float when it should an shouldn't

**Comment by SlRvb** [comment]
Fixed to allow floating on tablets but not mobile in the ITS v1 beta, thanks!
