### ISSUE TITLE
[Bug] left and right not working as intended

### ISSUE THREAD

**Issue by herrozerro** [SlRvb/Obsidian--ITS-Theme#178]
### Describe the bug
When following this guide https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Guide/Image-Positions.md#leftright, I am just using the snippet, most things work, but left and right do not.

**Expected behavior**
For left and right, according to the guide it should put the image to the right or left with the text wrapping.  I use the following code but All I get is the below screenshot.  If I use right, it's the exact same

![[Pasted image 20230216110218.png| left | 200 ]]

### To Reproduce
1. download https://raw.githubusercontent.com/SlRvb/Obsidian--ITS-Theme/main/Snippets/S%20-%20Images%20Adjustments.css to my snippets folder
2. add the image
3. Add the left or right modifier

### Screenshots
![image](https://user-images.githubusercontent.com/2041213/219482732-1173610b-cd16-463b-9263-d20064a8af89.png)

### OS
Where does the bug occur?

- [ ] Desktop, EndeavourOS

Obsidian Version: 1.1.9

**Comment by SlRvb** [comment]
If this is in live preview, it's not meant to work there to avoid editing issues. https://github.com/SlRvb/Obsidian--ITS-Theme/issues/165
