### ISSUE TITLE
[FR] images-addons

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#18]
https://github.com/radekkozak/discordian/blob/master/.theme/mixins/images-addons.css  I found a more powerful css. that can replace the one above, and if oh I want to do magic on your theme, what should I do, I didn't find something like package.json.

_Originally posted by @Borber in https://github.com/SlRvb/Obsidian--ITS-Theme/issues/16#issuecomment-890986932_

**Comment by Borber** [comment]
And, I want the image to be centered by default

**Comment by SlRvb** [comment]
I've incorporated some of the image stuff from what you've linkeed into ITS in this new update, so you should be able to do almost the same thing. There's a new Style Setting toggle called `Center Images` under the Note Elements section that should do what you want.

Check this for more information: https://forum.obsidian.md/t/theme-its-dark-light-theme/12838/126

---
> ... oh I want to do magic on your theme, what should I do, I didn't find something like package.json.

I'm not sure what you mean by doing magic on my theme, but having a CSS snippet file in your repo should be enough to fiddle with the CSS in a way that isn't going to be overridden by updates.

**Comment by Borber** [comment]
Thank you so much, ITS is my favourite theme and I'm looking forward to seeing how great ITS will be when WYSIWYG comes out!
