### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TristGit** [SlRvb/Obsidian--ITS-Theme#180]
### Describe the bug

Too much work to merely say that changing fonts within your theme does not work with nothing but Style Settings and the ITS theme itself. Have tried, latest versions of all, with 3 seperate fresh Obs installations.

Going into your fields and changing them simply does not work, meanwhile, changing into other themes outright does. Most font related changes; size, family, etc doesnt even work. Most fields change nothing in your theme, so what am I missing, here?

**Comment by SlRvb** [comment]
Old version of ITS was made before the v1 changes were applied so they don't work as well, the beta of ITS v1 fixes this issue and it will be fixed when ITS V1 is released.
