### ISSUE TITLE
[Bug] Only half of code block type displayed

### ISSUE THREAD

**Issue by toysoldier2012** [SlRvb/Obsidian--ITS-Theme#181]
### Describe the bug
Only half of code block type displayed

### To Reproduce
1. Create new note
2. Create a code block by ```
3. Give a name to this code block, like Java
4. Move out of the code block to see the error

### Screenshots
<img width="551" alt="image" src="https://user-images.githubusercontent.com/17837501/220629256-9bfaf827-d0d7-4993-8de2-622336006496.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/17837501/220629491-d04bd80d-39d9-4940-91fa-ea0f497b8c41.png">

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile(not yet tested)

Obsidian Version:
1.1.9

**Comment by SlRvb** [comment]
Should be fixed in the v1 beta.
