### ISSUE TITLE
Image is not resized in preview pane

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#182]
### Describe the bug
The image is not resized in preview pane

**Expected behavior**
The image should be resized in preview pane

### To Reproduce
1. Embed an image. E.g. `![[Frosthaven.png|100]]`
2. Preview a file with the image
3. See error: the image is not resized to `100` but it retains its original size

### Screenshots
- Default theme image is resized in preview pane
![2023-02-23_17 22 49_CSX](https://user-images.githubusercontent.com/98799613/221069137-ae2171d2-a3de-4196-a54c-c4096bfa7f19.jpg)

- ITS theme image is not resized in preview pane
![2023-02-23_17 22 23_CSX](https://user-images.githubusercontent.com/98799613/221069025-6be378c7-c440-46d3-8f10-a08d1987cfac.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: V1.1.15

**Comment by SlRvb** [comment]
Preview pane? Do you mean Popover or do you mean Reading view?

**Comment by Missionary2112** [comment]
I mean Popover.

**Comment by FireIsGood** [comment]
Seems to be the `.popover.hover-popover img:not([alt=""]):not(.cm-widgetBuffer):not(.emoji):not(.link-favicon)` selector which doesn't account for images with the [built-in image dimensions](https://help.obsidian.md/Linking+notes+and+files/Embedding+files#Embed+an+image+in+a+note). This can be fixed by adding `:not([width])` to the popover class.

**Comment by FireIsGood** [comment]
Ah, a better solution would be to remove the `width: 100%` declaration to cap out overly wide widths (e.g. width of 800px would overflow in the previous solution idea) but allow for the desired smaller width images.

I'll put up a pull request to fix it.

**Comment by SlRvb** [comment]
This should now definitely be fixed in the beta.
