### ISSUE TITLE
Timeline Spacing not rendering correctly 

### ISSUE THREAD

**Issue by zoccer5555** [SlRvb/Obsidian--ITS-Theme#183]
### Describe the bug
If i use the spacing feature of the timeline, there is no line between the individual entries

**Expected behavior**
All the topics should be connected, even with the parameter t-number

### To Reproduce
The following is the edit view:

> [!timeline|t-l] **Title** _Subtitle_
> Left aligned timeline piece

> [!timeline|t-r] **Title** *Subtitle*
> Right aligned timeline piece

> [!timeline|t-r t-1] **Title** *Subtitle*
> Spaced timeline piece

This is the result:

![grafik](https://user-images.githubusercontent.com/125312164/221172618-307fa6a1-c7d2-4af7-a373-97e737e44b40.png)

### OS
Where does the bug occur?

- Desktop

Obsidian Version: 1.1.15, Installer Version 1.1.9

### Additional context
I disabled every css snippet i'm normally using to test this. I also tried to just use the css snippet for the callouts.

**Comment by SlRvb** [comment]
I believe something had changed in the css for callouts that broke it when obsidian v1 came out. I'll check again to see if I can find a way to restore it, but that's what I remember from the last time I tried to fix it.

**Comment by SlRvb** [comment]
Restored this functionality in the current ITS Beta 🥳 413491c4e99fcbacb1a665c924951ba4c91cb1b8
