### ISSUE TITLE
[FR] How to center headings one while leaving the other headings unchanged

### ISSUE THREAD

**Issue by linfengtongxue70** [SlRvb/Obsidian--ITS-Theme#184]
How to center headings one while leaving the other headings unchanged
Now it seems that you can only center all headings, and you can't set headings one individually

Also, as far as I know, ITS theme is the most popular theme in China besides bluetopaz theme. Are you interested in translating these options for your loyal Chinese users? Maybe this will make your work more popular!

**Comment by SlRvb** [comment]
I believe you should be able to center it in the Specific Heading options, but if that's not there, in ITS version 1 (also the beta if you want to test that) has the ability to do that.

I don't know chinese so I can't translate it myself, but I'm willing to accept translations for languages. Not sure how to do that exactly, but I'm willing to figure it out.

**Comment by linfengtongxue70** [comment]
Certainly, I was able to locate the option for centering text within the "Header Alignment" settings. I truly appreciate your prompt response. Thank you very much!

If you have plans to translate it into Chinese, perhaps I can assist you with a portion of it. I would be happy to provide you with a translated document by March 1, 2023, if you find my services satisfactory.

Lastly, I wish you and your family good health and happiness. Take care!
