### ISSUE TITLE
[Bug] Can't position web-based images in live preview

### ISSUE THREAD

**Issue by Antyos** [SlRvb/Obsidian--ITS-Theme#186]
### Describe the bug
Position tags (left | right | center) don't work on embedded web-based images (from a URL) in Live Preview.

**Expected behavior**
The `left`, `right`, and `center` tags in images should appropriately position the image in Live Preview mode.

### To Reproduce
Include in any markdown file:
```markdown
![img|center](https://www.dummyimage.com/400x400)
```

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

### Versions
- Obsidian Version: 1.1.16
- ITS Theme Version: 0.8.87

**Comment by SlRvb** [comment]
https://github.com/SlRvb/Obsidian--ITS-Theme/issues/165

**Comment by Antyos** [comment]
Oops. I feel dumb. I even saw the other thread. Thanks!

**Comment by Antyos** [comment]
Actually, wait, it's still not working. There doesn't appear to be a `center lp` alt tag in the **S - Image Adjustments.css** snippet. Also, this bug only occurs for embedded web images. If the image is stored locally in my vault, e.g., `![[dummyImage.png|center]]`, then it works fine.
