### ISSUE TITLE
Links in checkboxes are not muted when checked out, but enhanced in bold

### ISSUE THREAD

**Issue by PhilippeKr** [SlRvb/Obsidian--ITS-Theme#189]
### Describe the bug

**Expected behavior**
I would expect the link to me muted, just like the rest of the text which changes colour.

### To Reproduce
1. Create a checkbox and put a link in the text.
2. Check the checkbox
3. See that the normal text is muted but that the link is bolded and in original bright colour

### Screenshots
![Screenshot 2023-04-04 203350](https://user-images.githubusercontent.com/77798281/229886226-c9a82d02-fd5f-431b-b7d0-afa94a723dc9.png)

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

### Versions
- Obsidian Version: 1.1.1.16
- ITS Theme Version: Current

**Comment by SlRvb** [comment]
Should be fixed in the beta now :)

**Comment by PhilippeKr** [comment]
Thanks. I've been looking at the beta on the site, but all the download links seem broken to me...

**Comment by SlRvb** [comment]
Ah could you look here again? I've update to reflect the new way to get the beta and its updates. https://publish.obsidian.md/slrvb-docs/ITS+Theme/ITS+Theme

**Comment by PhilippeKr** [comment]
Thanks, it works way better that way, easy to install and update.
And yes, it's corrected in the sense that the links are no longer in bold when the checkbox is checked, I would however like and expect that they got dimmed a bit like the rest of the text. Would that be possible ? Or is it in an option that I have not found ? Thanks in advance (and thanks again for a great them). :D

**Comment by SlRvb** [comment]
They should be dimmed I made sure links, tags, etc were dimmed if a checkbox was checked. Could you screenshot the checked task so I can see what's going on?

It should look like this:
![Obsidian_CfxidscwlW](https://user-images.githubusercontent.com/54087190/232605251-9e178a6a-a029-4bb8-982b-9245304ab402.png)

**Comment by PhilippeKr** [comment]
[image: image.png]
Here you go, and thanks for looking into it. It might just be wrong
configuration.

Philippe

**Comment by SlRvb** [comment]
I can't seem to recreate this issue, could you see if enabling restricted mode for plugins and disable all snippets. Just checking you have the beta theme installed via brat and not via snippets right?

**Comment by PhilippeKr** [comment]
Hi, apologies, I was on holidays, but I can confirm that the problem still
occurs even with restricted mode and disabling all snippets, including ITS
ones. And yes, the beta theme is installed by brat.

Thanks in advance,

Philippe

**Comment by SlRvb** [comment]
Ah I think I fixed it, can you update the beta again?

**Comment by PhilippeKr** [comment]
It did not work, so I tried to uninstall the theme and install it again to
make sure that I had the right version, but now it won't install:
[image: image.png]

Also, I checked what happened with the theme uninstalled, and the color
does not change, it's just that the text is crossed out when the checkbox
is checked (which I find less interesting than a colour change).

Thanks in advance,

Philippe

**Comment by SlRvb** [comment]
I'm not sure why it won't install (I also can't see the image), but you should just be able to run the command `Update beta themes` and that should get you the latest update. 

Not sure how you uninstalled my theme, but it should just install fine with running that command with BRAT installed.

**Comment by PhilippeKr** [comment]
Thanks a lot for the continuous support. It did not work at first for no
reason that I could discern, but it's perfect now, dimming the links as
well as the text.

Thanks again, you're the best !

Philippe
