### ISSUE TITLE
Headings move to the right, instead of center

### ISSUE THREAD

**Issue by psychsatani** [SlRvb/Obsidian--ITS-Theme#19]
The option to centre the headings with lines on either side puts the heading on the right instead of centre. Would really like this option to work, a solution to this bug will be much appreciated. I have attached the video that shows this. I am on 0.12.13 insider build. 

https://user-images.githubusercontent.com/78266798/128648989-a384666d-1a0f-467a-ae8d-441b60ab0b45.mov

**Comment by SlRvb** [comment]
Is this with the Style Settings `Center Headings` option? I can't seem to recreate this error.

**Comment by psychsatani** [comment]
Yes it is with style settings. They suggested I raise an issue here.  https://github.com/mgmeyers/obsidian-style-settings/issues/20

**Comment by psychsatani** [comment]
I just fixed it by unchecking the "hide header underline" option. I have updated this over the style settings page too. Thank you!

<img width="801" alt="image" src="https://user-images.githubusercontent.com/78266798/128795600-85f07ddc-9395-4151-a75d-e857b1a9f234.png">
