### ISSUE TITLE
Duplicate Style settings (with differences)

### ISSUE THREAD

**Issue by Cammagno** [SlRvb/Obsidian--ITS-Theme#196]
This is still true after installing beta1.
I think the second one is an old version, but no idea how to get rid of it.

![DoubleITSsettings](https://user-images.githubusercontent.com/95725064/235130681-5b9fa0bd-fd70-4520-9de5-e0e3494d2088.png)

#####

Since a while, I've a double set of Style Settings for ITS Theme, with similar but not identical options.

Any idea how can I get rid of the duplicate?

![image](https://user-images.githubusercontent.com/95725064/194783774-aabdb604-2f67-4a7a-bca9-d9702d7d5bf5.png)

_Originally posted by @Cammagno in https://github.com/SlRvb/Obsidian--ITS-Theme/discussions/147_

**Comment by SlRvb** [comment]
If you have my theme you should not need most of my snippets. Disable any snippets and reload obsidian. Does that fix it?

**Comment by Cammagno** [comment]
> If you have my theme you should not need most of my snippets. Disable any snippets and reload obsidian. Does that fix it?

I had none of your snippets active, but after your message pointing me towards snippets, I've checked all of them and find some of your snippet code included in one of my personalized snippets (hell knows when and why I did it), so yes thanks, now the problem is solved :)
