### ISSUE TITLE
[Bug] Link styling is lost when link includes markdown formatting

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#199]
### Describe the bug

Markdown links that include markdown formatting in the link text loose the link styling in the current ITS beta:

`[_Test **Link** Content_](https://obsidian.md)`

### Screenshots

Built-in theme:
<img width="160" alt="Screenshot 2023-05-13 at 10 45 36" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3801202/ffbc50dd-0455-4d70-9ca7-c1b21df099d7">

ITS beta:
<img width="168" alt="Screenshot 2023-05-13 at 10 45 53" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3801202/d5fd512d-b16f-4c01-b1d9-22e52c1bc64a">

### OS
Tested on macOS 13.4

### Versions
- Obsidian Version: Version 1.2.8 (Installer 1.2.8)
- ITS Theme Version: Latest beta release installed via BRAT

**Comment by SlRvb** [comment]
The links with the markdown formatting do look correctly styled to me on my end 🤔
![Obsidian_FSjiTKqzeZ](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/54087190/15689b0f-e7dc-4107-ba84-d51e221568d0)

 If you mean in comparison to the default theme, yeah I don't style my links like the default theme with an underline.

**Comment by Jnosh** [comment]
Yes, I just mean the link coloring difference in this case. I used the default theme just to compare whether obsidian by default retains the link styling when using bold or italics in the link text.

Here is a screenshot of two links, one with and one without formatting, using a new vault using ITS with default settings to better show the difference using just ITS:

<img width="230" alt="Screenshot 2023-05-14 at 23 30 06" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3801202/57fed6d2-ed63-4a92-a467-052c270d9444">

The link coloration is only missing in reading view, in editing view it is blue as usual.

Here is the sample vault with just ITS installed via BRAT and a note with those two links:
[Test.zip](https://github.com/SlRvb/Obsidian--ITS-Theme/files/11472974/Test.zip)

Looking at the styling in the developer tools shows that the styling for `em` and `strong` is overriding the inherited styling for `a.external-link`, specifically the color.
Seems in pre-1.0 ITS, `--italic-color` and `--bold-color` were set to `inherit` by default whereas in 1.0 they are set to `--text`.

**Comment by SlRvb** [comment]
Ah can you update to ITS v1.0.41 and see if this has been fixed?

**Comment by Jnosh** [comment]
👍 Working perfectly now!
