### ISSUE TITLE
Horizontal line in Edit mode

### ISSUE THREAD

**Issue by DutchPete** [SlRvb/Obsidian--ITS-Theme#2]
I have a snippet for stylized horizontal lines in both Edit and Preview.
Putting the 3 dashes results in this in **Edit mode**:

<img width="284" alt="line" src="https://user-images.githubusercontent.com/10794265/108162366-a277f100-70f5-11eb-9703-ebf2692dcd41.png">

That did not happen in the previous version of ITS.

This is the snippet I use:

[hor-line-grad.css.zip](https://github.com/SlRvb/Obsidian--ITS-Theme/files/5993521/hor-line-grad.css.zip)

**Comment by SlRvb** [comment]
Ah, I'd added a border to the top of the hr editor's line. Fixed in the next update! Thanks for showing me that snippet I was struggling with how to get the editor's hr to look the same!

**Comment by DutchPete** [comment]
Thank you.
