### ISSUE TITLE
Icons look like large pictures in preview

### ISSUE THREAD

**Issue by psychsatani** [SlRvb/Obsidian--ITS-Theme#20]
When I preview a linked note that has icon in it, the preview shows them in a massive size. It has not impacted test or other elements of the note. (see attached recording). This is new. I used to preview notes with icons in them before with the same theme but I always saw them as icons. Dunno what changed that. 

https://user-images.githubusercontent.com/78266798/129457713-c43526b1-a03f-4327-83e9-55bc6612d9cb.mov

Once again, thank you for this wonderful theme!

**Comment by SlRvb** [comment]
What plugin do you have for emojis?

**Comment by psychsatani** [comment]
I had emoji toolbar and icons plugins. Disabled both of them and the issue is resolved. Thank you!!

**Comment by SlRvb** [comment]
I think I fixed it with the current update so that you can still use the plugin and not have it broken on hover.

**Comment by psychsatani** [comment]
Yes I turned them on after adding the theme again and it is resolved. 🙏🏻

**Comment by psychsatani** [comment]
Hi. This issue has recurred. I noted it before updating to the new theme update and it has persisted with the new theme update as well.

**Comment by SlRvb** [comment]
Hmm, I can't seem to replicate that. I haven't touched any of the css for the popover so I'm not sure why it seems to have undone itself for you 🤔

**Comment by psychsatani** [comment]
I reloaded obsidian and it seems to have gone now. Maybe I tweaked something in style settings. Will update if it recurs.

**Comment by SlRvb** [comment]
Please do! 🙏

**Comment by SlRvb** [comment]
For now, I'll close this issue. Reopen it if it happens again 👍
