### ISSUE TITLE
[Bug] Infobox callout disappears after scrolling through it

### ISSUE THREAD

**Issue by bojtalepenye** [SlRvb/Obsidian--ITS-Theme#200]
### Describe the bug
I am trying to build my own wiki in obsidian. I use the infobox callout.
I added tables to it, and lots of details (Character's description)
As I am scrolling down, the callout disappears.
Note: I am only using the infobox callout css snippet. I am not using the theme!

**Expected behavior**
The callout shouldn't disappear, like for example in Wikipedia's website.

### To Reproduce
1. Create an infobox callout
2. Add information to it
3. Scroll down to the page
4. The infobox callout disappears
### OS
Where does the bug occur?
- [ ] Desktop

### Versions
- Obsidian Version: 1.2.8

### Additional context
Note: I am only using the infobox callout css snippet. I am not using the theme!
https://github.com/SlRvb/Obsidian--ITS-Theme/assets/62150968/4d6e9a71-ec34-404c-95dc-56b5d0b274ee

**Comment by SlRvb** [comment]
Same issue as those listed in #122. Unfortunately it's obsidian behavior so CSS alone can't fix it 😔
