### ISSUE TITLE
[Bug] dataview cards not working for me

### ISSUE THREAD

**Issue by Cammagno** [SlRvb/Obsidian--ITS-Theme#202]
Not sure if it's a bug or if I'm doing something wrong

Cards Callout with dataview or dvl is supposed to render as in this theme documentation
https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callouts/Callout+-+Cards

Instead, i only get empty boxes if using the "dataview" attribute, or a single column if I use the "dvl" attribute
(see screenshot)

This happens on Desktop, Obsidian 1.3.1, ITS 0.8.87 (Dataview 0.5.55)

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/95725064/fb4e1810-e001-4110-bf88-01825094ea1d)

**Comment by Cammagno** [comment]
> This happens on Desktop, Obsidian 1.3.1, ITS 0.8.87 (Dataview 0.5.55)

Just to update:
issue still present in ITS 1.0.10 Obsidian 1.3.4,  (Dataview 0.5.56)

**Comment by SlRvb** [comment]
Hmm I'm not able to recreate this issue on my side 🤔 Any chance you could share the markdown one of the notes this query is pulling from?

**Comment by Cammagno** [comment]
> Hmm I'm not able to recreate this issue on my side 🤔 Any chance you could share the markdown one of the notes this query is pulling from?

Sure!
Just to create no confusion, I upload the first shown in the picture (but it's the same for all of them):
[Munchkin South Park - Detective.md](https://github.com/SlRvb/Obsidian--ITS-Theme/files/11581236/Munchkin.South.Park.-.Detective.md)

If somehow useful, this is instead the md note in which the query is placed (once again, this also happens in other similar ones):
[Class.md](https://github.com/SlRvb/Obsidian--ITS-Theme/files/11581238/Class.md)

**Comment by SlRvb** [comment]
I really can't seem to recreate this on my end for some reason, I changed some image names to test and they seem to popup for the cards query too.

![qM0TgVUtNE](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/54087190/9a2ea140-41a5-442c-8747-0ef1edf43b15)

Any chance you might have extra snippets turned on or some other plugins that might be doing something weird? 🤔

**Comment by Cammagno** [comment]
> Any chance you might have extra snippets turned on or some other plugins that might be doing something weird? 🤔

Thanks for your help.
I've got it working turning on Restricted mode to disable all the 100+ plugins and then turning it back off.
After restarting Obsidian, it works as expected.
God knows what the problem was.
