### ISSUE TITLE
[Bug] File Explorer formatting is suddenly bad.

### ISSUE THREAD

**Issue by Geohexamon** [SlRvb/Obsidian--ITS-Theme#203]
### Describe the bug
The file explorer looks horrible all of a sudden: https://cdn.discordapp.com/attachments/222103179637030913/1110844113177292932/image.png

**Expected behavior**
This is how it's been looking: https://cdn.discordapp.com/attachments/222103179637030913/1110103737076293642/image.png

### OS
Where does the bug occur?

- [Win10] Desktop

### Versions
- Obsidian Version: 1.3.3
- ITS Theme Version: 0.8.87

I have tried resetting from start to no avail. What's weird is that when I reinstall ITS after deleting the .obsidian folder in my vault, it looks fine for a second, but the moment I do anything with the file explorer it breaks again.

I sent my vault to a friend and it looks the same on their computer too.

The only thing I can think of is that recently I tried an experiment where I tried to keep my vault folder on a google drive to try and distribute it to some friends, but the experiment failed so I reverted my changes. Ever since it has been like this.

**Comment by SlRvb** [comment]
Can you update the ITS Theme to v1.0 and see if it's still a problem there?

**Comment by Geohexamon** [comment]
No, that seems to be fine there!
