### ISSUE TITLE
[Bug] \overline does not work

### ISSUE THREAD

**Issue by Answed** [SlRvb/Obsidian--ITS-Theme#204]
### Describe the bug
The \overline{#} method only works for one char which is not capitalized. As soon as you add more chars or the chars are capitalized the line dissapears

**Expected behavior**
A line above all characters in {} 

### To Reproduce
1. Create a MathJax/LaTex expression with $$ or $$$$
2. Write \overline{a} to see the Line
3. Change \overline{a} to either \overline{A} or \overline{abcsr...} 

### Screenshots
Default Theme:
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/35118203/1b7a9bb6-4ee8-4ea7-b308-70dac0e31556)

ITS Theme:
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/35118203/b0cb28a7-148c-41ae-b6c2-00b6b139019c)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version:  1.3.3
- ITS Theme Version:  0.8.87

**Comment by SlRvb** [comment]
Any chance this occurs on the new ITS v1.0 update?

**Comment by SlRvb** [comment]
That's really weird, I can't seem to recreate it on my end, it shows up the way it should for me: 
![Obsidian_0Xs6q9v50v](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/54087190/54f04c2b-659e-4f0a-91a7-706cb0eb2bb5)

Any chance plugins or snippets might be doing something strange to them?

**Comment by SlRvb** [comment]
Ah it's no worries 💖 

If obsidian later makes issue comes up again, see which plugin might've caused the issue and maybe report that to the plugin dev.
