### ISSUE TITLE
[Bug] Cursor doesn't move with space in Pathfinder alternate theme with Encoded Fonts enabled.

### ISSUE THREAD

**Issue by Z3DT** [SlRvb/Obsidian--ITS-Theme#206]
### Describe the bug
Minor, mostly annoying bug: Enabling the Encoded Fonts snippet and setting the ITS to the Pathfinder theme causes an issue where the cursor does not move when typing a space in a note tile, making it hard to tell that you typed that space in the first place.

**Expected behavior**
Cursor moves when pressing spacebar

### To Reproduce
1. Enable Style Settings and set Theme to ITS theme
2. Install Encoded Fonts and enable
3. In Style Settings, set Alternate Color Scheme to Pathfinder
4. Create a new now
5. See error

### Screenshots
https://www.youtube.com/watch?v=HUQVv-re0_k

### OS
Windows 11

- [X] Desktop
- Possibly also mobile, but I don't use Obsidian on mobile so I haven't tested.

### Versions
- Obsidian Version: 1.3.4
- ITS Theme Version: 1.0.10

**Comment by SlRvb** [comment]
Ah I think the encoding got weird, can you redownload the snippet and see if I've fixed that issue?

**Comment by Z3DT** [comment]
Yup, that's fixed it! Thanks!
