### ISSUE TITLE
[Bug] Broken CSS classes

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#208]
### Describe the bug

A couple of CSS classes that don't seem to be working anymore. Not sure if they were broken or removed with ITS 1.0 or broken by some Obsidian update but they are still listed in the documentation but don't seem to have any effect:

- `readable`
- `writing`
- `poem` (although I'm not sure what it's supposed to look like when working correctly)
- `alt-co` (also doesn't seem to have an effect when placed on a callout directly)
- `hr-tog` (only broken for the pathfinder theme)

### OS
Where does the bug occur?

- [x] Desktop
- [not tested] Mobile

### Versions
- Obsidian Version: Version 1.3.4 (Installer 1.3.3)
- ITS Theme Version: 1.0.10

**Comment by SlRvb** [comment]
All these classes should now be fixed in ITS v1.0.20. Only exception is `alt-co` and I meant to remove that one as that's now just the default callout styling so that should now be removed from the list on the guide.

**Comment by Jnosh** [comment]
`readable`, `poem`, `hr-tog` seem to be working correctly.

For `writing`, headings are centered and text is justified as mentioned in the documentation.
For `auto sets readable line width`, that adjusts the line length when `Readable line length` is enabled, correct? If so, that seems to be working as well.
Also, with the `writing` CSS class applied, some sort of visual indicator is added to links. Not sure if that is expected or a bug:

<img width="245" alt="Screenshot 2023-05-30 at 14 44 53" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3801202/e0472f70-9009-447a-b060-9c3092a39265">

**Comment by SlRvb** [comment]
In ITS v1.0.24 that link issue and the writing's line width should be fixed for when readable is off too

**Comment by Jnosh** [comment]
Perfect, thanks!
