### ISSUE TITLE
[Bug] Center Images style setting doesn't work

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#209]
### Describe the bug

The `Note->Images->Center Images` setting doesn't seem to be working currently.

(The `center` attribute on an individual images still works.)

### OS
Where does the bug occur?

- [x] Desktop
- [not tested] Mobile

### Versions
- Obsidian Version: Version 1.3.4 (Installer 1.3.3)
- ITS Theme Version: 1.0.10

**Comment by SlRvb** [comment]
Can you see if this is now fixed in ITS v1.0.21?

**Comment by Jnosh** [comment]
Thank you, seems to be working as expected now.
