### ISSUE TITLE
[Bug] Hide Header Underline style setting doesn't work for Pathfinder theme

### ISSUE THREAD

**Issue by Jnosh** [SlRvb/Obsidian--ITS-Theme#210]
### Describe the bug

The `Note->Headers->Hide Header Underline` style setting doesn't seem to be working for the Pathfinder theme.

### OS
Where does the bug occur?

- [x] Desktop
- [not tested] Mobile

### Versions
- Obsidian Version: Version 1.3.4 (Installer 1.3.3)
- ITS Theme Version: 1.0.10

**Comment by SlRvb** [comment]
Can you check that this setting is now working as it should in ITS v1.0.20?

**Comment by Jnosh** [comment]
Can confirm that this is working correctly now, thanks!
