### ISSUE TITLE
[Bug] Pathfinder Theme /INI Tracker

### ISSUE THREAD

**Issue by Pete1974** [SlRvb/Obsidian--ITS-Theme#211]
### Describe the bug
The Initiative Value is unreadable with this Template as it is a black font on a brown/dark-red background.

**Expected behavior**
Please change colors

### OS
Win11
MacOS
<img width="379" alt="Bildschirmfoto 2023-05-30 um 15 25 24" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/134707797/2cc8e279-9afe-4421-817d-f10fa4f56f46">

### Versions
- Obsidian Version: 
- ITS Theme Version: Pathfinder

**Comment by SlRvb** [comment]
Can you see if ITS v1.0.22 fixes this issue?

**Comment by Pete1974** [comment]
Yes that solved the Problem, thx!!



Von: SlRvb ***@***.***>
Gesendet: Mittwoch, 31. Mai 2023 18:29
An: SlRvb/Obsidian--ITS-Theme ***@***.***>
Cc: Pete1974 ***@***.***>; Author ***@***.***>
Betreff: Re: [SlRvb/Obsidian--ITS-Theme] [Bug] Pathfinder Theme /INI Tracker (Issue #211)


Can you see if ITS v1.0.22 fixes this issue?

-
