### ISSUE TITLE
[Bug] When hovering over filenames/buttons, text unreadable

### ISSUE THREAD

**Issue by Captain-Ziltoid** [SlRvb/Obsidian--ITS-Theme#214]
### Describe the bug
When hovering over filenames in the sidebar, or over buttons such as 'minimize' or 'close', or over plug-in buttons, the pop-up is unreadable, as well as whatever is being hovered over. 

**Expected behavior**
I expected it to be readable. It used to have a different font.

### To Reproduce
1. Go to vault running the ITS theme/TTRPG colour scheme
2. Hover over filename in sidebar, or buttons within the vault

### Screenshots
<img width="328" alt="Screenshot 2023-06-16 211807" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/136809871/8e3a100c-78f8-4696-b1a8-7d1bd21f47e8">

### OS
Windows 11 OS

- [X ] Desktop

### Versions
- Obsidian Version: 1.3.5.
- ITS Theme Version: 1.0.37

### Additional context
Not sure if its just a font colour issue, or something else. I'm sure it didn't used to be like this. Can't figure out which font parameter changes it though.

**Comment by SlRvb** [comment]
What plugin is that in the screenshot?

**Comment by Captain-Ziltoid** [comment]
> What plugin is that in the screenshot?

No plugin in the screenshot. Its just me hovering over one of my files, using the ITS theme with the TTRPG colour scheme in Light mode.

**Comment by SlRvb** [comment]
Do you have snippets? If you have the Alt Themes snippet you need to disable and delete that

**Comment by SlRvb** [comment]
With no way to recreate this, I can't figure out what's going wrong to fix it. If it's still an issue and you can recreate this in the Sandbox Vault, do feel free to reopen this issue.
