### ISSUE TITLE
[Bug] Bold & Italics color is gone

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#215]
### Describe the bug
I get very used to using Bold and Italics in different colors. The bold & italics text color cannot be rendered anymore. 

**Expected behavior**
A bold & italics text should be rendered in color edited in Style Setting.

### To Reproduce
1.  In Style Setting, go to Colors > Text > Faint Text (italics color)
2. Adjust to any color
3. See error: Color cannot be rendered

### Screenshots

- **Style Setting**
![2023-06-16_17 48 41_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/80742e7f-e3a3-47a4-8ead-41d326c9fdae)

- **Color cannot be rendered**
![2023-06-16_17 51 44_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/12b49603-6dc7-4bcb-acc8-ad2c5875dc20)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.5
- ITS Theme Version: 1.0.37

**Comment by SlRvb** [comment]
🤔 Hmm `Faint Text` isn't the color for the italics. If you search for italic and bold in the style settings the actual color settings for those should show up.

**Comment by SlRvb** [comment]
With those selected and changing the text to blue, it seems to work on my end 🤔
![Obsidian_igj82rWRnK](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/54087190/4b6ee510-9728-48ec-91c3-387d851c3b91)

**Comment by Missionary2112** [comment]
Oh yeah I just found it. Thank you for the image. I thought going to Color section to change color, not in Note > Text > Advanced Text Decoration. A little tricky there 😅
