### ISSUE TITLE
[FR] Illusion Theme Inspired Headers - Set per header

### ISSUE THREAD

**Issue by ProStashio** [SlRvb/Obsidian--ITS-Theme#216]
### Is your feature request related to a problem? Please describe.
I love the Illusion Theme Inspired headers, I would love to use them just to break up new main sections with main headers rather than every header.

### Describe the solution you'd like
Instead of having a toggle for all headers, a toggle for each header.

### Describe alternatives you've considered
None

**Comment by SlRvb** [comment]
I've added the option to ITS v 1.0.45 to toggle certain headings in the Style Settings if you search for `Illusion Heading` they should pop up

**Comment by ProStashio** [comment]
> I've added the option to ITS v1.0.45 to toggle certain headings in the Style Settings if you search for `Illusion Heading` they should pop up

works like a charm, many thanks!

**Comment by ProStashio** [comment]
Not sure if it's intended, but the old overall toggle is still there

**Comment by SlRvb** [comment]
Yeah that's intended, if you only want it for specific headings, you need to toggle that off and switch to the specific toggles
