### ISSUE TITLE
[FR] Change icon color

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#217]
### Feature Request
I would like to change icon color but couldn't do it in Style Setting.

![2023-06-19_17 43 58_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/e0930595-878c-493f-9c41-da39c3679e8f)
As you can see, if the icon color is dark it would be nice.

### Describe the solution you'd like
Change icon color in Style Setting

### Describe alternatives you've considered
I can change button color (Style Setting > ITS Theme Setting > Color > Workspace > UI Element > Button) to darker but it would cause color scheme conflict in my setting.

**Comment by SlRvb** [comment]
I've added the option to change it in the style settings under `Colors > Workspace > UI Elements > Sidebar Active Icon Color`

**Comment by Missionary2112** [comment]
One thing to notice is that when I click on the icon, it still display default color not the "Sidebar Active Icon Color" until the focus is changed to elsewhere.
https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/b6d42900-8816-48d5-a9cd-b1c989413adc

**Comment by SlRvb** [comment]
1.0.67 should fix that now :)
