### ISSUE TITLE
[Bug]  Checkbox ui presentation problem on ‘Dropped’ customer task status

### ISSUE THREAD

**Issue by aruid** [SlRvb/Obsidian--ITS-Theme#218]
### Describe the bug
When i use the last version ‘9686d50376a1b1afff2be3724c08dea4aa595ab3’ which is  commits on May 24, 2023,  'Snippets/S - Checkboxes.css' on my Obsidian's checkbox style setting, there is a problem i had

Markdown text ↓
```
- [ ] Unchecked
- [x] Regular
- [X] Checked
- [-] Dropped
```
1. The 'Dropped' status is missing the Checkbox Strikethrough，as the picture below
<img width="1208" alt="image" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3890964/9a07a6d2-dbb2-4293-ae79-a5f989f18159">
And i had set the ‘Style Settings’  →‘Checkbox Strike Specific’ as the picture blew
<img width="1167" alt="image" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3890964/2eb1551b-934b-4f85-a212-b61df7792444">

So，i try the the earlier version ‘c03d7c5fcd64fabd4fc30b27fa49546e51acb216’ which is commits on May 19, 2023，and the ‘Dropped’ status strikethrough recover, as the picture blew
<img width="1220" alt="image" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3890964/1ab85907-e266-4e25-b8bc-88e49f5d5d4f">

2.  The 'Unchecked' status UI not work too，because i sawed the ‘unchecked’ status ui should be as the picture below，btw the picture is from ：https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/CSS+Snippets/Alternate+Checkboxes+(SlRvb)
<img width="819" alt="image" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/3890964/f4d09752-1777-47fe-a096-6839e35927ad">

**Comment by SlRvb** [comment]
I think both of these should be fixed now in the checkbox snippet, thanks for letting me know about this!
