### ISSUE TITLE
More style sheet controls for paragraph, header, and list spacing

### ISSUE THREAD

**Issue by SlRvb** [SlRvb/Obsidian--ITS-Theme#223]
### Discussed in https://github.com/SlRvb/Obsidian--ITS-Theme/discussions/222

<div type='discussions-op-text'>

<sup>Originally posted by **Taliesin1** July  3, 2023</sup>
I was wondering if it would be possible to get more control over the paragraph spacing on headers and lists.</div>

**Comment by SlRvb** [comment]
@Taliesin1 A coming update will allow for better control over that, so once that gets pushed to the public, I'll have the options to adjust that within the style settings 👌🏽

**Comment by Taliesin1** [comment]
Awesome! Thanks!

**Comment by SlRvb** [comment]
ITS v1.1.12 should now have these options if you search for `spacing` which should bring up all the sliders to adjust spacing :)
