### ISSUE TITLE
[Bug] Blockquote doesn't work properly

### ISSUE THREAD

**Issue by AusVox** [SlRvb/Obsidian--ITS-Theme#224]
### Describe the bug
No quotation mark on a > blockquote and the ==\*\*Author\**== text formatting doesn't work properly.

**Expected behavior**
Blockquote with quotation mark and special author field formatting

### To Reproduce
1. Create blockquote as in the screenshot
2. Add special formatting
3. See error

### Screenshots
![изображение_2023-07-16_082844351](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/62338420/a0638c55-d19f-4bad-9b86-b7a4d1cc9ac0)
![изображение_2023-07-16_082857899](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/62338420/d8169b53-ad99-431a-a9f5-253c0e138a57)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.5
- ITS Theme Version: 1.0.67

### Additional info
Tried disabling all snippets and plugins and reinstalling theme. Didn't help

**Comment by SlRvb** [comment]
I've removed that functionality from the ITS v1 update, but if you update to v1.0.70+ I have a `> [!Quote]` callout that should get you the same functionality:
https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callouts/Callout+-+Quote
