### ISSUE TITLE
[Bug] hiding the status bar

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#225]
### Describe the bug

There is a problem with hiding the status bar, it is normal when there are no other plugins,

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/6e6b40d9-4039-4f2a-8d3a-7836be69341f)

But as soon as there are more plugins, it will become

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/66783a93-0a18-4870-8a96-c05378a4ddf4)

**Expected behavior**

Install multiple plugins that will appear in the status bar, such as obsidian git, workspace plus

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version: latest

**Comment by SlRvb** [comment]
I can't seem to recreate this, by default the status bar looks correct and even with those plugins installed, they don't cause the status bar to end up like that 🤔

**Comment by SlRvb** [comment]
Ah wait, I see the issues you mean with the hide status bar toggle, will fix

**Comment by SlRvb** [comment]
In ITS v1.0.77 this should be fixed now 🤔

**Comment by Borber** [comment]
> In ITS v1.0.77 this should be fixed now 🤔

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/4ba5182a-7b9f-47d4-9941-a3cf849707fe)

In fact, there are still some problems. I wrote a css myself. Do you think it can be used?

```css
.status-bar:not(:hover) {
    width: 50px;
    height: 30px;
    display: block;
    opacity: 0;
}
```

![ob](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/30563826/ed114b3a-b675-469d-9267-351be4258146)

**Comment by SlRvb** [comment]
Oh I see why, various complements overrides my stuff still. Guess I will have to force  it.

**Comment by SlRvb** [comment]
Okay, ITS v1.0.78 should actually fix that now
