### ISSUE TITLE
[Bug]: Aside Callout toggle is partially covered

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#226]
### Describe the bug
Aside Callout when toggle off to minimize the content, the icon to toggle back on is partially covered. 

**Expected behavior**
Aside Callout toggle should not be covered by main text

### To Reproduce
1. Create Aside Callout with `-` to hide it
2. See error: Aside Callout toggle is partially covered

### Screenshots
- This is working as expected
![2023-07-21_16 08 18_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/e8e61875-3e2e-4981-abdd-bef986956577)

- The Aside Callout toggle is partially covered
![2023-07-21_16 06 57_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/848890de-59a1-438a-a914-5798379f37da)

- When Aside Callout is opened, it looks as expected
![2023-07-21_16 07 10_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/2de8944f-0241-47ef-b165-d5eeb6798b05)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version: 1.0.78

**Comment by SlRvb** [comment]
Wait do you have extra css attached to your callouts? If you remove that is it fixed?

**Comment by Missionary2112** [comment]
I tried turning off each css snippets but nothing changes

**Comment by SlRvb** [comment]
Oh the Original Callout styling is the issue, will fix.

**Comment by SlRvb** [comment]
ITS v1.0.82 should now fix this

**Comment by Missionary2112** [comment]
Sorry, I just realized one thing. 
![2023-07-23_20 50 13_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/8ead6415-6712-44c9-adf8-08a6b5162a95)
When the Aside Callout positioned next to the list, the callout will be blocked. 
Can you adjust to toggle the list when I click on the number / bullet ? That way it will not overlap over Aside Callout.

**Comment by SlRvb** [comment]
ITS v1.0.85 should move the arrows closer to help with that 🤔

**Comment by Missionary2112** [comment]
Wow, it's much better. Thank you.
