### ISSUE TITLE
[Bug]: ITS Callout Quote is mandatory

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#227]
### Describe the bug
I would like to have an option to change between ITS Callout Quote & default Callout Quote

### Suggested Solution
By using the first capital letter of "quote", I can define which type of Callout Quote it's gonna be. 

E.g.
- `>[!quote]` = Default Callout Quote
- `>[!Quote]` = ITS Callout Quote

### Screenshots
- **Default Callout Quote**
![2023-07-21_18 22 47_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/6d74c750-b11e-47f6-bceb-5194c84df136)

- **ITS Callout Quote**
![2023-07-21_18 27 07_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/6084f632-2224-4b06-a3a1-0d2f0fc3c20d)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version: 1.0.78

**Comment by SlRvb** [comment]
I've added the option in the style settings to disable the quote styling if you don't want it as default where the adjustments to restyle it can be manually reapplied. 

Callouts unfortunately don't really have any way to do capital or lowercase versions as far as I'm aware 🤔 so this might be the way I'll have to go about it

**Comment by Missionary2112** [comment]
Thank you, that works for me.
