### ISSUE TITLE
[Bug]: Tag List renders nothing & is looped

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#229]
### Describe the bug
A tag list renders only the first half and the other half just cannot show up. And when scrolled down the bottom, it looped back up.

**Expected behavior**
It should work as expected in default theme

### To Reproduce
1. Go to Tag section
2. Select a tag with huge amount (e.g. more than 200 tags)
3. Scroll down and see error

### Screenshots
https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/21120da0-6b63-43aa-815a-3756c0308a16

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version: 1.0.78

**Comment by SlRvb** [comment]
I think I fixed this in ITS v1.0.80, do let me know if it worked.
