### ISSUE TITLE
How to change the background color of embeds

### ISSUE THREAD

**Issue by zcysxy** [SlRvb/Obsidian--ITS-Theme#23]
Hi! Seems like I cannot change the background color of embeds in ITS like I can in other themes, I skimmed through the code and didn't figure out why. Are there any special classes assigned to embeds?

**Comment by SlRvb** [comment]
The current style of embeds uses the note's color, but if you toggle `Original Embeds` on and change the color of `Embed/Blockquote`, I think that should do what you want.

**Comment by zcysxy** [comment]
Yeah I succeed with Original Embeds turned on! However I was trying to change the color in a certain note using cssclass frontmatter. Is it possible without turning on Original Embeds globally?

**Comment by SlRvb** [comment]
Ooh, if you want to use a cssclass, this should do it:
```css
.embed .markdown-embed {
    background-color: #1c2535;
}
```

**Comment by zcysxy** [comment]
Sorry but selector `.embed .markdown-embed` doesn't work for me. I finally succeeded with selector `.markdown-preview-view .markdown-embed, .internal-embed` 🍻 .

FYI I achieved some kind of glass effect by tweaking embed background color 😆

![image](https://user-images.githubusercontent.com/48207708/132293604-d780d02c-30ba-437a-8994-39936e4beac3.png)
