### ISSUE TITLE
[FR]:  Size format should be similar to default theme

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#231]
### Is your feature request related to a problem? Please describe.
I created a lot of Canvas image content when I used the default / AnuPpuccin theme. When I switch to ITS theme, the image resized bigger than usual. Plus, other things getting bigger too, including the dataview table I mentioned before in a bug report. 

### Describe the solution you'd like
Resize ITS format similar to default theme. Because I find AnuPpuccin theme is pretty much the same format as default theme. That way, I can switch between themes without getting disrupted in size format.

### Screenshots
- AnuPpuccin theme
![2023-07-26_17 05 23_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/3a4c64d9-6cf1-408f-ba84-21eb65cc6e3e)

- ITS theme
![2023-07-26_17 05 34_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/5cfddfeb-40b4-4a36-9790-bebcbc791def)

As you can see, the Wheel of Fortune (embedded image from a weblink) is resized to fit in a Canvas card in AnuPpuccin / default theme. But when switched to ITS theme, the image is enlarged out of portion. 

Thank you for reading my request.

**Comment by SlRvb** [comment]
Ah, can you see if ITS v1.0.84 fixes that?

**Comment by Missionary2112** [comment]
Yes, that looks nice! Thank you so much 🥳
