### ISSUE TITLE
[Bug] S - Checkboxes.css - Regular is unchecked but highlighted

### ISSUE THREAD

**Issue by technotherion** [SlRvb/Obsidian--ITS-Theme#233]
### Describe the bug
Using the Tasks plugin
This is with Minimal Settings plugin disabled and pretty much all of my settings at default -- except that my checkboxes are squares instead of circles as specified by Minimal. 

"Regular" checkbox is showing as a transparent but highlighted unchecked checkbox with S - Checkboxes.css enabled.
I have Style Settings installed and none of the options here appear to affect these. 

Here is the style with Minimal enabled, S - Checkboxes disabled
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/13829537/3f4aee72-4a6e-46dc-9744-138802315396)

Here's the style with Minimal enabled, S - Checkboxes enabled
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/13829537/f84758da-e671-44f8-9184-cc346922f0f8)

**Expected behavior**

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/13829537/d00ff17e-bced-4fb9-adb6-77b2fb5c519d)

Was expecting it to look a bit more like the documentation. 

### To Reproduce
1. downloaded css snippet https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Checkboxes.css
2. Went to Obsidian > Appearance > CSS snippets and added snippet
3. Enabled snippet
4. Went to Tasks, down to Custom Statuses, reset all custom statuses, added ITS theme and SIRvb checkboxes
5. Copied this snippet for the checkboxes and embedded it in a new note https://publish.obsidian.md/slrvb-docs/ITS+Theme/Alternate+Checkboxes#Checkbox+Types

### OS
Win 10 
Where does the bug occur?

- [x] Desktop
- [ ] Mobile (untested)

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version: N/A

I apologize if this is a bit nitpicky but those checked boxes are a little difficult to see at the moment.

**Comment by SlRvb** [comment]
Could you update the snippet again? I think I've fixed the issue, thanks for letting me know!

**Comment by technotherion** [comment]
All fixed. 
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/13829537/543b4536-4411-46a2-a536-f294d957b1b1)
And here's with Minimal's square checkboxes, too:
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/13829537/efc7d471-7edc-444d-9bc1-b91ed2260465)
