### ISSUE TITLE
[Bug] Huge Margins on New Window

### ISSUE THREAD

**Issue by AKasera** [SlRvb/Obsidian--ITS-Theme#234]
### Describe the bug
Files opened in new tab have horrific margins to the point that the file is in the center with 3 to 4 inch margins on either side just wasting space

**Expected behavior**
Minimal if not very little margins just like when It's depicted on the main window

### To Reproduce
1. Open a file in a new window

### Screenshots
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/15956410/d6fd8f06-6561-4d32-9b27-db34827300f5)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/15956410/c18bada8-57a0-4a7c-b5e6-1d38fd0517fd)

### OS
Where does the bug occur?

- [ X] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version:

**Comment by SlRvb** [comment]
uh, is that with readable line length turned off?

**Comment by AKasera** [comment]
Yes

**Comment by SlRvb** [comment]
ITS v1.0.90 should fix that now 🤔

**Comment by SlRvb** [comment]
If this isn't fixed, do feel free to reopen this issue.
