### ISSUE TITLE
[Bug] Default Bullet Disc Shape not rendered in Dataview table

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#238]
### Describe the bug
Default Bullet Disc Shape not rendered in Dataview table

**Expected behavior**
The bullet shape should be rendered in Dataview table

### To Reproduce
1. Go to Style Setting > Note > Lists > enable `Default Bullet Disc Shape`

### Screenshots
- **Backmatters**
![2023-08-09_16 46 04_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/64e3ae84-9b34-4818-9d5b-016f65189178)

- **ITS theme**
![2023-08-09_16 45 27_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/a211549a-eb1f-4fd7-9810-024665a9a825)

- **Default theme**
![2023-08-09_16 45 52_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/b9a9a3e2-63c4-4ab3-bfe7-0a601544f016)

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

### Versions
- Obsidian Version: 1.4.2
- ITS Theme Version: 1.0.87

### Additional context
If I disable `Default Bullet Disc Shape`, it works fine with customized bullet shape.

**Comment by SlRvb** [comment]
This should be fixed now in ITS v1.1.07 :)
