### ISSUE TITLE
Alternate theme and color changes

### ISSUE THREAD

**Issue by thatguy14** [SlRvb/Obsidian--ITS-Theme#24]
Hello - I am trying to use your ITS theme - I really like it. I am having 2 issues however:

1. Whenever I open the settings menu, everything but the settings menu changes to a lighter blue color ( see screenshots)
2. I placed the alternate theme CSS snippet into the snippets folder and toggled it on. However, when I go to style settings and press the toggle on one of them - it does nothing. Am I doing something incorrectly?

Thanks!

![ITS_nosetting](https://user-images.githubusercontent.com/25937625/132356516-eaf973bc-524d-42ad-950d-8b73dc0ded55.png)
![its_withsettings](https://user-images.githubusercontent.com/25937625/132356539-69ff313e-eb5b-45d4-9806-a59fa11ff389.png)

**Comment by Borber** [comment]
1. I think this is a deliberate design by the author
2. Can you take a screenshot of your style setting?By the way, you should download Theme - All Alternate Themes.css and select a theme in the settings, for example the DnD theme snippet works fine for me
![image](https://user-images.githubusercontent.com/30563826/132374008-547015a8-87dc-429c-81d5-5cc5bd69bc64.png)

**Comment by SlRvb** [comment]
1. Borber is correct, that's the color set whenever opening settings
2. I'm not sure what would be the reason the Alternate Themes snippet wouldn't work, perhaps either a picture or gif of the issue may help narrow down the potential cause.

**Comment by thatguy14** [comment]
Thanks for the replies

1. Is there an easy way for it to not do this?  I'd prefer to stay with the dark-style rather than it shifting colors but not a big deal
2. I individually installed the CSS snippets and that is working. I put the raw output from [the all themes css link](https://raw.githubusercontent.com/SlRvb/Obsidian--ITS-Theme/main/Theme%20-%20All%20Alternate%20Themes.css) and when I press the toggle in Styles Plugin nothing happens. Hopefully the screenshots below are helpful. 

![image](https://user-images.githubusercontent.com/25937625/132387914-dc69e681-7fcc-417b-84a5-49f6039a8e76.png)
![image](https://user-images.githubusercontent.com/25937625/132387955-a1df05c9-ecc2-4965-8ff9-214d6ebb1247.png)
![image](https://user-images.githubusercontent.com/25937625/132388044-620a33ab-6001-457f-8b2e-e0065ee77026.png)

**Comment by SlRvb** [comment]
1. Yeah you can change that by changing the color of **Search 2** in the `Other Colors > Hightlights` section

---
2. I'm not sure why that's not working, could you open the Dev Console `ctrl + shift + i` and see if the selected alternate theme shows up?
![PGJLvJag4P](https://user-images.githubusercontent.com/54087190/132423472-25de5d43-fad7-4f9e-aede-180dcd63d0e6.png)

And could you put your snippet file here? I'm not sure if anything strange is going on in the file or not to cause this.

**Comment by thatguy14** [comment]
1. Thank you, for anyone else, I changed what SIRvb said above to alpha = 0 and that did it.
2. I have attached a screenshot of the console log with the settings as per my above screenshot and have attached the snippet that I copied and pasted. I converted it to a text file as git wouldn't let me upload a CSS here

![image](https://user-images.githubusercontent.com/25937625/132515842-16db1a85-9153-4ebd-b017-ffe36d50ab11.png)
[ITS_allthemes.txt](https://github.com/SlRvb/Obsidian--ITS-Theme/files/7129073/ITS_allthemes.txt)

**Comment by SlRvb** [comment]
Seems like your CSS file got cut off 🤔. This should be the whole file: [ITS_allthemes.txt](https://github.com/SlRvb/Obsidian--ITS-Theme/files/7129587/ITS_allthemes.txt)

I guess just change the `txt` extension to `css` and I believe it should work.

**Comment by thatguy14** [comment]
That did it! I am not sure how I screwed that up - I tried twice to make sure (just copy pasted the raw text from the link given in the readme). Anyways, thanks for your help, this is my favorite theme set!
