### ISSUE TITLE
[Bug] Documentation for Alternate Color Schemes Links to Dead File

### ISSUE THREAD

**Issue by Rvby1** [SlRvb/Obsidian--ITS-Theme#241]
### Describe the bug
In the documentation for ITS Theme, the page for Alternate Color Schemes links to a file that is meant to include all the themes in file, named Theme - All Alternate Themes.css. This file seems to have been deleted or moved at some point.

You can find the page here: https://publish.obsidian.md/slrvb-docs/ITS+Theme/Alternate+Color+Schemes
And the linked file here: https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Theme%20-%20All%20Alternate%20Themes.css

**Expected behavior**
Ideally, there would be a link to the spreadsheet. Or, if this file is no longer supported, and the stand-alone theme files should be used, that should be noted.

**Comment by SlRvb** [comment]
I've updated the docs, thanks for mentioning this I should've updated that section 🤔
