### ISSUE TITLE
[Bug] numbers in numbered list invisible in edit mode 

### ISSUE THREAD

**Issue by Rondesgr** [SlRvb/Obsidian--ITS-Theme#242]
### Describe the bug
When creating a numbered list, the numbers are invisible in edit mode.  However, in read mode, they show up.

**Expected behavior**
Type "1. " and then 1st item in list
press [enter] and have "2. " show up on next line, enter more text, press [enter], have "3. " show

### To Reproduce
1. Type 1. and [space]
2. type text
3. press [enter]
4. "1." disappears. No text "2. " shows.
5. type text for number 2.
6. press [enter]
7. nothing shows as "3. "
8. click "editing" icon to switch to "read" mode
9. numbers of numbered list appear

### Screenshots
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/5704149/cef37ca6-7249-420e-8b56-4c0df858c867)
---------
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/5704149/c0cc9d16-bf47-4e5e-81b6-11e764def851)

### OS
Windows 10 Pro
- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.3.7
- ITS Theme Version: 1.1.12

**Comment by SlRvb** [comment]
Can you update to ITS v 1.1.15? I think this should be fixed now 🤔

**Comment by Rondesgr** [comment]
Perfect! Thank you so much!
