### ISSUE TITLE
[Bug] Bullet points in column list not showing correctly when changing to reading mode.

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#244]
The bullet points are not rendered correctly when I change to reading mode.
![bug](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/7eb5ac50-ae26-4e30-9061-3191f6db823e)
I'm using obsidian 1.4.6 and the AnuPpuccin theme.
Thanks

**Comment by albertoloscerritos** [comment]
It also happens when using the Sandbox Vault. Obsidian v 1.4.12

![its_bug_2](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/cfcad960-9647-4b97-b507-9f6408c9a618)

**Comment by SlRvb** [comment]
I think I've pushed a fix to the callouts, could you download the snippet again and see if that worked?

**Comment by albertoloscerritos** [comment]
It seems to be working perfectly. Thanks.
