### ISSUE TITLE
[Bug] Callout not showing titles correctly when using minimal theme.

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#246]
When using minimal theme and having the outlined callouts selected, the ITS callouts won't render the title (and the icon) correctly, they are cropped.

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/ccf8088e-0ab2-474b-a265-f64b1236bfea)

I'm using obsidian 1.4.12

**Comment by SlRvb** [comment]
I think the new updates to the callout should fix this, do let me know if it worked!
