### ISSUE TITLE
[Bug] (Image Positioning Snippet) Bulletpoints overlap with left-aligned images

### ISSUE THREAD

**Issue by phthallo** [SlRvb/Obsidian--ITS-Theme#248]
### Describe the bug
When using your Image Positioning Snippet, aligning an image using `![[image.png|left]` and then creating a bulleted list (so bullet points positioned to the right of the image) cause the bullet points to overlap with the image. 
Additionally, list indentation to the right of the image is not preserved.

**Expected behavior**
Bullet points should be fully visible, and correctly aligned with a suitable margin instead of overlapping.

### To Reproduce
1. In Source Mode, paste any image in and resize with the `left` attribute, with [this CSS snippet](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Images%20Adjustments.css) enabled.
2. Begin typing a list of arbitrary length, with varying bullet indents. 
3. Switch to Reader Mode.
4. See screenshot below.

### Screenshots
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/84078890/63068038-d18f-41d6-9227-d8e27684f8db)
^ The above image is in Reader Mode with all sidebars collapsed.
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/84078890/9b2f74a6-d375-41d6-8795-2364978f1734)
^ The above image is what I'm typing in (in Source Mode). I usually only switch between Source and Reader mode. 

(In the screenshots, I am using the AnuPpuccin theme with a couple of other plugins, but I tested it on an empty vault and it still doesn't work correctly.) 
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/84078890/84781f87-81fc-4e4d-8c92-e602d8151b12)
^ Image above is the empty vault trial. This one isn't using any resizing, just `left`.

### OS
Windows 10 

Where does the bug occur?

- [X] Desktop
- [ ] Mobile (untested)

### Versions
- Obsidian Version: v1.4.16
- ITS Theme Version: N/A

### Additional context
// Thank you!

**Comment by SlRvb** [comment]
This should now be fixed if you redownload the snippet! Thanks for letting me know and sorry it took so long to get to 🙈

**Comment by phthallo** [comment]
Thank you so much and no worries about the wait! It is fixed, but another problem's come up :'D 
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/84078890/37c2f98a-4180-4dee-8120-544937abec8d)
Fixing the issues with how lists are displayed appears to have broken how they wrap around the image (normal text is perfectly fine though!). 

I definitely understand if this is something you can't fix though/isn't high priority, as this is probably a niche use for it. Again, thanks for making and maintaining this snippet (and the ITS theme itself!)

**Comment by SlRvb** [comment]
Hmmm yeah unfortunately I don't know of a way that this could be fixed 🤔 any other methods that push the bullets away from overlapping also results in this effect. Sorry about that, you can disable it in the style settings if it's too much of an issue.

**Comment by phthallo** [comment]
That's okay, thanks anyways :) Have a nice day!
