### ISSUE TITLE
[Bug] Roundness option in style settings plugin not working properly

### ISSUE THREAD

**Issue by TreePage** [SlRvb/Obsidian--ITS-Theme#250]
### Describe the bug
When adjusting 'roundness' option from the style settings plugin, the set value will revert back to default once I close the app and restart it. Also, the roundness-slider becomes unresponsive.

**Expected behavior**
To set a desired value in the roundness-setting and it staying that way unless I change it.

### To Reproduce
1. Go to 'Obsidian settings' and click on 'Style settings'
2. Open 'Workspace' and set a value higher than 0 for 'roundness' option
3. Save and close the program
4. Restart the app and repeat the steps above. 'Roundness' is now back to value 0 and unresponsive.

### OS

Windows 10

Where does the bug occur?

- [x ] Desktop

### Versions
- Obsidian Version: v.1.4.16
- ITS Theme Version: 1.1.33

**Comment by SlRvb** [comment]
I can't quite seem to recreate this behavior. Does this occur still if you disable all plugins but Style Settings?

**Comment by TreePage** [comment]
> I can't quite seem to recreate this behavior. Does this occur still if you disable all plugins but Style Settings?
> 
> It seems like this might be some kind of sync issue of some sort.

The issue seems to have gone by itself now.
