### ISSUE TITLE
Some style controls seem to not work

### ISSUE THREAD

**Issue by Taliesin1** [SlRvb/Obsidian--ITS-Theme#251]
### Describe the bug
I set up a test Style Sheet note to test all the different controls for the different styles so I could learn what each of them do. Try as I might, I can't render any changes in this Style Sheet note — or any other note — on these controls:

Note>Text > Paragraph Spacing
Note>Headers > Header Spacing
Note>Lists/Bullet Adj>List Line Width
Note>Lists/Bullet Adj>Original Bullet Lines

**Expected behavior**
I would expect these controls to render visible changes to text with the applied style.

### OS
Where does the bug occur?

- [x] Desktop: MacOS 14.0
- [ ] Mobile

### Versions
- Obsidian Version: 1.4.16
- ITS Theme Version: The latest one — can't find a number

**Comment by SlRvb** [comment]
🤔 Hmm

Paragraph & Heading spacing work for me as well as Original Bullet Lines toggle, make sure you're in reading mode to see those changes though since they only really apply there.

List Line width slider also works but this one should work on either live preview or reading mode.

**Comment by Taliesin1** [comment]
Ah, my bad — I musta been in live preview mode, because I switch to Reading mode now and I see that everything I listed before is working after all — with the exception of the List Line Width, which still apparently does nothing in either mode. Perhaps I don't understand what it's supposed to do? I expect the actual line width to get shorter, so that they're "indented" from the right and shorter than the body text line width. But when I turn that slider, the width of the list line doesn't change at all.

One other question — is there any chance we could get controls to alter the amount of space that _follows_ a header? As it is now, the header floats midway between the paragraph that precedes it and the paragraph that follows it. 

Headlines should always be closer to the paragraph below than the one above. Is there a way I can override this in the css? Not sure how the css I might write would be overridden by either the native styles or the ITS theme styles.

Thanks so much. This is an awesome theme!

**Comment by SlRvb** [comment]
Oooh, no the Line width it means there is the line for when a list has subbullets not the width of a bullet line 🤔 maybe I should call it something like `list indentation width` instead to clear that up?

If you open that request for header stuff as another issue so it's easier for me to track, I'll try to add it sometime soon :)

**Comment by Taliesin1** [comment]
Ah, okay. I would suggest list indention _weight,_ which is typically how designers think of the thickness of a line or rule. If there are other parameters that also deal with the thickness of the line, I'd change this to weight as well, for consistency.

I will enter another GitHub issue for my other request, sure thing. Thanks!
