### ISSUE TITLE
[Bug] "S - Checkboxes.css" snippet doesn't work

### ISSUE THREAD

**Issue by WhiteSp1rit** [SlRvb/Obsidian--ITS-Theme#252]
### Describe the bug
The "S - Checkboxes.css" snippet doesn't work. Does nothing.

**Expected behavior**
It should add custom checkboxes.

### To Reproduce

1) Install Tasks plugin and enable it
2) Put "S - Checkboxes.css" into the snippets folder
3) In Appearance menu, enable the snippet
4) In Tasks plugin menu, add entries for custom checkboxes in Custom Statuses section
5) Restart Obsidian
6) Observe as none of the custom checkboxes display properly, they all show the default checked checkbox instead just as before

### OS
Win 10 Pro

### Versions
- Obsidian Version: 1.4.16
- Snippet version is not mentioned anywhere, downloaded from here: 
https://github.com/SlRvb/Obsidian--ITS-Theme/tree/b87c80c8caebb0d86824ff3b46e60c76f482140a/Snippets

### Additional context
The theme itself works fine, only the snippet by itself doesn't work.
Also, if I understand correctly, Style Settings plugin should show settings for the snippet. It doesn't show anything.

**Comment by WhiteSp1rit** [comment]
Managed to "fix" this - when you try to download a file, instead of downloading it, GitHub gives you the file with code of its own page, instead of the actual file.......... Using "Download raw file" button downloaded the correct one

**Comment by SlRvb** [comment]
So the snippet works now?
