### ISSUE TITLE
[FR] Collapsible Infobox Sections

### ISSUE THREAD

**Issue by ProStashio** [SlRvb/Obsidian--ITS-Theme#253]
### Is your feature request related to a problem? Please describe.
Depending on the note, the infobox can become quite large. I know you can collapse the whole Infobox, but it would be nice to be able to hide sections whilst revealing others.

### Describe the solution you'd like
Within the infobox, there should be a way to add a collapse function like titles, so anything under it can be collapsed until the next 'title' of the same level.

### Describe alternatives you've considered
Collapsing the whole info box

**Comment by SlRvb** [comment]
You can add another sub callout to collapse stuff inside it:

```
> [!infobox] 
> # Infobox in an Infobox
> > [!infobox]- Heading Test
> > hidden info
```

Though I guess I could make that subcallout style look a little more like regular infobox heading styling 🤔

**Comment by SlRvb** [comment]
Gotcha yeah, I'll get to fixing that styling to fit better 👍

**Comment by SlRvb** [comment]
I've changed the sub infobox header styling to match regular headers in v1.1.43 🤔 let me know if this is close or not
