### ISSUE TITLE
[Bug] Infobox Left and Header Overlap

### ISSUE THREAD

**Issue by ProStashio** [SlRvb/Obsidian--ITS-Theme#255]
### Describe the bug
Headers and Infobox Left collapse buttons overlap and cause issues with each other

**Expected behavior**
Them not to overlap

### To Reproduce
1. Make Infobox left
2. Make Header
3. Try collapse

### Screenshots
https://gyazo.com/937c69a109074ff17854842a162e6701

https://gyazo.com/b0f447f3296dd82adabfb1c261507697

### OS
Windows Desptop

### Versions
- Obsidian Version: 1.4.16
- ITS Theme Version: 1.1.34

**Comment by SlRvb** [comment]
I think this should be fixed in v1.1.43 🤔

**Comment by ProStashio** [comment]
Still having that issue

**Comment by scarfur** [comment]
**Same here with [!infobox|right]**. I am on Minimal Theme with the ITS snippet. Headers and plain text works as expected but as soon as there is a markdown table (using the advanced tables plugin but it occurs when I turn off that plugin too) involved, the content gets pushed down and starts where the infobox ends.
Having this issue for a long time, and I think that never worked. As far as I remember, this happened with ITS theme without additional plugins and CSS snippets too.

**Comment by SlRvb** [comment]
I think I've mildly fixed it in ITS v1.2.79. Just made sure the arrow shows over the callout so it's actually clickable, since any other fancy fixes would make regular headers a nightmare to engage with. Hope this is a fine enough fix 😬

**Comment by SlRvb** [comment]
If my fix didn't fix this to your liking feel free to reopen this issue.
