### ISSUE TITLE
[FR]  Picture with caption

### ISSUE THREAD

**Issue by Leiyi548** [SlRvb/Obsidian--ITS-Theme#256]
### Is your feature request related to a problem? Please describe.
I need to show the title of my picture to be able to quickly know the meaning of the picture and more information

### Describe the solution you'd like
add image title style like [[img file#inl|title]]

### Describe alternatives you've considered
I think more people need it

### Additional context
Blue Typoze:
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/76139422/f7e1b2e5-c5c1-4458-b1f4-faef6c469f4f)

**Comment by SlRvb** [comment]
My version is with callouts for more functionality: https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callouts/Callout+-+Captions

**Comment by Leiyi548** [comment]
> My version is with callouts for more functionality: https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callouts/Callout+-+Captions

It's too complicated, and a lot of times you have to type more code.

**Comment by SlRvb** [comment]
Alright, I've re-added my old image adjustment captions in ITS v1.1.37 & the snippet. If you use `#cap` in your image, you should get the same functionality.

**Comment by Leiyi548** [comment]
> Alright, I've re-added my old image adjustment captions in ITS v1.1.37 & the snippet. If you use `#cap` in your image, you should get the same functionality.

Awesome,good work
