### ISSUE TITLE
Mirror images

### ISSUE THREAD

**Issue by Andrea-28-03** [SlRvb/Obsidian--ITS-Theme#259]
Hi, I'm not sure if this is doable with your snippet or theme but I didn't find anything and it could be really useful to have a word that flips images vertically and horizontally, thanks

**Comment by SlRvb** [comment]
This should be available in ITS v1.1.51 and in the image snippet as well! How to use it is here in the [documentation](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Image+Adjustments#Flip+%2F+Rotation)
