### ISSUE TITLE
Ability to turn off changed heading in embed

### ISSUE THREAD

**Issue by themvl** [SlRvb/Obsidian--ITS-Theme#26]
One of the things i didn't like about this theme is that it made headings in a embeded note smaller and fainter no matter what heading they where. This for me was solved by removing the associated css part. This would be a easy and very wanted setting.

**Comment by SlRvb** [comment]
I've added the option for that in the Style Settings under the `Note Elements` section. The toggle is `Embed Heading Undo`.

**Comment by SlRvb** [comment]
ITS Theme has been [updated](https://forum.obsidian.md/t/theme-its-dark-light-theme/12838/132) with that toggle, you just need to reinstall the theme to see it.

**Comment by SlRvb** [comment]
I'll be closing this issue for now. If the update's toggle doesn't work, feel free to reopen this issue or create another one about it.
