### ISSUE TITLE
[Bug] Obsidian--ITS-Theme Source mode will change WinTitle

### ISSUE THREAD

**Issue by Leiyi548** [SlRvb/Obsidian--ITS-Theme#260]
### Describe the bug

I want to use ahk to call out the window I want, through wintitle, ITS Theme in source mode to change wintitle to C:\Users\14246\Desktop\myGithub\People\HomePage.md, The default is HomePage-People-Obsidian v1.4.16

### To Reproduce
1. open a random file
2. use ahk to get current page wintitle
3. switch to preview mode
4. use ahk to get current page wintitle
5. see different

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.4.16
- ITS Theme Version: 1.1.4.2

### Additional context

I want the source code mode,wintitle to be HomePage-People-Obsidian v1.4.16

**Comment by SlRvb** [comment]
Um, I'm not sure that's something I can do with css alone. Do other theme's not do that?
