### ISSUE TITLE
[Bug] Infoboxes

### ISSUE THREAD

**Issue by Mondrethos** [SlRvb/Obsidian--ITS-Theme#261]
### Describe the bug
Hi,

Info boxes are not appearing to the left or right side of text, only above or below.

**Expected behavior**
For infoboxes to appear on the sides like they do on Wikipedia

### To Reproduce
Use the example infobox from the ITS documents site.

### Screenshots

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/9123069/79bf4fbd-d2b3-4321-a521-77ae93e0345c)

### OS
Where does the bug occur?

Linux

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.4.16
- ITS Theme Version: 1.1.43

**Comment by SlRvb** [comment]
Is this in live preview mode or reading mode. It'll only float in reading mode 🤔

**Comment by Mondrethos** [comment]
> Is this in live preview mode or reading mode. It'll only float in reading mode 🤔

I apologize, that was in live mode, works perfectly in reading mode, I'm dumb and didn't digest all the documentation perfectly, it was late and I'm working on migrating from notion.
