### ISSUE TITLE
Option to make [!column | list ]  elements run horizontally.

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#263]
Hi, not sure if this is already possible, but I think it would be really useful I we could make the elements of a [!column | list ] have a horizontal order. For example, I have the following callout:

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/a2bc9c0c-268b-4d90-a7c3-6bf93f734be3)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/24fe94a3-3c47-4da0-ae5f-336dcc3c813b)

Elements go from left to right, so everything is ok.
But If I add one more element, I would expect it to be placed under the first element in the left most part of the callout, like this

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/7bc8bc22-780e-43b1-bf6a-d285ce0d21f9)

But that is not the case, this is the result:
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/d0e494ae-34da-4833-924f-fc7c78239c8c)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/8f7d98b6-37fd-4abc-9076-bada82ebb410)

Do you think it would be possible to add this functionality?
Thanks a lot for the great work :)

**Comment by SlRvb** [comment]
This should be possible in ITS v1.2.24 if you use `list-x` instead of just `list` now :)

**Comment by albertoloscerritos** [comment]
Thank you so much :)

**Comment by albertoloscerritos** [comment]
One question, can I use this new functionality with only the snippet? Or do I need to install the ITS theme?

**Comment by SlRvb** [comment]
oh _oops_, it should be added to the snippet now too 🙈

**Comment by albertoloscerritos** [comment]
Thanks for the great work
