### ISSUE TITLE
[FR] Pathfinder Remaster TTRPG Theme

### ISSUE THREAD

**Issue by Zombiefleischer** [SlRvb/Obsidian--ITS-Theme#265]
With the release of the Pathfinder Remaster, I would like to have the new Remaster colors as a theme for ITS-Theme. I find the green more soothing than the red/brown stuff from the original.

**Comment by SlRvb** [comment]
I have a beta of this styling on ITS v1.2.56, let me know if there's anything that doesn't look right or should be styled differently!

**Comment by Zombiefleischer** [comment]
At first glance, everything seems fine. The color of the links pop a bit more than before, nothing I don't like. I'll test drive it further and by Thursday at the latest I'll have a session :smile:
