### ISSUE TITLE
[Bug] Dataview cards seems to be broken after Obsidian update: 1.5.3

### ISSUE THREAD

**Issue by scarfur** [SlRvb/Obsidian--ITS-Theme#266]
### Hey there! 🎅🏽

**After the update a dataview card looks like this:**
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/51059311/52eefade-148f-4737-b306-23445456663b)

Markdown (worked with version 1.5.2):
```md
> [!cards|dataview]
> ```dataview
> TABLE WITHOUT ID
> 	"![|sban cover hmicro](" + image + ")" as Image,
> 	"**"+ file.link + "**" AS "Column Name",
> 	file.mtime AS "Modified"
> FROM "folder"
> SORT file.mtime desc
> LIMIT 3
> ```
```

**Expected behavior**
Dataview works still as expected though they changed some things regarding path code (check patch notes from 1.5.3) if you use it like this (no leading `> `) - that said: maybe that is the issue and could be that dataview do not support leading `> ` after the update?

Plain working dataview markdown:
```md
TABLE WITHOUT ID
"![|sban cover hmicro](" + image + ")" as Image,
"**"+ file.link + "**" AS "Column Name",
file.mtime AS "Modified"
FROM "folder"
SORT file.mtime desc
LIMIT 3
```

### To Reproduce
1. update Obsidian to 1.5.3

### Screenshots
Unfortunatly I have no screenshot of how it looked before, but basically it was the filename and the date

// edit: tested the mobile version 1.5.2 (see picture below), all still working as expected:
![IMG_7110](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/51059311/0c36e5bd-a85c-4987-b83a-a5a89e16361d)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile (all working fine as usual and expected on iOS, obsidian version 1.5.2)
~~- [ ] Mobile (as usual Obsidian 1.5.3 is not released on mobile yet I guess)~~

### Versions
- Obsidian Version: 1.5.3
- ITS Theme Version: latest

### Additional context
I used the snippet along with the Minimal theme

**Comment by SlRvb** [comment]
Could you download the snippet again? I think it should be fixed now!

**Comment by scarfur** [comment]
Works again - thank you very much for everything 💕
