### ISSUE TITLE
[Bug] Highlight color on hovering 

### ISSUE THREAD

**Issue by Tx0n** [SlRvb/Obsidian--ITS-Theme#267]
### Describe the bug
I changed the color of highlitght when hovering over a button as you can see here 
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/45081985/163dddf5-34cc-4ead-b73d-325d311d1989)

These are the only color options I have in style settings to change the colors of highlight when hovering over them.

The problem is that it doesn't work in the file explorer and the top right explorer of obsidian
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/45081985/169fe1fd-e94a-431c-8630-5bb888ca3c18)

**Expected behavior**
Since these options are general (hover color, hover active color) they should also change the hover color in the file explorer and top right explorer

### To Reproduce
1. Just change colors in the highlighting options like above

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

### Versions
- Obsidian Version: 1.5.3
- ITS Theme Version: 1.2.01

**Comment by SlRvb** [comment]
I've added the option to change those colors under `Colors > Workspace > UI Elements > Sidebar Hover Background Color` in ITS v1.2.04
