### ISSUE TITLE
[Bug] Dataview query not showing up checkboxes if using "group by" function.

### ISSUE THREAD

**Issue by iloukine** [SlRvb/Obsidian--ITS-Theme#269]
### Describe the bug
After the latest Dataview update, I cannot see the checkmarks on tasks if "group by" function is used.
If using a different theme, do not have this issue.
I have went through all the setting on Dataview and used the "Style Settings" plugin to go through every option on ITS.
**Expected behavior**
Being able to see checkboxes when using a Dataview query.

### To Reproduce
1. Use ITS theme
2. Create dataview query with the "group by" function.

### Screenshots
![Obsidian ITS Theme Issue](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58890413/420c9072-1ac6-4e0b-9974-4fe07416ffb3)
![Obsidian ITS Theme Issue different theme](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58890413/7fda82d4-d9a1-4453-8d31-6e1687616344)

### OS
Windows 10

- [X] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.5.3
- ITS Theme Version: 1.2.20

**Comment by iloukine** [comment]
![Obsidian ITS checkbox issue 2](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58890413/8990c946-8244-4a71-b2d0-cbe0283edcf0)
![Obsidian ITS checkbox issue](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58890413/36edfdc7-dc3a-4564-b79f-0e283dad68d0)

**Comment by iloukine** [comment]
Something I have noticed, the left end of the tags are being cut off. 
You can really tell when turning off "originals bullet lines" and turning on "outline tags".

![Obsidian ITS issue](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58890413/00665822-f69b-4562-83d1-0e428de58b91)

Now that I think about it, I always thought it was weird that a non grouped dataview query had the checkboxes aligned farther left than the non grouped ones. It was noticeable, but still visible.

**Comment by SlRvb** [comment]
Can you let me know if this is fixed on ITS v1.2.24?

**Comment by iloukine** [comment]
Yes it was. Thank you very much.
I'm sorry if I missed an update. I could have sworn I checked yesterday,

**Comment by SlRvb** [comment]
It's all good, I just updated it haha. Thanks for letting me know it works 💖
