### ISSUE TITLE
[Bug] Cannot click at cursor

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#270]
### Describe the bug
Cursor does not spawn at clicked location in Live Preview mode

**Expected behavior**
Cursor should be spawned at clicked location in Live Preview mode. I did try the same with default theme and AnuPpuccin theme, and it works just fine.

### To Reproduce
Follow the layout in source mode below

### Screenshots
**Video showing the bug**
https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/3583e44b-bb46-46df-8e46-96aad5ea6035

**In Source mode**
![2024-01-22_20 31 41_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/793bfd21-ef5f-4f21-8bcf-f8e4b1e606d6)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: v1.5.3
- ITS Theme Version: 1.2.26

**Comment by SlRvb** [comment]
Hmmm, I can't seem to recreate this. If you disable style settings and reload, does that fix the cursor issue?

**Comment by Missionary2112** [comment]
I did try to disable style settings but it doesn't work. 

I think I know the issue. Allow me to demonstrate. Basically I use CSS that conflict with ITS theme and that's why the cursor does not appear at the clicked point. However, some other themes and default theme seem to work fine, except sticky note css I just installed recently. 

https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/51fd15e8-5eab-4db2-a247-f70e5b2e85c3

**Comment by SlRvb** [comment]
Hmmm any chance I could get that css file to test and see what's wrong?

**Comment by Missionary2112** [comment]
Yeah sure. 

[Dropdown & Sticky Notes CSS.zip](https://github.com/SlRvb/Obsidian--ITS-Theme/files/14090949/Dropdown.Sticky.Notes.CSS.zip)

- Dropdown forum: https://forum.obsidian.md/t/want-a-multi-level-dropdown-menu-inside-your-notes-you-can-i-built-one/40501
- Sticky Notes github: https://github.com/dhniceday/obsidian-sticky-notes

**Comment by Missionary2112** [comment]
Yes, it does enable to click on the heading but not the line below the heading.

https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/706d774e-f21a-4f76-b3da-b24d808b83b1

**Comment by SlRvb** [comment]
Just to check, what version of ITS are you on?

**Comment by Missionary2112** [comment]
Oh yes, my back. I just updated to the lastest ITS version and it works nice! Thank you :)
