### ISSUE TITLE
[Bug] Image becomes slightly transparent when using the callouts snippet for captions

### ISSUE THREAD

**Issue by AudioLotus** [SlRvb/Obsidian--ITS-Theme#271]
### Describe the bug
When I go to set up an image using:

```
>[!caption|center wtall]
>![[path/to/image.jpg]]
>Some caption text
```
Everything appears fine when editing live, however when I go to the reading view, I get this sort of translucent / transparent effect on the image. 

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/93493187/d59ddfa0-caf7-40cb-afa9-15118e228696)

This seems to happen even when the theme is set to default and other snippets are disabled.

---

### Expected behavior

Ideally the image would appear in its original state:

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/93493187/170017c2-6c34-45e5-8d5e-1f0a7b0a76a6)

Here's a better comparison of the images:

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/93493187/595f9865-761d-4636-9fe0-db28ff701dd3)

---

### To Reproduce
1. Set up caption callout:
```
>[!caption|center wtall]
>![[path/to/image.jpg]]
>Some caption text
```
2. Switch to reading view.

---

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

---

### Versions
- Obsidian Version: 
1.5.3

- ITS Theme Version: 
Just the most recent callout snippet 

### Additional context
n/a

**Comment by SlRvb** [comment]
Any chance the new update to the callout snippet fixes this?

**Comment by AudioLotus** [comment]
Yeah that seems to have fixed things! Thanks kindly!
