### ISSUE TITLE
Alternate checkboxes disappearing when unchecked

### ISSUE THREAD

**Issue by Pannerz** [SlRvb/Obsidian--ITS-Theme#273]
### Describe the bug
When unchecking alternate checkboxes then rechecking they will change into default [X] 

**Expected behavior**
Alternate checkbox symbols 

### To Reproduce
Uncheck any alternate checkbox 
Recheck the same alternate checkbox 
Changes into default checkbox 

### OS
Where does the bug occur?

- [ X] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.5.3
- ITS Theme Version: 1.1.47

**Comment by SlRvb** [comment]
This is more of an obsidian issue, technically the only real supported behavior is checkmarks filled in with an `x`. So there's nothing I can do about that from a CSS standpoint sorry! 🙈

**Comment by Pannerz** [comment]
Many thanks for your reply, understandable! I saw the alternate checkboxes working on your documentation https://publish.obsidian.md/slrvb-docs/ITS+Theme/Alternate+Checkboxes (stays after checking off) so I thought it might have been possible.
