### ISSUE TITLE
[Bug] Line Numbers and KB & M Navigation Aren't Consistent [Skips Lines]

### ISSUE THREAD

**Issue by VoltaicGRiD** [SlRvb/Obsidian--ITS-Theme#275]
### Describe the bug
ITS theme skips lines at various points in files. When navigating or viewing the file (or line numbers), while ITS theme is enabled, the line numbers are not consistent with the actual lines in the file. This occurs even with Restricted Mode enabled and all custom snippets turned off. This behavior continues even when utilizing the mouse cursor or the arrow keys to select a line, which skips any lines that don't have a line number, straight to either the very last line in the file, or the nearest "line-numbered" line. Even utilizing a right-arrow press on this line, does not move to the next line, it does nothing.
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58367364/b1d7ccd8-f7ae-4f43-a1ab-df5f7ce95fb3)

**Expected behavior**
Line numbers should reflect accurately the number of lines in the file, and attempting to select a line via the arrow keys or via the mouse, would accurate place the editing cursor where it belongs.

### To Reproduce
1. Enable the ITS theme
2. Work on a file with a decent variety of elements (code-blocks, headers, horizontal lines, in-line code)
3. Use only the arrow-keys and monitor closely for line jumps.

### Screenshots
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/58367364/78adbf3f-b966-4094-8359-0e1367da5b1b)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile (untested)

### Versions
- Obsidian Version: **1.5.3**
- ITS Theme Version: **Latest**

### Additional context

[Daily.md](https://github.com/SlRvb/Obsidian--ITS-Theme/files/14107134/Daily.md)

**Comment by SlRvb** [comment]
I think I've fixed this on ITS v1.2.33. Do update and let me know if it is 🙏🏽
