### ISSUE TITLE
[Bug] Statblock Admonition

### ISSUE THREAD

**Issue by skellyjelly** [SlRvb/Obsidian--ITS-Theme#276]
### Describe the bug
Hi there, something seems to be happening with the ITS theme and a "statblock" Admonition. It doesn't happen on the default or other themes, and still happens with all CSS snippets disabled. 

**Expected behavior**
The first image shows what it should look like, the second is what it currently looks like. Basically it's made to be very narrow and missing the title of the admonition. Other admonitions seem to be fine, it's just this one and just on ITS. If I were to rename the admonition to "Statblock" with a capital S it no longer happens. 

![goblin1](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/55192533/b6ec495f-73c5-40df-9056-b23ba8299b86)
![goblin2](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/55192533/09ad728f-c65f-4397-b3ef-a573d97fade5)

Then again here is what the Admonition looks like in another theme and in ITS. 
![image1](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/55192533/9353442b-3a4d-44e6-a1a8-f245a0ec2a96)
![image2](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/55192533/3acabcc6-03e5-4789-be31-f6a45d0ce34d)

### To Reproduce
Using ad-statblock in a note. 

### OS
Where does the bug occur?

- [X] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: most current
- ITS Theme Version: most current

**Comment by Jacks-01** [comment]
Not sure if these two are related, but I'm inclined to think they are given how similar the styling looks. I created this statblock about a day ago: 
<img width="504" alt="image" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/92601085/1f69b312-95c4-47c5-83ba-a0f680b33c07">

And after updating to the most recent version the exact same code looks like this: 
<img width="526" alt="image" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/92601085/52c6ddc1-313a-4be1-b051-8dd961b3a5ce">

Not sure if this was a redesign or intended but I thought I would mention it just in case.

**Comment by SlRvb** [comment]
I have changed the callout name to `statblocks` instead to avoid it conflicting with these admonitions, so if you update my theme it should be fixed now!
