### ISSUE TITLE
[Bug] Collapsible Callout Snippet

### ISSUE THREAD

**Issue by Jack-Chronicle** [SlRvb/Obsidian--ITS-Theme#279]
### Describe the bug
The Snippet for alternate call outs isn't letting you collapse/expand any Callout that is offset to the right in reading view 

**Expected behavior**
Any alternate Callout included that defaults to the right or that is offset to there should be capable of collapsing and expanding, with the +/-, in reading view as well as live preview mode

### To Reproduce
1. Go to live preview
2. Make a Callout, with a position to the right
3. Make it Collapsible
4. Go to reading view
5. Can't expand/collapse

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

### Versions
- Obsidian Version: 1.5.8 (126)
- ITS Theme Version: ---

### Additional context
It works fine in the latest ITS Theme, but the Snippet from the GitHub isn't working

**Comment by SlRvb** [comment]
Does this happen on the default theme? I can't seem to recreate this 🤔

**Comment by Jack-Chronicle** [comment]
Yeah, I tried it without any other snippets or plugins and on the default theme

Specifically the aside callout was what I was checking, but some others were having issues when I tried them as well

**Comment by Jack-Chronicle** [comment]
After messing around, I find out the real issue
It works fine so long as the next text after the Callout isn't a list

I just added some text after it and it started working again

**Comment by SlRvb** [comment]
Could you update the snippet and let me know if it's fixed now? Thanks for bringing my attention to this!

**Comment by Jack-Chronicle** [comment]
That appears to have fixed it, thanks!
