### ISSUE TITLE
[Bug] Pathfinder alternate color scheme does not use proper colors

### ISSUE THREAD

**Issue by GraveyardDuck** [SlRvb/Obsidian--ITS-Theme#281]
### Describe the bug
Rather than the expected color scheme, the Pathfinder color scheme uses default ITS colors. Fonts are changed accordingly, but not colors.

**Expected behavior**
Color scheme should resemble this: [https://raw.githubusercontent.com/SlRvb/Obsidian--ITS-Theme/main/Images/Theme-Pathfinder--Lightmode.png](https://raw.githubusercontent.com/SlRvb/Obsidian--ITS-Theme/main/Images/Theme-Pathfinder--Lightmode.png)

### To Reproduce
1. In Style Settings, reset ITS Theme Settings to default.
2. In ITS Theme Settings, select Alternate Color Schemes, then select Pathfinder in the TTRPG drop-down menu.

### Screenshots
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/31831396/43759068-ce48-43ee-8ff9-df5628d41f89)

### OS
Where does the bug occur?

- [X] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.5.8
- ITS Theme Version: 1.2.44

**Comment by SlRvb** [comment]
Could you update to v1.2.45? I think this should be fixed now

**Comment by GraveyardDuck** [comment]
> Could you update to v1.2.45? I think this should be fixed now

That did the trick! Thank you!
