### ISSUE TITLE
[bug] Archiving of Kanban boards

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#29]
There is a problem with the archive indent of the Kanban board

![image](https://user-images.githubusercontent.com/30563826/135702791-1082c36f-ebd5-41a7-96df-868624519478.png)

![image](https://user-images.githubusercontent.com/30563826/135702821-dccf6a41-5e46-4e20-82c7-dcbfeb01f549.png)

**Comment by SlRvb** [comment]
I don't use the archive feature of Kanban too heavily so could you help me recreate the archive card indentation so I could see what's gone wrong?

**Comment by Borber** [comment]
> I don't use the archive feature of Kanban too heavily so could you help me recreate the archive card indentation so I could see what's gone wrong?

It seems that it's not just indented lists, but also regular text that obscures the archive icon, which only returns to normal when hovering

**Comment by SlRvb** [comment]
Oooh, I think I might know what happened. Have you updated the theme in the past 1-2 days?

**Comment by Borber** [comment]
> Oooh, I think I might know what happened. Have you updated the theme in the past 1-2 days?

Of course, I keep an eye on ITS updates every day, and I basically update every version as soon as I can.

**Comment by SlRvb** [comment]
Ah yep, I see where I messed it up and I think it should be fixed now.

**Comment by Borber** [comment]
> Ah yep, I see where I messed it up and I think it should be fixed now.

Yes, it's fixed,  perfect.
