### ISSUE TITLE
Callout boxes not collapsable when containing an iconize icon

### ISSUE THREAD

**Issue by Davve37** [SlRvb/Obsidian--ITS-Theme#292]
### Describe the bug
Callout boxes not collapsable when containing an iconize icon

**Expected behavior**
When you press the little arrow the box should collapse.

### To Reproduce
```
> [!note]+
> :RaArcher:
```

### OS
Where does the bug occur?

- [x] Desktop

### Versions
- Obsidian Version: v.1.5.11
- ITS Theme Version: 1.2.56

**Comment by SlRvb** [comment]
Feel free to reopen when Iconize fixes it and if my CSS does still break it after that.
