### ISSUE TITLE
Manual image width ignored in preview

### ISSUE THREAD

**Issue by KosRud** [SlRvb/Obsidian--ITS-Theme#293]
https://github.com/SlRvb/Obsidian--ITS-Theme/blob/75d040c5418f3f655a2a90a8e5a234cc0008520e/Snippets/S%20-%20Images%20Adjustments.css#L383

This line seems to force images to 100% width in preview mode, even if the width was specified manually. This only happens in preview mode, edit mode displays the image normally. When I commented out this line, the image was displayed with desired width in both preview and edit.

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/36504423/cd759564-864c-4057-93ae-65b3f882ca04)

**Comment by SlRvb** [comment]
This should be fixed now on ITS v1.2.58!

**Comment by KosRud** [comment]
> This should be fixed now on ITS v1.2.58!

👍I just updated and the images appear correctly.
