### ISSUE TITLE
[FR] Add Alternate Checkbox: `<`

### ISSUE THREAD

**Issue by mvriel** [SlRvb/Obsidian--ITS-Theme#294]
### Is your feature request related to a problem? Please describe.

For Bullet Journaling, a common mark is to use the `<` chevron to indicate a task is migrated to the Weekly or Monthly spread. This is present in Minimal and when I switched from Minimal to ITS, my previous (and future) checkboxes 'broke' because they now show as completed.

### Describe the solution you'd like

Is it possible to add a new Alternate Checkbox `<`? I would love for it to be an icon of an arrow pointing backwards (similar to `>`); though I understand this may be different from the presentation in Minimal. For Bullet Journaling this would be nice.

**Comment by SlRvb** [comment]
If you update my theme to v1.2.61 `<` should now be added! Thanks for the suggestion.

**Comment by mvriel** [comment]
Works like a charm! Thank you!

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/193704/02ee36bb-f5ed-49be-8a60-ed206cea848e)
