### ISSUE TITLE
Process to change button size on ribbon

### ISSUE THREAD

**Issue by blaidd31204** [SlRvb/Obsidian--ITS-Theme#296]
I love your ITS Theme!  Apologies for using the issues thread to contact you.  I am a brand new user to Obsidian and have zero coding experience.  I attempted to look at the CSS code in the theme.css file to reduce the size of the buttons on the left ribbon.  I prefer to have as many buttons visible without having them move/scroll.  In the normal Obsidian theme, I can change the button sizes with the following snippet:

.side-dock-ribbon {
  --ribbon-width: 30px;
}
.side-dock-ribbon svg {
  height: 15px;
  width: 15px;
}

However, the ITS theme seems to override that process and there is nothing in the Style Settings plug-in to adjust the buttons on the left ribbon.  IS there any suggestion on what I could do to make them smaller and pack more into the left ribbon?  Thanks, in advance, for any help you can give.

**Comment by SlRvb** [comment]
Can you update to ITS v1.2.63 and let me know if the Ribbon Width Sizing and Ribbon Icon Sizing sliders work in the style settings? (You can use the search to bring those up) Those should accomplish what you want :)

**Comment by blaidd31204** [comment]
WILCO tonight.

**Comment by blaidd31204** [comment]
Thanks.  It made the icons smaller, but it did not reduce the space in-between the icons to have them stack closer together.  Is that possible in ITS Theme?  Using the snippet above on the default theme, I can do it.  Just not on the ITS WOTC theme.

**Comment by SlRvb** [comment]
Ah shoot, on ITS v1.2.66 I've added `Ribbon Icon Spacing` that should do what you want

**Comment by blaidd31204** [comment]
This works great!  Is there anything that can change the same type of spacing on the status bar?

**Comment by SlRvb** [comment]
Added `Status Bar Spacing` slider in ITS v1.2.67. Do let me know if that's good enough!

**Comment by blaidd31204** [comment]
This was awesome and fixed it immediately!  Thank you so much!
