### ISSUE TITLE
[Bug] txt-c (and others) are not respected in [!cards|dataview]

### ISSUE THREAD

**Issue by scottTomaszewski** [SlRvb/Obsidian--ITS-Theme#297]
### Describe the bug
Having a cards callout using dataview with the `txt-c` metadata doesnt center text

**Expected behavior**
text is centered

### To Reproduce
Create a note with name `test1223` and content

```
---
name: Bill
---

> [!cards|dataview 2 txt-c]
> ~~~dataview
> TABLE name
> WHERE file.name = "test123"
> ~~~
```
Render

### Screenshots
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/5295276/acbf49bd-f693-4dc2-b808-ede4d24e7ce9)

### OS
Linux

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.5.12
- ITS Theme Version: downloaded fresh copy before making this issue

### Additional context
n/a

**Comment by SlRvb** [comment]
Should now be fixed on ITS v1.2.68!
