### ISSUE TITLE
[FR] Dragonbane TTRPG Theme

### ISSUE THREAD

**Issue by retrodans** [SlRvb/Obsidian--ITS-Theme#298]
I am starting to setup a [Dragonbane](https://freeleaguepublishing.com/wp-content/uploads/2023/11/DRAGONBANE-full-game-2048x1345.png) campaign on Obsidian, but it would be great if there was a way to theme it to use some more standard Dragonbane theming. At the moment I am just using Drowned, but there are fonts that could work nicely etc. https://www.dafont.com/final-fantasy.font with standard colors.

Is there a way we can create our own custom schemes for other TTRPG theming, and maybe one we can export and share with you as a PR to help expand it?

**Comment by SlRvb** [comment]
I do have a template [Alt Color Scheme snippet here](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Alt%20Color%20Scheme%20Template.css) for styling my theme, do let me know if there are some things you want to do that are somewhat not possible with the template and I'll help out as best I can to either add the variables to the snippet or adjust my theme to add that feature in for you to style.

I've been trying to figure out how exactly I want tackle user submitted themes and I'm thinking that I might have a separate snippet that people can submit their themes to and others can download and use. So if you'd like to work with me on figuring out the best way to go about that I would really appreciate it!
