### ISSUE TITLE
ITS Theme: Bullet Point Indent Issue

### ISSUE THREAD

**Issue by moorebi** [SlRvb/Obsidian--ITS-Theme#30]
Then using the ITS theme cannot seem to figure out if this is a setting or not but when I use bullets and they "line wrap" they are not "aligned correctly.. See attached screen shot for issue.

![image](https://user-images.githubusercontent.com/6247939/136035316-f91f5c52-e0c0-4130-9c18-a9333a5f1ee3.png)

**Comment by SlRvb** [comment]
I believe in the new commit I just pushed, this should be fixed. 

Thanks for letting me know! I used to just think this was default behavior and tolerated it, but you got me to check and realize that it definitely wasn't.

**Comment by moorebi** [comment]
Refreshed the theme and looks great now.... thanks
