### ISSUE TITLE
Tabs in infobox [FR] 

### ISSUE THREAD

**Issue by Lights-dummies** [SlRvb/Obsidian--ITS-Theme#300]
Dear All,
thank you very much for this theme, is faboulous!
I have a request: does it's possible to have tabs in infobox like fandom?
I attached a picture for better undestanding.
Thank you in advance
![Portable_infobox_panel](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/113032023/8aee42f4-3c3a-47fe-97db-1666d49c3006)

**Comment by SlRvb** [comment]
Hey, so I can't really accomplish this with just CSS alone, but there is this option  that uses metabind if you want to get that kind of functionality: https://github.com/sailKiteV/Obsidian-Snippets-and-Demos/tree/main/TabsInObsidian

**Comment by Lights-dummies** [comment]
Dear,
thank you very much!
This is what I need !!
