### ISSUE TITLE
[FR] Relative image size scaling

### ISSUE THREAD

**Issue by TheAussieTinker** [SlRvb/Obsidian--ITS-Theme#301]
### Is your feature request related to a problem? Please describe.
When you resize an image by assigning the width in pixels, it doesn't translate well across devices.

### Describe the solution you'd like
Having an option to adjust the size of the image based on the size of the workspace. This could occur with syntax like:
![[image.png|50%]] where the 50% means the width of the image will take up 50% of the workspace.

### Describe alternatives you've considered
Relative to the screen size if relative to the workspace is too hard.

**Comment by SlRvb** [comment]
Oops, I should've added this feature to the docs. I can't quite do it your way but I do have relative sizing on my image adjustments. Do let me know if the [documentation here at the bottom](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Image+Adjustments#Sizing) about it is unclear about how to use it, thanks for reminding me I hadn't put it on there! 🙈
