### ISSUE TITLE
[FR] Image captions

### ISSUE THREAD

**Issue by merlin1973** [SlRvb/Obsidian--ITS-Theme#302]
Hi, I was just wondering if there's any plan to add Image captions?

I normally use the html <sub></sub> command to add sub text to images. 

but this doesn't work when I use the ITS themed |right or |left option for embedded images.

I've tried googling this for some alternatives but haven't found anything yet.

Thanks
Steve

**Comment by SlRvb** [comment]
Hmm well there already is using the [caption callout](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callouts/Callout+-+Captions) or the [#cap](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Image+Adjustments#Extras) flag on the image to kinda sorta do that. 

No idea what exactly your HTML stuff looks like but have to imagine if you want to make it float just adding this `style` into the html div would work: `style='float: right;'` or `style='float: left;'`
