### ISSUE TITLE
Header alignment and underlines affected by Fantasy Statblocks [Bug] 

### ISSUE THREAD

**Issue by PurplePixieX** [SlRvb/Obsidian--ITS-Theme#303]
### Describe the bug
See: [Fantasy Statblocks Bug#332](https://github.com/javalent/fantasy-statblocks/issues/332)

Headers seem to act oddly when Fantasy Statblocks is also installed. It takes away center alignment for all headers and also completely removes the underline for h3 headers.

**Expected behavior**
Headers should look like this with and without hcl cssclass.

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/126978878/94fc55cf-9942-4074-a5c5-04ead4a3d332)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/126978878/9a0d512a-9d27-42a2-8a1c-fa58cedf9be0)

**Current behavior**
This happens with Fantasy Statblocks enabled.

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/126978878/28c2b1f8-f6ae-4c76-9c1e-ae496d33514e)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/126978878/3547104a-406f-465a-ae41-038983031c17)

### To Reproduce

1. Launch a clean vault in obsidian
2. Install the ITS theme
3. Create a new note and add the hcl css class
4. Create a header (Looks fine up until here)
5. Enable Fantasy Statblocks plugin
6. Header is not centered

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: v1.5.12
- ITS Theme Version: v1.2.66

### Additional context
ONLY happens with Fantasy Statblocks. Went to their git first but no solution was found.

**Comment by SlRvb** [comment]
Yeah this has been an issue with the statblocks plugin that I've been wanting fixed, the [styling here](https://github.com/javalent/fantasy-statblocks/blob/ded895d4da46e8b4ccfee2a1fc15a82ad81f628d/src/layouts/BnB/xCSS/Bunkers-and-Badasses.css#L414) from like 414 to 470 is the cause of the issue with my theme that I cannot fix on _my_ end. 

I've had to disable the statblock plugin myself while I waited for the fix from either @
valentine195 or @sigrunixia

**Comment by valentine195** [comment]
Can you check 4.3.1?

**Comment by PurplePixieX** [comment]
> Can you check 4.3.1?

Issue resolved!
