### ISSUE TITLE
[Bug] advanced table plugin issue

### ISSUE THREAD

**Issue by HippyCraig** [SlRvb/Obsidian--ITS-Theme#304]
### Describe the bug
When ITS theme is not on all text will wrap based on the size of the working area in edit mode.   But with advanced table in edit mode spaces the rows and columns and the word wrap on tables is disable but the other text stays within edit window bouderies.   When I turn on the ITS this table behavior is gone, the tables wrap and make it difficult to read

this Al occurs in edit mode everything renders within the boards of the window

**Expected behavior**
Should work the same regardless of ITS theme or not

### OS
Windows 10 
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.5.12
- ITS Theme Version: current

**Comment by SlRvb** [comment]
Toggle added to ITS v1.2.71 Style Settings if you search for `Unwrap Table` that should do it!

**Comment by HippyCraig** [comment]
I upgraded the theme and its at 1.2.70  is there a beta you wanted me to get ?  or is this not published yet?

**Comment by HippyCraig** [comment]
Great thanks 

so far it looks great
