### ISSUE TITLE
[Bug] Headers changing with level

### ISSUE THREAD

**Issue by Taliesin1** [SlRvb/Obsidian--ITS-Theme#305]
### Describe the bug
I've manually set all of my headers to be the same color, and they are working as expected in one vault. I copied the .obsidian folder from that vault to a new vault and started editing the colors in Style Settings. Long story short, my headers in the new vault are rendering in different colors at the different levels. H1, H4, and H5 are rendering at the right color, but H2 and H3 have a mind of their own in the new vault and will not render in my specified color. I can't find any setting that says these colors should change with the levels, and I've been through every setting several times and cannot find the odd colors for H2 and H3 spec'd anywhere. It's almost like something is cached or hung up somewhere.

Also my vault label in the new vault is rendering in the color I specified, but not the font I specified. The font is rendering correctly in the page titles, however, so I know it's loaded. The font is rendering correctly on the original vault. Very strange.

**Expected behavior**
All the headings to display in the colors (and font) I sepc'd.

### To Reproduce
N/A

### OS
Mac OS 14.4.1

- [ ] Desktop

### Versions
- Obsidian Version: 1.5.12
- ITS Theme Version: Not sure

**Comment by SlRvb** [comment]
oh, now this is very weird and I don't think this should be happening. Did you later toggle on a different Alternate Color Scheme? That's the only thing I can think of that could possibly override your styling. 

Otherwise a direct copy of the .obsidian folder with all the snippets, themes, plugins, etc should basically result in a completely identical look 🤔

**Comment by Taliesin1** [comment]
Thanks for the quick reply!

Yeah, I did a direct copy, but then I started editing the new vault/version. And this weirdness crept in. Almost like a setting is cached — but the old vault didn’t have changing colors on the headers, either. Super weird.

Is there a cache or something. I just can’t figure out where this is coming from.


M.

**Comment by SlRvb** [comment]
Hmmm there shouldn't really _be_ a cache most especially for just appearance stuff. Do you have a screenshot maybe I could look at that showcases the differences between the old vault and new vault?

**Comment by Taliesin1** [comment]
Here are three screenshots:

The first show the original vault with all the header said to a red color.

The second shows the copy of the original vault —same page. The melon and red color headers should be green, like the page title. Also the name of the calendar in the right sidebar is red, but that’s just because it’s H3, I imagine.

The third shows the settings on my headers on the new vault showing them all to be set green.


Thanks!

￼

￼

￼

**Comment by SlRvb** [comment]
Hmmm, you might have to send those images again, can't quite see it on github. I just get [OBJ] 🙈

**Comment by Taliesin1** [comment]
￼￼￼

**Comment by SlRvb** [comment]
hmmmm, nope still got the [Obj]. Might wanna hop onto the github site and send it from there 🙈

**Comment by Taliesin1** [comment]
Sorry. Let’s try this:

<img width="1599" alt="Screenshot 2024-05-19 at 10 02 13 PM" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/10515719/836138cc-a405-4f5b-b792-7b493f4fe147">

<img width="1646" alt="Screenshot 2024-05-19 at 10 02 24 PM" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/10515719/9b46ad01-554e-453b-8b10-bfc26bf54850">

<img width="773" alt="Screenshot 2024-05-19 at 10 03 58 PM" src="https://github.com/SlRvb/Obsidian--ITS-Theme/assets/10515719/a66e7923-b132-44f5-9adb-20cf4e0ff947">

**Comment by SlRvb** [comment]
Oh hmmm it _does_ seem like you've toggled on wotc? You haven't right?

**Comment by SlRvb** [comment]
Feel free to reopen if you've got any more info for me to try to reproduce.
