### ISSUE TITLE
[Bug] Mark quote callout overlap

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#307]
Great work as always. I think there is a bug when using the S - Callouts.css snippet (the one that contains the code for the quote callout). As you can see from the following picture 

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/0c58c9fe-5d5a-4a6e-aeaf-e0297ece5207)

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/5fd80b67-7e6a-4f18-ab9f-84364b8fcb0e)

I am using the default obsidian theme, and obsidian v 1.6.1. and I am also using the latest version of the snippet. 
Also, is there a way to automatically surround the text with " " when using the quote callout? I think it would be a great addition. Thanks

**Comment by SlRvb** [comment]
If you update the callout snippet this should also be fixed, thanks for letting me know!

**Comment by albertoloscerritos** [comment]
Thank you so much. 
Your snippets are one of the most useful tools in obsidian. 
Awesome job as always :) have a good night.
