### ISSUE TITLE
[Bug] Inline Title Size has no effect in Style Settings

### ISSUE THREAD

**Issue by finaldragn** [SlRvb/Obsidian--ITS-Theme#308]
### Describe the bug

When using the "Inline Title Size" slider under **ITS Theme > Workspace > Sizing > Notes**, there is no effect on the title of notes.

**Expected behavior**
The size of the title of a note should decrease or increase based on the position of the slider.

### To Reproduce
1. Open the Style Settings community plugin.
2. Click on ITS Theme Settings > Workspace > Sizing > Notes
3. Drag the slider thumb along the track in either direction 
4. Note lack of visible effect on any note title.

### OS
Where does the bug occur?

- [ X ] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.5.12
- ITS Theme Version: 1.2.72

### Additional context
Local workaround/quickfix: By changing the id in theme.css in the **.obsidian/themes/ITS Theme** folder, functionality can be restored. (Ln 189: "inline-title-font-size" > "inline-title-size"). Doesn't seem like the proper fix since it goes from high specificity to low specificity, but hope it helps.

**Comment by SlRvb** [comment]
Should now be fixed with ITS v1.12.74+, thanks for letting me know!
