### ISSUE TITLE
[FR] How to resize image with caption, and keep caption centered

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#309]
Hi, thanks for the awesome job. I have one question. If I am using the S - Images Adjustments.css, when I add a caption to an image it works perfectly...
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/6bdba5b1-7982-406a-89f9-7793fd8aab82)

However, my question is if it is possible to resize the image and keep the caption aligned to middle of the image and not to the middle of the page:

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/6c2f0cce-968b-4726-b7d0-60412b7ef1d4)

Thanks :)

**Comment by SlRvb** [comment]
This should be fixed, but I can only affect how this works using my sizing names (`wmed`, `wtiny`, etc) since I can't really grab obsidian's `100` and the like numbers myself unfortunately.

**Comment by albertoloscerritos** [comment]
Hi, thanks :)
Just one question, how am I supposed to write this?
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/c5d5d482-f770-49af-a972-ea9c072626a9)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/3036ac30-9210-4635-ad9e-890db40c348b)
A tried these 2 implementations, in both cases the size changes, but in both case the caption includes the size modifier.
Thanks for the help.

**Comment by SlRvb** [comment]
Oh sorry! It should be like this `#cap#wmed`, with any of the size variables in my docs.

**Comment by albertoloscerritos** [comment]
Hi. 
Am I doing something wrong? I tried the following two implementations, based on your reply. But it looks like I am not able to change the size of the image.

![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/948f9246-bdf5-426c-8064-66c78e8b907d)
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/94f39875-8dd5-496b-b468-847e876fea03)

The results are the same in both reading and editing mode.
Also, is the character `\` actually required?
Thanks :)

**Comment by SlRvb** [comment]
Ah, try and redownload the snippet again? I think I fixed the issue. And no you don't need the `\` escape.

**Comment by albertoloscerritos** [comment]
Hi, good morning. 
I just tried the new snippet in and obsidian sandbox. The resizing works
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/73661bc0-1e7f-4a4f-9e6c-cd74bef1e5d7)
However in reading mode, the caption is now in the center again 
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/6a4d2040-4ea0-4007-b9c7-2ae0f02245a7)
:(

**Comment by SlRvb** [comment]
Ah shoot, I think I've fixed that issue now. Could you redownload the snippet?

**Comment by albertoloscerritos** [comment]
It worked. You are the best :)
