### ISSUE TITLE
[FR] Is there an option to align a callout to the right (or center) without wrapping text 

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#311]
Hi. 
Is it possible to align a callout to the right but avoid the text from warping next to the callout.

![right](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/16707033/81f88b04-49e5-48da-b668-5ab82fcacbcd)

Thanks.

**Comment by SlRvb** [comment]
If you put `|clear` in that callout that should do the trick 🤔

**Comment by SlRvb** [comment]
Okay I've added this functionality if you use the `|block` option. Let me know if this works as intended!

**Comment by albertoloscerritos** [comment]
Thank you so much. It worked perfectly :) 

One completely unrelated question, is there any snippet to use the following cssclasses: https://publish.obsidian.md/slrvb-docs/ITS+Theme/CSS+Classes
Or is it only possible while using your theme?
Thanks
