### ISSUE TITLE
[Bug] Excalidraw right click menu styling overflow issue

### ISSUE THREAD

**Issue by WX-Zarroc66** [SlRvb/Obsidian--ITS-Theme#316]
### Describe the bug
While utilizing the Excalidraw plugin, right clicking on elements would have a selection table appear, the options within that table have been overflowing and going off screen not allowing me to access some of the options.

**Expected behavior**
When right clicking on an element, a table would appear with all of its selections on the screen. 

### To Reproduce
1) Install & Enable Excalidraw Plugin,  ITS ThemeGo, and Style Settings Plugin
2) Create new Excalidraw drawing
3) Add any element from selection bar at top of drawing; Box, Circle, Diamond, or arrowed line are elements within my drawing. 
4) Right Click Element
5) See pop-up from right clicking
![Issue Screenshot](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/173321939/75f6aa15-2f69-481a-9e73-f6def7c72fe2)

### OS
Where does the bug occur?

- [X ] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: v1.6.3
- ITS Theme Version: v1.2.79

**Comment by SlRvb** [comment]
Should be fixed in ITS v1.2.88!
