### ISSUE TITLE
[Bug] Image cannot be embedded in bullet list

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#317]
### Describe the bug
Image cannot be embedded in bullet list, unless it's resized. 

**Expected behavior**
Image should be embedded in bullet list

### To Reproduce
1. Create a bullet list
2. Embed an image on the bullet list without resizing it
3. See error: the image cannot be embedded

### Screenshots
**ITS theme**
![2024-06-21_15 26 24_CSX|400](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/65490488-526d-4a01-b637-4d65ebfa7640)

Default theme
![2024-06-21_15 26 41_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/5ea5bf1d-31b4-4882-96d1-05ceea653332)

However, if I resize the image, it works fine. In this example, I resize down to `|400`
![2024-06-21_15 27 16_CSX|400](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/964bc5a9-33c5-4836-8567-43a6f7861a1b)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.6.4
- ITS Theme Version: 1.2.79

**Comment by SlRvb** [comment]
Hmmm I can't seem to replicate this issue, not sure if this is also related to the #282 issue that I also can't seem to replicate 🤔

**Comment by Missionary2112** [comment]
I think I know what happened. 
When the editor window is narrow, the image cannot be rendered. But when I close all the sidebar and the editor window gets wider, the image now can be rendered. 

**Narrow editor window** (I use this all the time, taking note on the right side of the window, while watching the content on the left side)
![2024-06-24_22 01 26_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/2e655744-80f0-490c-974a-784fdbfc6c13)

**Wide editor window**
![2024-06-24_22 02 44_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/97496149-2387-4c50-8d1c-6b177097d480)

**Comment by SlRvb** [comment]
Hmmm, even with installing the plugin I might've thought would be conflicting I still can't recreate this. Do you happen to have the image I could test this on or at least what size the image is so I can try to replicate this?

**Comment by Missionary2112** [comment]
Sure, here is the link: https://www.playbook.com/s/missionary/fZj9hx5N9Q8MQvbYXm3TSPTY?assetToken=B4JKMYBug2UJJ6TNpcCoE5LE

Are you sure you tried it on a bullet list `- ![[image]]` ?
![2024-06-25_15 33 44_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/ae599687-0951-4390-ae13-4d93e54a46ba)

**Comment by SlRvb** [comment]
*oh* this looks like funky conflicts between the Justify Text setting and just huge images being pushed super far to the right 🤔

**Comment by SlRvb** [comment]
Okay yeah, that's exactly what's happening. Now I can definitely recreate this, will see what I can do about it

**Comment by SlRvb** [comment]
Should be fixed in ITS v1.2.88!
