### ISSUE TITLE
additional spacing between checks spacing in the Checks callout box

### ISSUE THREAD

**Issue by dgiles474** [SlRvb/Obsidian--ITS-Theme#319]
### Describe the bug
I have been using the Checks callout in my vault and with the most recent 1.6.3 obsidian update I have noticed that there has been added spacing in between the checks boxes. Is there a style setting or callout adjustment to help adjust the spacing of the setting. 

**Expected behavior**
reducing the spacing between the check boxes in the checks callout

### To Reproduce
1. create a checks callout
2. follow the syntax outlined in the SIRvb ITS documentation
3. you may notice an increase in spacing between the Check Boxes

#### This is the checks example in the documentation 
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/164708045/404a857e-dc4f-4b90-86f3-9aa1f2b7e065)
#### This is what it looks like in my vault
![image](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/164708045/b6ff477b-c54c-49d5-8ea1-b60fb4ed9e69)

### Mode
What mode(s) does the bug occur? Select all that apply.

- [ ] Source Mode
- [x] Live Preview
- [x] Reading Mode

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.6.3
- ITS Theme Version: 1.2.82
- [x] Using ITS Snippet: 

### Additional context
Overall This is my favorite Obsidian theme. I love using it for my DnD campaign.

**Comment by SlRvb** [comment]
Should be fixed in ITS v1.2.84!

**Comment by dgiles474** [comment]
You're awesome! Thanks! I would love to know how you fixed it so fast?

**Comment by SlRvb** [comment]
Mostly just that the `list-indent` property is a new thing for lists that my css didn't account for so just setting that to `0` was all I had to do 😂
