### ISSUE TITLE
[Bug] Checkboxes appear twice

### ISSUE THREAD

**Issue by jcesguerram** [SlRvb/Obsidian--ITS-Theme#321]
### Describe the bug
I installed the SIRvb css snippet for alternative checkboxes. When i enable it and put a checkbox it appears twice or sorf of super imposed on another

**Expected behavior**
I expected simply the alternate checkboxes

### Mode
What mode(s) does the bug occur? Select all that apply.

- [X] Source Mode
- [X] Live Preview
- [X] Reading Mode

### OS
Where does the bug occur?

- [X] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.6.5
- ITS Theme Version:
- [ ] Using ITS Snippet: SIRvb alternate checkboxes

### Additional context
I'm using the Border theme.
When I disable the css snippet I still get a version of the checkboxes. It's as if somewhere else in my vault there were other instructions for alternate checkboxes and were coming into conflict with the snippet

**Comment by SlRvb** [comment]
Should now be fixed if you update/redownload the alt checkboxes snippet
