### ISSUE TITLE
[Bug] "Disable Row Hover Highlight" not working on odd-numbered rows

### ISSUE THREAD

**Issue by HoopyFreud** [SlRvb/Obsidian--ITS-Theme#324]
### Describe the bug
When Disable Row Hover Highlight is checked, odd-numbered row still have a hover color.

**Expected behavior**
Both odd and even numbered rows should not have a hover color when Disable Row Hover Highlight is checked

### To Reproduce
1. Check Disable Row Hover Highlight
2. Create a table with at least 2 rows

### Mode
What mode(s) does the bug occur? Select all that apply.

- [ ] Source Mode
- [ ] Live Preview
- [x] Reading Mode

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.6.7
- ITS Theme Version: 1.3.00

**Comment by SlRvb** [comment]
Oops, thanks for the help and the pointer in the pull request. Should be fixed now in v1.3.03!
