### ISSUE TITLE
[Bug] Blockquote text not rendered correctly anymore since version 1.7

### ISSUE THREAD

**Issue by DutchPete** [SlRvb/Obsidian--ITS-Theme#326]
### Describe the bug
When the cursor is not in a blockquote, the text font is not the same as the surrounding text font. 

**Expected behavior**
It should be the same.

### To Reproduce
1. Start a blockquote with `>`, then press the space bar 1x
2. Type some text
3. Click outside the blockquote block

### Screenshots
![image](https://github.com/user-attachments/assets/af5034c2-20bf-4dfd-b58c-1f4849451b48)

### Mode
What mode(s) does the bug occur? Select all that apply.

- [ ] Source Mode
- [x] Live Preview
- [x] Reading Mode

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.7
- ITS Theme Version: 1.3.03
- [ ] Using ITS Snippet:

**Comment by SlRvb** [comment]
Should be fixed in ITS v1.3.19+

**Comment by DutchPete** [comment]
Thank you.
