### ISSUE TITLE
[Bug] Make Match Case symbol visible in light mode

### ISSUE THREAD

**Issue by Missionary-OSBS** [SlRvb/Obsidian--ITS-Theme#328]
### Is your feature request related to a problem? Please describe.
I miss this Match Case symbol in search pane for a long time because it's not visible in Light mode

**Match Case disabled**
![2024-08-22_22 40 10_CSX](https://github.com/user-attachments/assets/ea827232-c1d8-4111-987e-e689145ac528)

**Match Case enabled**
![2024-08-22_22 41 09_CSX](https://github.com/user-attachments/assets/eb4db271-090d-4e9b-a7d2-6b3d264cf3a7)

### Describe the solution you'd like
I would like the Match Case symbol in different color but white when it's disabled

### Describe alternatives you've considered
Use different theme or use dark mode

**Comment by SlRvb** [comment]
Should be fixed in v1.3.16, thanks!
