### ISSUE TITLE
[Bug] Kanban current view reading visual issue

### ISSUE THREAD

**Issue by HonorableEmperor** [SlRvb/Obsidian--ITS-Theme#329]
### Is your feature request related to a problem? Please describe.
**Editing mode**

![스크린샷 2024-08-23 오후 10 09 17](https://github.com/user-attachments/assets/f05771e8-22f3-492c-af9d-8b5a59731e2e)

**Reading mode**

![스크린샷 2024-08-23 오후 10 09 23](https://github.com/user-attachments/assets/818bc03d-b842-46eb-a32a-998d6d1eb780)

### Describe the solution you'd like

First of all, I would like to apologize as I'm not a major in a related filed(such as Computer Science or Development). However, I wanted to bring to your attention a visual issue I've encountered in reading mode with the Kanban Callout. Please find the attachments that demonstrate this issue.

As a web novel writer in Korea, I have been customizing my Obsidian template, and I'm truly amazed by your astonishing work. I would be grateful if you could take a look at this and guide me on how to resolve the problem.

Thank you for your time and support!

**Comment by SlRvb** [comment]
Could you paste the text in your note to make this? I feel like this might be text formatting issue based on reading mode issues. 

Either paste it exactly in a codeblock here or drop a stripped down version of the file here so I could see the potential issues.

**Comment by HonorableEmperor** [comment]
```
> [!kanban]+ 
> - ㅤ<center><h1>원고</h1></center>
>    - ![[paper2.gif]] 
>    - [[1. 원고 대시보드.canvas|대시보드 바로가기]] 
> - ㅤ<center><h1>캐릭터</h1></center>
>    - ![[character.gif|wmed]] 
>    - [[2. 캐릭터 대시보드.canvas|대시보드 바로가기]] 
> - ㅤ<center><h1>플롯</h1></center>
>    - ![[plot.gif]] 
>    - [[3. 플롯.canvas|캔버스 바로가기]] 
> - ㅤ<center><h1>노트</h1></center>
>    - ![[note.gif|wmed]] 
>    - [[4. 노트.canvas|캔버스 바로가기]] 

```

**Comment by SlRvb** [comment]
Weird... even when I paste the code it seems to work alright on my end in reading. 
![Obsidian_uiNhXZO4aD](https://github.com/user-attachments/assets/fcb53a69-bd1b-4615-91e3-1678568bd84a)

So I'm not sure why it's broken unless something else in your note is causing issues and causing the syntax to not be read. Seems like maybe a horizontal line is too close or maybe something else? If you have the kanban callout alone in a note does the same thing happen?

**Comment by SlRvb** [comment]
If you have any additional information to help recreate this and if it's still an issue, feel  free to reopen this issue.
