### ISSUE TITLE
[Bug] Dataview checkboxes cut off

### ISSUE THREAD

**Issue by irodionzaytsev** [SlRvb/Obsidian--ITS-Theme#332]
In Dataview (Tasks) query, the checkboxes are cut off (see picture). 
![ITS](https://github.com/user-attachments/assets/28ab5a13-cc9d-41db-9a35-ebe54f4ccfe3)

Expected behavious:
checkboxes should appear properly - as squares, not being cut off on the left.

**Comment by SlRvb** [comment]
Sorry, could you refill out the bug template with extra info on there to help me recreate it? Thanks.
