### ISSUE TITLE
[Bug] Callouts not displayed correctly in reading mode

### ISSUE THREAD

**Issue by irodionzaytsev** [SlRvb/Obsidian--ITS-Theme#333]
In reading mode, the callout gets jumbled up and pulled to right. See pictures below
![Screenshot from 2024-09-06 09-32-47](https://github.com/user-attachments/assets/d5755562-6dcb-4b05-bcf1-c99282bef572)
![Screenshot from 2024-09-06 09-33-23](https://github.com/user-attachments/assets/7705f1a7-f11e-42b1-af25-3ddb431fd2f6)

**Comment by SlRvb** [comment]
That is correct behavior, if you dont want it to float to the right add `|sban` to the callout
