### ISSUE TITLE
[FR] How to use colorful folder style

### ISSUE THREAD

**Issue by Leiyi548** [SlRvb/Obsidian--ITS-Theme#334]
### Is your feature request related to a problem? Please describe.
I want colorful folder style

### Describe the solution you'd like

look picture

![image](https://github.com/user-attachments/assets/12ec4ead-5b3a-4b43-8128-506e2bc815bd)

**Comment by SlRvb** [comment]
https://publish.obsidian.md/slrvb-docs/ITS+Theme/Folder+Styles
