### ISSUE TITLE
[Bug] Bullet lists alignment different between preview and edit mode

### ISSUE THREAD

**Issue by jonilaserson** [SlRvb/Obsidian--ITS-Theme#335]
### Describe the bug
Bullet list alignment is different between preview and edit mode.

**Expected behavior**
Both alignments should be the same (and if writing in a RTL language - to the right).

### To Reproduce
1. Use the WOTC/DND Beyond style 
2. Create a new note
3. Start typing a list with "- " and then write something in Hebrew (like "אייטם")
4. Switch to reading mode

### Screenshots
Edit mode:
![image](https://github.com/user-attachments/assets/3797eb85-bd61-4061-ac0f-b42db7578c2a)
Preview mode:
![image](https://github.com/user-attachments/assets/858b4561-ae14-4eba-bd72-5e78c5058f21)

### Mode
- [ ] Source Mode
- [ ] Live Preview
- [x] Reading Mode

### OS
Windows
- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.6.7
- ITS Theme Version: don't know where it is
- [ ] Using ITS Snippet: 

### Additional context
Workaround: If I toggle on `Lists->Default Bullet Disc Shape`, it is aligned correctly.

**Comment by SlRvb** [comment]
Should now be fix in ITS v1.3.25, thanks for letting me know!

**Comment by jonilaserson** [comment]
Thank you!
