### ISSUE TITLE
[FR] Folder Arrows Always Visible Option

### ISSUE THREAD

**Issue by Husselbeh** [SlRvb/Obsidian--ITS-Theme#337]
### Describe the solution you'd like
Folder Arrows option for always visible instead of 'hover' being the only option. They shouldn't replace the typical folder icon though. 

### Describe alternatives you've considered
I've tried searching for some CSS code to provide what I'm searching for but sadly can't find anything. 

### Additional context
What I have:
![image](https://github.com/user-attachments/assets/3b95a026-e2ef-4fe6-b174-ee621e07f928)
What I would like (From an older YT Video by JoshP):
![image](https://github.com/user-attachments/assets/2e1b1e49-a522-46b6-ae13-f6eca7a1c21f)

Thank you for reading, regardless of whether or not you decide to add this. 
Loving ITS as a new obsidian user so thank you!

**Comment by SlRvb** [comment]
Should be available now in v1.3.17! Under Style Settings Workspace > File Explorer > Folder Arrows. Set that to display and that should work.
