### ISSUE TITLE
[Bug] `hr` Bolt decoration scrolls with page in Community Plugins' readme

### ISSUE THREAD

**Issue by damiankorcz** [SlRvb/Obsidian--ITS-Theme#339]
### Describe the bug
Same as title. Also, I think it's supposed to be centered.

**Expected behavior**
The decoration stays with the HR and is centered.

### To Reproduce
Easy way to see it is go to Community Plugins and look at the Tasks plugin (as shown in the video below).

### Screenshots
[simplescreenrecorder-2.webm](https://github.com/user-attachments/assets/cdc59d4a-0816-4547-a061-8ef2f54d40f0)

### Mode
In the Settings -> Community Plugins' Readme preview.

### OS
- [x] Desktop

### Versions
- Obsidian Version: 1.7.3
- ITS Theme Version: 1.3.16
- [ ] Using ITS Snippet:

**Comment by SlRvb** [comment]
Should be fixed now in ITS v1.3.28. There's no way I know to fix it other than to disable it, but thanks for letting me know!
