### ISSUE TITLE
[Bug] Dim option (snippet) not working

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#341]
Hi. I think the dim and dim-hvr options for callouts are not working correctly. I tried hovering over them in multiple combinations e.g. with + sign, with - sign with no sign, in editing and reading mode, but nothing seems to happen, or maybe I am doing something wrong. 
![callout_bug](https://github.com/user-attachments/assets/7e8150d5-06f6-429d-9787-2e870377c255)
I tried it in my normal vault and in sandbox and got the same results. I am using the lates snippet version, and obsidian 1.7.3
Thanks for reading.

**Comment by SlRvb** [comment]
Should be fixed now! Do update your and check out the updated docs on the `dim` options.

**Comment by albertoloscerritos** [comment]
Awesome, thanks 👍
