### ISSUE TITLE
[FR] Option like slim-margin but for row gaps

### ISSUE THREAD

**Issue by albertoloscerritos** [SlRvb/Obsidian--ITS-Theme#343]
Hi. I hope you are having a great day. 
I think one option that would be very handy, would be the option to reduce the row gap between callouts inside columns. At the moment `slim-margin` allows us to do this but only for column gaps:
![image](https://github.com/user-attachments/assets/ab01bff9-aa15-483f-892b-caa78f7c48f3)
But having the option to do this for row gaps too would allow us to have very nice-looking grids of callouts, just by reducing the gap:
![image](https://github.com/user-attachments/assets/9c538e67-5938-46e9-8314-66c9f386d011)

Thanks for reading :)

**Comment by SlRvb** [comment]
Should now be fixed if you update your callout snippet!

**Comment by albertoloscerritos** [comment]
Thank you so much for the awesome work 👍 
Have a great day.
