### ISSUE TITLE
[Bug] Callouts inherit the title color from the level above

### ISSUE THREAD

**Issue by Nydid** [SlRvb/Obsidian--ITS-Theme#344]
### Describe the bug
When nesting callouts with the `bg-c-[color]` code, I noticed the titles do not style properly. They do not behave in the same way for each color (eg. Black styles every title black, Purple styles most but not all, Blue styles correctly, etc)

![image](https://github.com/user-attachments/assets/35cb5210-5c8e-44e4-a455-1bfbc74e2138)

**Expected behavior**
I expected the individual callout's colors to be respected when nested, like the currently (supposedly) working Blue
![image](https://github.com/user-attachments/assets/61dd515e-a745-44a6-8978-eff4412c7224)

### To Reproduce
1. Create a nested callout structure
```
> [!cite|no-icon bg-c-white]- `bg-c-[color]`
> 
> > [!example|no-icon callout-block bg-c-purple] Purple Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-blue] Blue Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-green] Green Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-red] Red Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-pink] Pink Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-orange] Orange Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-yellow] Yellow Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-gray] Gray Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-brown] Brown Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-black] Black Title
> > Content
> 
> > [!example|no-icon callout-block bg-c-plain] Plain Title
> > Content
> 
```
2. Change the topmost level's `bg-c` color
3. See changes

### Screenshots
![image](https://github.com/user-attachments/assets/12b14012-cb51-44d0-b99e-c831cfd734b1)
![image](https://github.com/user-attachments/assets/1da4a5d8-0181-4f82-bb1f-a77f12ee73c1)
![image](https://github.com/user-attachments/assets/61dd515e-a745-44a6-8978-eff4412c7224)

### Mode
What mode(s) does the bug occur? Select all that apply.

- [ ] Source Mode
- [x] Live Preview
- [x] Reading Mode

### OS
Where does the bug occur?

- [x] Desktop
- [x] Mobile

### Versions
- Obsidian Version: 1.7.4
- ITS Theme Version: N/A
- [x] Using ITS Snippet: Latest (Last commit Aug 30, 2024)

### Additional context
None

**Comment by SlRvb** [comment]
Ah shoot, should be fixed on ITS v1.3.23, thanks for catching this!
