### ISSUE TITLE
[Bug] Default no-window-frame will cause the right sidebar to have its icons overlap with the maximise/minimise/exit buttons

### ISSUE THREAD

**Issue by Rose7002** [SlRvb/Obsidian--ITS-Theme#346]
### Describe the bug
The icons of the right sidebar overlap with those of the window itself. In the default theme these icons become covered by an overlay of sorts that prevents them being interacted with; this is not the case here. It also prevents scrolling sideways to click icons without pressing maximise/minimise/exit.

**Expected behavior**
Overlay prevents the icons from being interacted with and allows scrolling

### To Reproduce
1. Go to Sandbox Vault
2. Install ITS Theme
3. change vault windowframe display mode to Hidden if it isn't already

### Screenshots
![image](https://github.com/user-attachments/assets/2be1fc9a-8b71-4dff-b2d8-0b6a90ce556c)

### Mode
What mode(s) does the bug occur? Select all that apply.

- [x] Source Mode
- [x] Live Preview
- [x] Reading Mode

### OS
Where does the bug occur?

- [x] Desktop
- [?] Mobile

### Versions
- Obsidian Version: 
- ITS Theme Version: 1.3.24
- [ ] Using ITS Snippet:

**Comment by SlRvb** [comment]
Should be fixed now on ITS v1.3.25
