### ISSUE TITLE
[Bug] Timeline Callout not working (Snippet)

### ISSUE THREAD

**Issue by EvilsSouls** [SlRvb/Obsidian--ITS-Theme#349]
### Describe the bug
When using the The Timeline Callout does not produce a clear continuous line going down.

**Expected behavior**
When using the Timeline Callout it should produce the same result, as in the Documentation. This, however, is not the case.

### To Reproduce
1. Put the Callout Adjustment Snippet inside the Snippets folder and enable it
2. Make multiple timeline callouts
3. Observe the line not connecting

### Screenshots
![image](https://github.com/user-attachments/assets/325b5c7c-e6b0-4b6a-89c0-179853f51061)
![image](https://github.com/user-attachments/assets/281603ae-d96a-46ed-a85e-3657fc044bb4)

### Mode
What mode(s) does the bug occur? Select all that apply.

- [ ] Source Mode
- [x] Live Preview
- [x] Reading Mode

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: 1.7.6
- ITS Theme Version: 
- [x] Using ITS Snippet: Newest

**Comment by SlRvb** [comment]
Hmm, I can't recreate this. It seems to still be connecting together on my end as expected which is only in reading mode.

![Obsidian_XpI2HEEvFX](https://github.com/user-attachments/assets/cf630180-9d5a-4319-b808-30ebefdb1631)

```
> [!timeline|t-l c-orange] **Title** _Subtitle_
> Left aligned timeline piece

> [!timeline|t-r bg-c-red] **Title** *Subtitle*
> Right aligned timeline piece


> [!timeline|t-l bg-c-green]+ **Title** _Subtitle_
> Left aligned timeline piece

> [!timeline|t-r t-2]+ **Title** *Subtitle*
> Right aligned timeline piece
```

**Comment by EvilsSouls** [comment]
> Hmm, I can't recreate this. It seems to still be connecting together on my end as expected which is only in reading mode.
> 
> ![Obsidian_XpI2HEEvFX](https://private-user-images.githubusercontent.com/54087190/391207288-cf630180-9d5a-4319-b808-30ebefdb1631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjY1NzgsIm5iZiI6MTczMjk2NjI3OCwicGF0aCI6Ii81NDA4NzE5MC8zOTEyMDcyODgtY2Y2MzAxODAtOWQ1YS00MzE5LWI4MDgtMzBlYmVmZGIxNjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDExMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NmY2Njc5ZmJmZGZiMTZlMzYzNmQ2MWU1M2M1NTc4ZjBiNmY2YTcxYjU1ZGM3ZjM0OTdkNTgwN2NkMTA1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kVO_EJrhPdfTQHxpvnMB8n4JQPEvGrm3ntDDrkw9Iao)
> 
> ```
> > [!timeline|t-l c-orange] **Title** _Subtitle_
> > Left aligned timeline piece
> 
> > [!timeline|t-r bg-c-red] **Title** *Subtitle*
> > Right aligned timeline piece
> 
> 
> > [!timeline|t-l bg-c-green]+ **Title** _Subtitle_
> > Left aligned timeline piece
> 
> > [!timeline|t-r t-2]+ **Title** *Subtitle*
> > Right aligned timeline piece
> ```

I just checked in the Sandbox Vault and realized, that it was a problem with an existing snippet I had installed. I don't know why I hadn't assumed to check that first, as that is the most obvious first place to check. Sorry for the confusion.

PS: The Snippet I was using was CyanVoxel's General Tweaks Snippet, which apparently changes the shape of the Callouts to be rounded.
