### ISSUE TITLE
How can I change the Squared Bullet points to the normal bullets

### ISSUE THREAD

**Issue by vkbytes** [SlRvb/Obsidian--ITS-Theme#4]
I like the square bullets, I'd like to know how can get just the normal rounded bullet points?

**Comment by vkbytes** [comment]
I think I figured it out I commented the line below
```css
grep list-style ITS\ Theme.css
   /* list-style-type: "⬥ ";*/
 ```
Is that the right way for it

**Comment by SlRvb** [comment]
Yeah that will remove the bullet style. Add this in a snippet so it won't be overwritten in the next update:
`li { list-style-type: disc; }`
`ul ul::before { left: -14px; }`

**Comment by vkbytes** [comment]
Thanks @SlRvb This was really helpful. Its an amazing theme. Thank you for making it.
