### ISSUE TITLE
checkbox bug

### ISSUE THREAD

**Issue by 98YuGan** [SlRvb/Obsidian--ITS-Theme#40]
hello , thanks for your ITS.it's so beautiful. but,
In the synchronization function, excluded folders cannot be displayed normally, and the selected and unselected contents cannot be distinguished. I hope you can change this part of the code.

this is my changed
```
 /*Table Checkboxes*/

input[type="checkbox" i] {
    background-color: white;
    -webkit-appearance: none;
    box-sizing: border-box;
    border: 1px solid var(--accent);
    border-radius: var(--radius);
    position: relative;
    width: 15px;
    height: 15px;
    margin: 0;
    filter: none;
    outline: none;
    margin-top: auto;
    margin-bottom: auto;
    cursor: pointer;
}

input[type="checkbox" i]:checked {
    background-color:red;
    -webkit-appearance: none;
    box-sizing: border-box;
    border-radius: var(--radius);
    position: relative;
    width: 1.3em;
    height: 1.3em;
    margin: 0, 0, 0, 0;
    filter: none;
    outline: none;
    border: none;
```

**Comment by SlRvb** [comment]
Hmm, I think I fixed it. Is this what you meant? The sync folders checkbox should now check properly:
![Obsidian_t43exnHpRQ](https://user-images.githubusercontent.com/54087190/139958474-e9b47594-2fb7-471a-aeeb-afefb3fcaf03.png)

Hadn't even realized I'd messed that up, whoops.

**Comment by 98YuGan** [comment]
yes，yes。
