### ISSUE TITLE
A few bugs 

### ISSUE THREAD

**Issue by FanDannn** [SlRvb/Obsidian--ITS-Theme#42]
Sorry to submit this issue twice. I just created a discussion, but maybe it's better to submit here as an issue.

First, thank you for your excellent theme! I really love it.

There are a few bugs to feed back:
1. ITS Theme performs almost as perfectly on android, but the mind map plugin fails to show titles and words on each node under this theme, both in the bright and dark modes.
2. In bright mode, the Music notation plugin almost fails to show anything in preview mode, except for several white shadows. Yet it works well in the dark mode. This issue occurs both on mac desktop and android.

Thanks again! Looking forward to improvements.

**Comment by SlRvb** [comment]
Sorry this took so long to address. I believe I fixed `#2` and have pushed an update for it. But for `#1` do you have an example file that you can send over to me so I can test out what's going on with the mindmap plugin?

Also is this the James Lynch plugin or another mindmap plugin?

**Comment by FanDannn** [comment]
> Sorry this took so long to address. I believe I fixed `#2` and have pushed an update for it. But for `#1` do you have an example file that you can send over to me so I can test out what's going on with the mindmap plugin?
> 
> Also is this the James Lynch plugin or another mindmap plugin?

Thanks, I'm so glad to see your reply and update! `#2` has been fixed on Mac exactly but not on Android.
![music notation on Mac](https://user-images.githubusercontent.com/37014400/140014867-68d26bdc-0051-41ba-a89b-1237e1058d5d.png)
![music notation on Android](https://user-images.githubusercontent.com/37014400/140014882-6f7dfc9a-7a18-4b30-b595-bfb63ed1de43.jpeg)

Anyway, I believe it is already enough for common use. Thanks a lot.

For `#1`, yes it is the James Lynch plugin. I wrote a simple file "Outline Test.md" , you can see the file and the performances below.
[Outline Test.md](https://github.com/SlRvb/Obsidian--ITS-Theme/files/7465569/Outline.Test.md)
![Outline Test on Mac](https://user-images.githubusercontent.com/37014400/140015197-c56b1464-b0c9-4df5-94e7-3843006283ab.png)
![Outline Test on Android(bright)](https://user-images.githubusercontent.com/37014400/140015212-1227b678-bdfd-4999-a6e6-e7eb9837ea37.jpeg)
![Outline Test on Android(dark)](https://user-images.githubusercontent.com/37014400/140015219-f7d9bd51-90ad-44cd-bd60-951319d6a649.jpeg)

BTW, it may not be a bug but, I found it somehow hard to see the texts clearly when editing under bright mode. Then I realized that texts in ITS theme was lighter or, say, gray rather than black after comparing to other themes. Is it that I missed some button in the 'Style Settings' plugin?

**Comment by SlRvb** [comment]
The strange thing is that I can't seem to replicate the text disappearing for mindmap or the music sheet disappearing on android, they both seem to show up consistently for me 🤔 

---
Yeah the text is a gray instead of black, you can change the text color in the style settings to full black if that's easier to read.

In the newer update it should be under `Colors > Text > Text`.

**Comment by FanDannn** [comment]
> The strange thing is that I can't seem to replicate the text disappearing for mindmap or the music sheet disappearing on android, they both seem to show up consistently for me 🤔
> 
> Yeah the text is a gray instead of black, you can change the text color in the style settings to full black if that's easier to read.
> 
> In the newer update it should be under `Colors > Text > Text`.

Hhhh that's weird. Thanks for your patient reply and debugging. 

 My apology. Possibly because of the differences in os lol. I suddenly realize that my mobile os is not android anymore. I was too careless in seeing Harmony os as android due to its look and compatibility with android apps. Anyway, I believe your theme is already perfect on desktop and mobile devices, and these bugs are not that crucial for common use.

And I have changed the text colors and it works pretty well. I can no longer leave ITS theme now lol.
Thanks again!

**Comment by SlRvb** [comment]
If this is still an issue, feel free to re-open this issue 🙏🏽
