### ISSUE TITLE
[BUG] Error in the style of the ordered list

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#45]
![image](https://user-images.githubusercontent.com/30563826/139570795-a1306aaf-93c2-48b2-aca4-e4259efea01c.png)

Something is wrong with the style of the ordered list

**Comment by SlRvb** [comment]
Ah yeah I noticed that too, I've pushed a new commit that should fix that.

**Comment by Borber** [comment]
> Ah yeah I noticed that too, I've pushed a new commit that should fix that.

it fixed!
