### ISSUE TITLE
Please provide a default matching font for D&D WOTC~

### ISSUE THREAD

**Issue by Sunny-27** [SlRvb/Obsidian--ITS-Theme#46]
D&D WOTC is Great！Can I get a default matching font for it? 
I would like to get more colour schemes with parchment as the base colour！

**Comment by SlRvb** [comment]
Yeah I'll be adding the font into the file and in an update I should let the whole Alt Themes snippet be far more customizable so you can apply the parchment aesthetic on top of other stuff 🤔 

Just a bit preoccupied at the moment so I can't push out updates and fast as I'd like 🙈

**Comment by Sunny-27** [comment]
> Yeah I'll be adding the font into the file and in an update I should let the whole Alt Themes snippet be far more customizable so you can apply the parchment aesthetic on top of other stuff 🤔
> 
> Just a bit preoccupied at the moment so I can't push out updates and fast as I'd like 🙈

Thanks！！！！！！

**Comment by SlRvb** [comment]
I've updated and embedded the fonts in the alternate theme snippet, so if you download it again it should all show up now.

**Comment by Sunny-27** [comment]
> I've updated and embedded the fonts in the alternate theme snippet, so if you download it again it should all show up now.

OK！Download now！

**Comment by SlRvb** [comment]
I guess this issue is solved, so I'll be closing this. Feel free to reopen it if there's any issues.
