### ISSUE TITLE
 In a checkbox line, the trailing parentheses does not match the leading parentheses.  Live Preview  vs  Preview

### ISSUE THREAD

**Issue by paulsp** [SlRvb/Obsidian--ITS-Theme#49]
v0.13.4 In a checkbox line, the trailing parentheses does not match the leading parentheses.  Live Preview  vs  Preview
![Live Preview image](https://user-images.githubusercontent.com/14253472/142935644-c9b2759d-88c8-442f-8932-e1f88a96a40a.png)
![Preview Screen Image](https://user-images.githubusercontent.com/14253472/142935648-f82a2bbd-891c-4b50-b658-e63284d65dee.png)

**Comment by SlRvb** [comment]
Licat has added some options for styling that might help fix this problem in the next insider update, so I'll see what I can do when that comes out. So thanks for bringing this up!

**Comment by SlRvb** [comment]
Sorry this took so long, but I think I've fixed this issue in the new update f8de8b0

**Comment by paulsp** [comment]
Looks good.
Thank you
