### ISSUE TITLE
Subfolders do not expand/contract when used with AidenLx's Folder Note

### ISSUE THREAD

**Issue by MLRichmond** [SlRvb/Obsidian--ITS-Theme#51]
The latest update to the theme is incompatible with AidenLx's Folder Note.

Top level folders still function correctly, but sub-folders no longer expand or contract in the explorer view.

Deactivating AidenLx's or switching to another theme both resolve the issue.

**Comment by MLRichmond** [comment]
After a bit more review, I'm not sure this is related to any recent change. I tried going back several revisions and it is broken in all of them.

![image](https://user-images.githubusercontent.com/22899933/146114978-82089155-9ba6-4635-9fe5-70b399c87f7c.png)

If you click on the very, very edge of the row, you can still expand and collapse the row. This leads me to believe that there is something from the theme that is sitting on top of the clickable element from AidenLx's Folder Note and obstructing it.

**Comment by MLRichmond** [comment]
Ok - I've identified the issue. 

`.nav-folder-title-content,
.nav-file-title-content {
    width: 100%;
    line-height: 20px;
}`

The width 100% used to move file extensions to the end (looks nice, btw) causes the row to be width 100%, which obstructs the clickable element from Aiden's.

Double check me but I think the fix is as simple as this:
`/*Move File Extension to Right*/
.nav-file-title-content {
    width: 100%;
    line-height: 20px;
}
body:not(.type-undo) .nav-file-title {
    flex-direction: row-reverse;
}

/* Nav folder line height */
.nav-folder-title-content{
    line-height: 20px;
}`

**Comment by SlRvb** [comment]
Oooh, now that's interesting. I'll load up that folder note plugin and see what I can do to fix it right off the bat since it seems like a lot of new ttrpg folks are coming around and it's not quite obvious what the fix is.

For some, I've mentioned that the Style Settings toggle: `Display The Folder Arrow On Hover` under `Workspace` should fix being unable to open/close the folder. Does that work for you?

**Comment by SlRvb** [comment]
Okay, I've added the ability to auto display the folder arrow when hovering over the folder that has a folder note in it in the new commit: 981508a

**Comment by MLRichmond** [comment]
The fix does work - but it rendering the arrow causes some pop-in with the row. The fix I proposed allows you to click the row anywhere outside of the text to expand/collapse which is how it works in other themes. 

This is usable, but I prefer the other personally. Does the width change cause issues elsewhere that I didn't notice?

**Comment by SlRvb** [comment]
Hmm, fair enough. That is definitely nicer visually and in terms of usability. I've added that to the newest commit so it should work now. 👀

**Comment by MLRichmond** [comment]
Works great! Thank you!
