### ISSUE TITLE
colorful list failure to perform in live preview mode

### ISSUE THREAD

**Issue by windily-cloud** [SlRvb/Obsidian--ITS-Theme#52]
obsidian version: v0.13.14
theme version: latest (2021-12-29 update)

I tried turning on safe mode and setting it via style settings, but both failed. When I turn on "use legacy editor", the vertical line in front of the list is displayed normally. 

now:
![image](https://user-images.githubusercontent.com/30640638/147639615-995baca3-f41c-454c-baf9-b6619c8c410f.png)
previous:
![image](https://user-images.githubusercontent.com/30640638/147639716-62261b83-f35f-4c52-b1b1-0327a95b54ba.png)

What can I do to use the vertical line list in live preview mode, colorful lists may be better !

**Comment by SlRvb** [comment]
I think I might have to add murfs rainbow list snippet to my theme 🤔

**Comment by windily-cloud** [comment]
ITS is the most practical and beautiful theme I've come across so far, and there are such understanding and nice developers, I've also seen your "Journal vault", it's very beneficial, thank you very much for your work. I hope I can be like you in the future. 😊

**Comment by SlRvb** [comment]
I've pushed an [update](fe401d295aa80701424eb4711f897d871963298d) which should bring the lines "back" for cm6. It's a temporary fix for now, there's also a new slider to help adjust the lines if your bullet lists don't match up to the default. 

It's under `Note Elements > Lists > Murf's Rainbow Line Spacing`

**Comment by windily-cloud** [comment]
Thank you very much, but I don't seem to be displaying it properly here.

env: safe mode, without any CSS snippets, default style settings
![image](https://user-images.githubusercontent.com/30640638/147802833-9688eb27-a24d-477f-bda9-137e31a17932.png)

So I modified the corresponding values a little bit to have the following effect:

env: add a CSS snippets
```CSS
.markdown-source-view.mod-cm6 .list-bullet{
  padding-right: 0px;
}
.HyperMD-list-line.cm-line .cm-hmd-list-indent::before, .mod-cm6.is-live-preview .HyperMD-list-line.cm-line .cm-hmd-list-indent::before{
  left: 16px;
}
```
![image](https://user-images.githubusercontent.com/30640638/147802933-311c1ba0-a0b8-4a00-ae6d-cdecbb46eb51.png)

In addition, the original bullet line in the style settings seems to conflict：

env: open original bullet line option in style settings

![image](https://user-images.githubusercontent.com/30640638/147803111-941bd7c8-3ed9-45a8-93f2-9c8164971d48.png)

Thanks again！

**Comment by SlRvb** [comment]
Strange, I can't seem to recreate either errors. 

Those bullets in your first screenshot look quite unusually spaced _really_ far out from the side and the text which is very strange, and the original bullet line hides the border for the list like it should on my end 🤔

**Comment by windily-cloud** [comment]
Then let's leave it like this for now, I'll find it out after my exams. Thank you for your kind help! Happy New Year!😆

**Comment by windily-cloud** [comment]
> Then let's leave it like this for now, I'll find it out after my exams. Thank you for your kind help! Happy New Year!😆

When I upgraded the installer to the latest, all problems were solved, happy!
