### ISSUE TITLE
Content of li::before is not shown

### ISSUE THREAD

**Issue by lanice** [SlRvb/Obsidian--ITS-Theme#53]
In list items that have a content within their `::before` elements, that content is not shown. There is however additional whitespace where the content would be. This can easily be reproduced with the [cooklang plugin](https://github.com/deathau/cooklang-obsidian), using one of the [cooklang example recipes](https://github.com/cooklang/spec/tree/main/examples).

How the "Steps" are displayed with the default theme:
![cooklang-default](https://user-images.githubusercontent.com/1871704/147820724-1f485ada-cae5-49d0-bff5-0e550b92d6b6.png)

How they are displayed with the ITS theme:
![cooklang-its](https://user-images.githubusercontent.com/1871704/147820733-24613bbd-1f09-43e3-a235-888bfecad34c.png)

**Comment by SlRvb** [comment]
I think I've pushed out a fix for this, can you update and see if the words come back?

**Comment by lanice** [comment]
Yes it works now, thank you so much!!! 🥳
