### ISSUE TITLE
Blockquotes in Obsidian Slides

### ISSUE THREAD

**Issue by Craftidore** [SlRvb/Obsidian--ITS-Theme#55]
I love the ITS Theme, and use it with my RPG Vault. However, I was testing out the Obsidian Slides plugin, planning to use it for my intro session this week, and I spotted this:

```markdown
> **Session 0 is a planning session where the gaming group collaboratively lays the groundwork for a new campaign** 
> <cite style="float:right;"> [Cyrad, RPG.StackOverflow.com](https://rpg.stackexchange.com/a/105431/62592) </cite>
```

**File in Reading View:**
![image](https://user-images.githubusercontent.com/73705352/147982883-dcd9a7b5-96b6-4139-8a96-9b52aec86816.png)

**Obsidian Slides:**
![image](https://user-images.githubusercontent.com/73705352/147983064-ca59545f-f776-4c3f-a27a-9be126e433b9.png)

This isn't exactly a _bug_, but I find the blockquote styling for Obsidian Slides to be… disappointing—I wish it looked more like it does in Reading View. 

I'll try to test out other markdown syntax in Slides to see if it displays noticeably different, and update this issue with it.

**Comment by SlRvb** [comment]
Ah shoot, nice catch! [Fixed](7d0a324) the links and blockquote I believe.
