### ISSUE TITLE
Center Header With Lines not centering

### ISSUE THREAD

**Issue by Craftidore** [SlRvb/Obsidian--ITS-Theme#56]
In Style Settings, the 'Center Headings With Lines' doesn't center the headings. In fact, when the Center Headings is on, Center Headings  With Lines disables the centering.
![image](https://user-images.githubusercontent.com/73705352/148272765-e36c8f67-8fa8-4f9c-a2ce-9d27558d5451.png)
![image](https://user-images.githubusercontent.com/73705352/148272688-06779218-ebc7-4d00-81f0-3b89d35992dc.png)

**Comment by SlRvb** [comment]
I'm not sure if I fixed this recently, but I can't seem to recreate this issue 🤔 

Try updating the theme to see if I fixed this or if something else is messing this up.

**Comment by SlRvb** [comment]
Not sure if this is still an issue or not. If it is, do feel free to reopen and let me know.
