### ISSUE TITLE
Is there a way to prioritize heading color over link color?

### ISSUE THREAD

**Issue by onnyyonn** [SlRvb/Obsidian--ITS-Theme#57]
If a heading contains an internal link, it inherits the color of links, not the heading. Is there an option to prioritize the heading color instead?

**Comment by SlRvb** [comment]
I've added a toggle for this in the [newer commit](b4fe675).

It can be found under: `Note Elements > Headers > Header Color Override`.

**Comment by onnyyonn** [comment]
Thanks for the quick fix, and it works. By the way, overriding it only sets it to the color set as `Colors > Text > Headings`. I have set separate colors for each headings in `Text > Specific View Heading Changes > Heading Colors`. Is it possible to incorporate those?

**Comment by SlRvb** [comment]
I've added support for that in this commit 4061ef8, should do what you want now :)

**Comment by onnyyonn** [comment]
Thank you. Working as expected.
