### ISSUE TITLE
Live Preview bug

### ISSUE THREAD

**Issue by stepfire** [SlRvb/Obsidian--ITS-Theme#58]
With the latest update, I can't change the text in Live Preview if I have a picture with side alignment attributes along with the text.

**Comment by SlRvb** [comment]
Yep this has been something I've been meaning to fix. I'll have to disable Image and Embed Adjustments for live preview to fix this.

**Comment by SlRvb** [comment]
I've fixed the css to avoid this issue floating right or left in live preview messes with cursor calculations, so I've disabled left and right completely in this commit: 0816f417f458ec002b7b08d9c4e714c052e8fbbe

Update the theme and I believe you should no longer have problems with text.
