### ISSUE TITLE
Nord alternate theme breaks horizontal line symbol and only shows a square

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#59]
When using the alternate theme Nord, I see that the symbol for the horizontal line is set to the default thunderbolt icon.

However, I only see a square. Switching to another alternate theme displays it correctly.

**Comment by SlRvb** [comment]
The icon for Nord uses an encoded icon font. Just checking, do you have [this snippet](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/S%20-%20Encoded%20Icons.css) installed?

**Comment by stecydube** [comment]
Doh! Somehow must have misread the docs.

Thank you!

**Comment by SlRvb** [comment]
No worries! Glad it works now.

I need to update the Readme docs anyway so this will be on my list of things to update/fix 🙈
