### ISSUE TITLE
Checkboxes in admonitions don't render

### ISSUE THREAD

**Issue by VeroVerro** [SlRvb/Obsidian--ITS-Theme#64]
Hi, thanks for this wonderful theme again :) I'm having a bit of a problem with checkboxes in admonitions though - they render in default theme, but not in ITS theme:

![image](https://user-images.githubusercontent.com/17042871/150197763-773b90d3-220a-48d8-808a-54a4b01eac70.png)

![image](https://user-images.githubusercontent.com/17042871/150197801-9c5aac04-a640-4f44-8aaa-8c23190c43df.png)

It's the same whether I use the theme as is without any snippets or style settings, or whether I use admonition and / or checkboxes snippets.

They render fine in reading mode, the previous screenshots are from live preview in editing.

**Comment by SlRvb** [comment]
I think I've pushed a fix for that here:  1a73d42. Do let me know if it works 🙂

**Comment by VeroVerro** [comment]
Thanks! :) 

It mostly works :D The alternate checkboxes work, but an empty one (`- [ ] test`) doesn't, and for the regular x, only uppercase shows up (so `- [X] test` is good, `- [x] test` is not).

**Comment by SlRvb** [comment]
Can you update one more time? I believe I should have fixed that 🤔

**Comment by SlRvb** [comment]
Ah, that's great to hear. Glad it's working now. 🥳
