### ISSUE TITLE
Enabling "Center Heading with lines" removes spaces around internal link

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#65]
Using the Style Settings plugin along the ITS theme.

Enabling the "Center Heading with lines" option under
- In The Shadows Settings
  - Note Elements
    - Headers

All the headings having an internal link have no spaces around the link

`# This is a [[Test]] Here`

results in

`This is aTestHere`

when rendered.

### OS
Where does the bug occur?

- [x ] Desktop
- [  ] Mobile

Obsidian Version:
0.13.19

**Comment by SlRvb** [comment]
I think I've somewhat fixed this. It's a bit tricky to get the spacing correct for the end of the spacing with the last line since flex objects don't really allow padding for stuff like this. 

Hopefully when you update the theme, this is close enough though 🙂

**Comment by stecydube** [comment]
It works beautifully now! Thank you very much! 😀
