### ISSUE TITLE
Footnote does not jump to the bottom

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#66]
### Describe the bug
When I click on the footnote, it does not jump to the references at the bottom as it should. Though, it does jump back up when I return from the references.

**Expected behavior**

It should scroll/jump all the way down to the bottom & at exact location.

### To Reproduce
1. Create 'Footnote'
2. Click on 'Footnote'
3. It scrolls down halfway, especially in a long file

### Screenshots

Footnote [1] & [2] in the 3rd line
![2022-02-03 at 05 49 55 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/152459511-30247597-ed52-468e-a5bc-618e574bbd50.jpg)

When I click on either [1] or [2], it scrolls down just halfway not all the way to the bottom references
![2022-02-03 at 05 50 02 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/152459592-39d52ed4-64e1-459c-b7ca-c277841f7578.jpg)

This is where the location of references at the bottom
![2022-02-03 at 05 50 08 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/152459395-747d1451-c6ed-44b4-9ffb-f9f377f8e6d1.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.13.23

**Comment by SlRvb** [comment]
Hmm, this is very strange. I can't seem to recreate this on my end 🤔

**Comment by Missionary2112** [comment]
> Hmm, this is very strange. I can't seem to recreate this on my end 🤔

Did you try to bring your footnote all the way up to the top in a very long file ? When you click on the footnote, it will jump down halfway.

**Comment by SlRvb** [comment]
Oooh, yep managed to recreate the issue and I think I've pushed out a fix for it 🤔 

Update the theme and do let me know if the issue is fixed or not. Thanks for catching that!

**Comment by Missionary2112** [comment]
Thank you very much for your fixing. I'm a big fan of the theme.

Missionary
