### ISSUE TITLE
Frontmatter with long keyword 

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#67]
### Describe the bug
In YAML - frontmatter, when you use a long keyword, it will cut off and jump down a line. 

**Expected behavior**
Long keywords should still stay in their line without jumping down a line, as expected in default theme.

### To Reproduce
1. Create a YAML
2. Type a long keyword, such as "occupation" 
3. Change to Preview mode

### Screenshots
Error in ITS theme
![2022-02-15 at 05 00 18 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/154176278-08e472af-a4c3-433d-ad27-c58ea620f17c.jpg)

Normal YAML in default theme
![2022-02-15 at 05 00 35 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/154176349-898fe30e-1cfb-41a9-a0c1-dd9607a1ce3e.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.13.24

**Comment by SlRvb** [comment]
I've reverted my styling on the frontmatter as it was hacky and prone to errors like these. 

Should look like the default theme's frontmatter now.  c9d3462

**Comment by Missionary2112** [comment]
Thanks a bunch, now it looks fantastic.

Cheers,
Missionary
