### ISSUE TITLE
First emoji not showing correctly in Reading mode for headers

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#68]
Using theme (either regular or nord)

If you use a level 1 header like the following:

`# 🍟 header`

The emoji icon gets squished.

![image](https://user-images.githubusercontent.com/5737502/154568148-66581bb2-9c94-4b20-ae95-e45ad4122276.png)

Go deeper for the heading level (like 5 or 6) and it disappears completely.

![image](https://user-images.githubusercontent.com/5737502/154568232-40c4eac6-08ba-45d5-a7d6-ae3e405d758a.png)

Also, spacing around it is not right when surrounded by spaces in some occasions:

# Header 🍔miam ➡️ pizza

gives

![image](https://user-images.githubusercontent.com/5737502/154568569-e64b6143-99f5-4756-b910-f90fc8eaf503.png)

---

Using Obsidian V0.13.23
ITS Theme, latest as of today but the problem existed before
On Windows 10

**Comment by SlRvb** [comment]
This looks like you've got an emoji plugin installed 🤔

**Comment by stecydube** [comment]
Additional findings. There is clearly a combined effect between a specific style setting and the Emoji Toolbar plugin.

# Editing mode

![image](https://user-images.githubusercontent.com/5737502/154672605-89804827-e850-4c99-ab07-5f0a40d52a14.png)

# Reading mode

ITS theme: default

![image](https://user-images.githubusercontent.com/5737502/154673326-5e4710ac-c1da-4183-876d-a23025c4613e.png)

ITS theme with only setting the "Center heading with lines" enabled:

![image](https://user-images.githubusercontent.com/5737502/154673118-2705fd16-f31b-4248-9505-ce95ee896df7.png)

![image](https://user-images.githubusercontent.com/5737502/154672697-b3b3f7b5-ca7c-4878-92e6-3249b31e8104.png)

Works ok for the "Center headings" option though.

![image](https://user-images.githubusercontent.com/5737502/154673934-07d0ea27-acbb-4fa3-822d-b993ccdc93c9.png)

![image](https://user-images.githubusercontent.com/5737502/154673543-e0c72c7e-92bb-4a22-8b28-79a828879a0b.png)

I just noticed that when "Center headings" is active, the underline does not get centered and that's even with the Emoji plugin disabled.

**Comment by SlRvb** [comment]
Ahh ok, I see the problem for the emoji toolbar, should be fixed now. f7a5643

As far as the regular center heading line not centering, that was intentional, but I guess I can see if I can also fix that 🤔

**Comment by stecydube** [comment]
All fixed.
Found out that emoji don't show in back ticks when used inside a JS code block when the Emoji plugin is active. Not sure it's on your side though.

For example:

````
```js
console.log (`🍪`);
```
````

**Comment by SlRvb** [comment]
I think that's an issue with the emoji toolbar 🤔 Seems to work fine on my vault that doesn't have the plugin installed

**Comment by stecydube** [comment]
It definitely is an issue with the emoji toolbar, tried it with the default theme. Going to raise an issue with their team.
