### ISSUE TITLE
Theme does not respect "Readable line length" core settings

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#69]
I have the "Editor->Readable line length" set to disabled and the notes are still limited on width.

In fact, toggling this setting no longer does anything.

Working fine in default obsidian theme.

On windows, obsidian 0.13.23
Latest ITS theme as of today.

**Comment by SlRvb** [comment]
Oops forgot to target the class to avoid that issue 🤦‍♀️ Should be fixed now though efd70bc

**Comment by stecydube** [comment]
Fixed. Thank you 😀
