### ISSUE TITLE
[FR] - Better table handling

### ISSUE THREAD

**Issue by spiritualgeek** [SlRvb/Obsidian--ITS-Theme#70]
I'd be very appreciative if you'd consider exposing the following to the Style settings plugin:

- A maximum size that any column can be
- font size for `<td>`
- font size for `<th>`
- Options to minimize (or completely remove) padding

Dataview tables should work in the same fashion and this should be consistent between reading view and live preview modes (i.e., look exactly the same)

Thanks for a wonderful theme

**Comment by SlRvb** [comment]
> A maximum size that any column can be

I'm a bit unsure what this would be, do you want css classes to resize specific columns or general style settings options to just have columns span the whole note?

---

> Options to minimize (or completely remove) padding

For `td` and `th` separately?

**Comment by spiritualgeek** [comment]
Maybe my explanation is really horrid :)

- The ability to set the font size for cell content
- The ability to set the font size for heading content
- The ability to set the max width that any column can be. So, a column with long text doesn't destroy the table by squashing all other columns
- The ability to remove padding when it comes to borders, the actual cell etc. So that the maximum amount of text can fit inside the table
- The ability to do the above for dataview and normal tables.

I hope that this makes more sense?

**Comment by SlRvb** [comment]
Ah yep, that clears it up perfectly, thanks! I'll see what I can do 🙂

**Comment by spiritualgeek** [comment]
I keep on coming back to your theme. Thank you for the immense effort you put in to keep these theme fresh and to solve little issues

**Comment by SlRvb** [comment]
> font size for <td>
> font size for <th>
> Options to minimize (or completely remove) padding

So I've managed to do these three 5baba8c3748d84524da7e5457610c875b81719d8, but I'm a bit unsure as of right now how to get max width to work in tables. Not even fully sure max width works in table cells at least in the way you'd want it to work 😔

**Comment by spiritualgeek** [comment]
It seems to work a treat :) I can't seem to find the font sizing though?

This was fast. Thank you so much

**Comment by SlRvb** [comment]
Oops, forgot to commit those changes 🤦‍♀️

I've rearranged some stuff and made the settings a little more visually distinct. Also *actually* added the td and th changes 😅

![Obsidian_ZaGELXPi29](https://user-images.githubusercontent.com/54087190/154914069-2e73c743-1f83-4d17-be71-5f6819cc496a.png)

**Comment by spiritualgeek** [comment]
This works perfectly. Thanks so much!

Just 1 last request. It would be great if it carried across the note text weight.

Or perhaps even had its own :)

Thank you so much. This is outstanding. Highly appreciative.

**Comment by SlRvb** [comment]
> Just 1 last request. It would be great if it carried across the note text weight.

What do you mean? 🤔

**Comment by spiritualgeek** [comment]
If one changes the note text weight to be a bit heavier it has no impact on the text in the table which it should. Otherwise, a separate font-weight just for tables would be good :)

**Comment by SlRvb** [comment]
Oooh, interesting. I hadn't noticed that, will fix for both 👍🏽

**Comment by spiritualgeek** [comment]
.poke :)

**Comment by SlRvb** [comment]
Oops, so I think I've added support for that here under the `Note Elements > Tables` 8f3d8e2bb51684c420405ab29d02a1d24881e5e5

**Comment by spiritualgeek** [comment]
How did I miss that? :) Awesome!
