### ISSUE TITLE
[FR] Ability to change the size of modals

### ISSUE THREAD

**Issue by spiritualgeek** [SlRvb/Obsidian--ITS-Theme#71]
Would you mind introducing the ability to change the width and height of modals?

Thanks!

**Comment by SlRvb** [comment]
Added sliders for that; Under `Workspace > Workspace Resize > Resize Settings Menu Width/Height` 👍🏽 b7b6b91

**Comment by spiritualgeek** [comment]
Awesome. This is perfect 👍
