### ISSUE TITLE
Embedded internal link has dead empty space 

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#72]
### Describe the bug
Embedded internal links expose dead empty space after scroll down within the embedded window. 

**Expected behavior**
When scrolling down an embedded window, it should stop at the end of the file, not expose the dead empty space.
It should behave like in the screenshot below.
![2022-02-24 at 02 03 27 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/155502761-9fe632e4-66a6-4fdb-a164-49683d45ad95.jpg)

### To Reproduce
1. Embed an internal link: `![[...]]`
2. Scroll all the way down to the bottom of the file
3. Scroll back up to the embedded link
4. See error: You would scroll down the embedded link with dead empty space

- It would be more apparent when embedded links at the bottom of a file
- If you keep scrolling up and down so many times, even the small embedded content window without scroll bar extended the dead empty space as well.

### Screenshots
![2022-02-24 at 01 53 44 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/155502507-59897b9e-ed80-416f-8059-7f6cd19084e2.jpg)

### OS
Where does the bug occur?

- [X] Desktop
- [ ] Mobile

Obsidian Version: v0.13.26

**Comment by SlRvb** [comment]
Yeah, that's an issue with obsidian in the new update, I've added my fix for it. bbc7839

**Comment by Missionary2112** [comment]
Awesome!! It works like silk!
Thank you SIRvb!
