### ISSUE TITLE
[Bug] Heading font size inconsistencies since Obsidian 0.13.27 (or 0.13.28)

### ISSUE THREAD

**Issue by slnc** [SlRvb/Obsidian--ITS-Theme#73]
### Describe the bug
Since updating to Obsidian 0.13.28 from 0.13.26, font sizes in Live Preview mode are much smaller than font sizes in View mode, see attached screenshot. 

### Screenshots
![Screen Shot 2022-03-02 at 07 17 37](https://user-images.githubusercontent.com/69429/156306454-8ddc5236-cc6a-4e86-9d84-6442816c8996.png)

### OS
Where does the bug occur?

- [x] Desktop on MacOS
- [ ] Mobile

Obsidian Version: 0.13.28

### Additional context

Looking at the changelog (theme changes), the issue was most likely introduced in 0.13.27, not 0.13.28:

https://forum.obsidian.md/t/obsidian-release-v0-13-27-insider-build/33223

Similar bug on a different theme:
https://github.com/insanum/obsidian_nord/issues/33

**Comment by slnc** [comment]
Yes, it's fixed, thanks and apologies, I somehow missed manually updating the theme and checking here for recent commits. o:)

**Comment by Borber** [comment]
> Yeah, I've fixed that here [8f3d8e2](https://github.com/SlRvb/Obsidian--ITS-Theme/commit/8f3d8e2bb51684c420405ab29d02a1d24881e5e5). Do let me know if an update fixes the issues.

![image](https://user-images.githubusercontent.com/30563826/156862640-12387547-a499-4fdd-a432-8314bff7055c.png)

I think there is still something wrong with the dnd style.
