### ISSUE TITLE
[FR] - Background to headings

### ISSUE THREAD

**Issue by spiritualgeek** [SlRvb/Obsidian--ITS-Theme#74]
Could you, please, consider exposing the ability to have backgrounds to headings <h1..6>?

- The ability to set the background colour for each heading level
- The ability to specify round or square corners, perhaps with a slider for the degree of roundness
- The ability to specify a border that automatically changes the saturation and lightness, so the border is a darker version of the background colour

Thanks

**Comment by SlRvb** [comment]
> The ability to set the background colour for each heading level

`Note Elements > Header Styling > Illusion Theme Inspired Heading` Toggle should get you want you need there

---
> The ability to specify round or square corners, perhaps with a slider for the degree of roundness

This will be coming down the road when I have the time to get #63 done at some point

---
> The ability to specify a border that automatically changes the saturation and lightness, so the border is a darker version of the background colour

So for now the update, I've added the ability to add borders that you can specify the colors for but not exactly just the slider for dark/lighter or saturated/desaturated looks 3a5b24b

You can find the settings for it under `Note Elements > Headers > Header Styling` the `Heading Colors` is where the colors for the borders are.

**Comment by spiritualgeek** [comment]
Very grateful for these additions. Thank you so much 🙏
