### ISSUE TITLE
[Bug] dnd Heading style error 

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#75]
> Yeah, I've fixed that here [8f3d8e2](https://github.com/SlRvb/Obsidian--ITS-Theme/commit/8f3d8e2bb51684c420405ab29d02a1d24881e5e5). Do let me know if an update fixes the issues.

![image](https://user-images.githubusercontent.com/30563826/156862640-12387547-a499-4fdd-a432-8314bff7055c.png)

I think there is still something wrong with the dnd style.

_Originally posted by @Borber in https://github.com/SlRvb/Obsidian--ITS-Theme/issues/73#issuecomment-1059644885_

**Comment by lprunk** [comment]
I think this is still bugged. The last update on the alternate themes css fixed one of the D&D themes, but the other two are still strange.

WOTC/Beyond (this is the fixed one):
![WOTCBeyond](https://user-images.githubusercontent.com/8081245/160288847-9d0d6c24-8da4-468b-a5ca-c229e87dbdff.png)

SlRvb D&D:
![SlRvbDnD](https://user-images.githubusercontent.com/8081245/160288853-f7511082-1f2e-49bd-9cb5-dad14e949ff9.png)

WOTC:
![WOTC](https://user-images.githubusercontent.com/8081245/160288859-b51826ba-a8a4-4292-bbe2-4520d2856fff.png)

**Comment by Borber** [comment]
> 

What version are you using now, and whether you are using the old editor

**Comment by lprunk** [comment]
I'm using Obsidian 0.13.33 (not insider) and the last version of the theme (just updated today both the theme and the Alternate Themes css file as well). I'm using the new editor (but it's bugged in the legacy editor as well), only one of the 3 D&D themes renders ok in editor or live preview mode. They work in read mode, only editor/live preview doesn't render ok.

**Comment by lprunk** [comment]
It's working now! Thanks =)
