### ISSUE TITLE
[Bug] Strange white polka dots

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#76]
### Describe the bug

When I move my mouse over the space between the diamond symbol and the text, a white dot appears in the upper left corner

**Expected behavior**

No white polka dots

### Screenshots
![image](https://user-images.githubusercontent.com/30563826/156863923-6be36ff9-05c2-4400-896a-2f7d5abee35b.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version:
0.13.28

**Comment by SlRvb** [comment]
Wait do you have the Outliner plugin enabled? I'm not sure exactly how to replicate this, I don't get any dot when hovering over bullets 🤔

**Comment by Borber** [comment]
> Wait do you have the Outliner plugin enabled? I'm not sure exactly how to replicate this, I don't get any dot when hovering over bullets 🤔

Yes, I have enabled Outliner

**Comment by SlRvb** [comment]
If you disable the plugin and reload obsidian does the issue still occur?

**Comment by Borber** [comment]
> If you disable the plugin and reload obsidian does the issue still occur?

It really doesn't seem to be a theme problem, when I turn on safe mode, it's that it doesn't appear, so I guess I should check it out myself. Thanks for your reply
