### ISSUE TITLE
[Q&A] List in preview mode

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#77]
### Describe the bug
No matter how I adjust the settings, always can not achieve satisfactory results, preview mode performance of the rainbow line seems to be less than before

### Screenshots
![image](https://user-images.githubusercontent.com/30563826/156961133-4e2e9810-9102-4f7f-b92a-18ebf0078fbe.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.13.29

**Comment by SlRvb** [comment]
I think I might've added some fixes for this here: ddbcda0

I've also added a slider `Note Elements > Lists > Murf's Rainbow Line Offset` to help adjust the line to match up under the bullet points. Do let me know if this update helped.

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/157168471-b16cd0b8-9a8f-4318-9753-2780347d6893.png)
The first column works perfectly, but the rest of the column is misshapen

**Comment by Borber** [comment]
> I think I might've added some fixes for this here: [ddbcda0](https://github.com/SlRvb/Obsidian--ITS-Theme/commit/ddbcda096fa54bdc04feac5c6b0ecbf8dce00079)
> 
> I've also added a slider `Note Elements > Lists > Murf's Rainbow Line Offset` to help adjust the line to match up under the bullet points. Do let me know if this update helped.

This setting has some use, but it does not solve the problem completely

**Comment by SlRvb** [comment]
Hmm, I can't seem to replicate that, do you have a snippet that might adjust the padding for lists? Mine looks like this with mostly default setting:
![Obsidian_HUfPwUs1DT](https://user-images.githubusercontent.com/54087190/157170099-2b71956f-0d8e-4791-b647-53bb0c0670bb.png)

**Comment by Borber** [comment]
It's done, Murf's Rainbow Line Spacing is not set properly, Murf's Rainbow Line Offset is also very useful, it's aligned

![image](https://user-images.githubusercontent.com/30563826/157172319-2150de01-6ea6-489b-88fc-ebe1d59acaa1.png)

**Comment by Borber** [comment]
Thank you, and good luck to ITS, whose popularity I don't think currently matches his excellence
