### ISSUE TITLE
[FR] : When front-matter is malformed, change icon colour or display some indicator that it is

### ISSUE THREAD

**Issue by spiritualgeek** [SlRvb/Obsidian--ITS-Theme#78]
Minor request (at least I think it may be)

I'm a YAML junkie and also include small notes in mine

Every so often I'll mistype and mess something up which breaks the front-matter

With your theme, I have the front-matter hidden and would like the little folder type icon to be red if there is something wrong

I am uncertain if this is easy to do? Basically, any indicator of broken FM would be fine

Thanks

**Comment by SlRvb** [comment]
Oo that's a great request. I've added that to the theme d23060d. It looks like this when the yaml is invalid: 

![Obsidian_AIEwZwa64j](https://user-images.githubusercontent.com/54087190/157812805-c425f672-642b-4012-a1fe-2c5db41ffca2.png)

**Comment by spiritualgeek** [comment]
Most Excellent, :D Thank you very much... My headers request would be the cherry on the top :)
