### ISSUE TITLE
[Bug] Collapse indent arrow display

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#79]
### Describe the bug
The indentation arrow of the list in LivePreview mode is displayed incorrectly, even when trying to turn on safe mode.

Misalignment, overlaying rainbow rows, and causing the first arrow to fail to display

**Expected behavior**
Turn on collapse indent

### Screenshots
![image](https://user-images.githubusercontent.com/30563826/157385311-4c35e4b2-cb92-42e3-b236-5c7974166c8b.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.13.31

**Comment by SlRvb** [comment]
Oh shoot, yeah this is a problem with Murfs Rainbow lines. I think it's time I remove that css from my theme since we have the Indentation Guides plugin 🤔 

I've updated 1c63100 and removed Murfs Lines, so I recommend you use the Indentation Guides Plugin instead with the `Highlight Active Indentation Group` toggled off in the settings (it breaks the styling 🙈 )

**Comment by Borber** [comment]
Roger, thanks for your reply, I'll update the theme now

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/157786986-f691a78b-62e1-4e46-a0cf-3c7b67a23ef2.png)

I updated the theme, and installed the plugin, and now the first indent is displayed properly, but it still overwrites Murfs Lines. Is there any way to make the list indent icons individually more compact? Without affecting the headings at the same time

**Comment by SlRvb** [comment]
I've added a toggle to move those closer d23060d

Should be under `Note Elements > Lists > Snug Live Preview Arrow`

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/157815613-84315046-467b-42dc-a985-3a33f96b5c25.png)

Perfect, love you so much.
