### ISSUE TITLE
Odd symbol shown when frontmatter string ends in "!"

### ISSUE THREAD

**Issue by Moonbase59** [SlRvb/Obsidian--ITS-Theme#8]
Hi there, I was just testing something using your theme, and it shows an odd display bug that doesn’t happen with other themes:

![Schreiben - Obsidian v0 12 3_081](https://user-images.githubusercontent.com/3706922/120101900-c90fe400-c148-11eb-87f3-260fc54a8460.png)

The original YAML frontmatter is:
```yaml
Some YAML: Front Matter!
```
which is a vaild YAML string.

When I change it to
```yaml
Some YAML: Front Matter
```
or
```yaml
Some YAML: "Front Matter!"
```
it displays correctly.

**Comment by SlRvb** [comment]
Oh hmm. Obsidian seems to recognize that as a code token but was applying my tag css to it. I think I fixed that with the new update.
