### ISSUE TITLE
[Bug] Can't open Folder Notes

### ISSUE THREAD

**Issue by shadychild** [SlRvb/Obsidian--ITS-Theme#80]
### Describe the bug
I can't open (or close if they are already open) folder notes in this particular theme.
I can regularly open folders that are not folder notes.

**Expected behavior**
Clicking on the left side of the folder, I should be able to open it and see the files and subfolders inside it

### To Reproduce
1. Go to left pane
2. Click on any folder that is a folder note too
3. See that it doesn't open. You can see the notes in the folder notes, but it doesn't open showing you files and subfolders

### OS
Where does the bug occur?

- [X] Desktop
- [ ] Mobile

Obsidian Version: 0.13.31

**Comment by SlRvb** [comment]
I believe I fixed that, you should be able to open the folder normally if you click the empty space on the right of the folder title 🤔

**Comment by shadychild** [comment]
Unluckily no. The bug is still there.

**Comment by SlRvb** [comment]
Ah darn, you can toggle the `Workspace > Display Folder Arrow On Hover` on in the style settings, that should let you open the folder normally by displaying the collapse arrow on hover.

**Comment by shadychild** [comment]
I feel dumb but I can't find this option. Where are the style settings?

**Comment by SlRvb** [comment]
Oh do you have the Style Settings Plugin installed?

**Comment by shadychild** [comment]
Yes, now I've found it, and it works! Thanks a lot!
