### ISSUE TITLE
Highlight + Italic format renders the text out of the blockquote

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#81]
### Describe the bug
I'm using Annotator plugin: Using both highlight + italic format would render the text out of the block quote. It would be fine if I format `==*text*==`. But the Annotator plugin formats differently `*==text==*` and that causes the error.

**Expected behavior**
The text should be inside the block quote regardless of formatted text.

### To Reproduce
1. Create a block quote `>`
2. Type any text
3. Make the text both highlight and bold
4. See error: the text will be rendered out of the block quote.

### Screenshots
![2022-03-10 at 04 08 43 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/157776969-15dd8647-47ad-4fdf-8d33-eeefb3467a1d.jpg)

![2022-03-10 at 04 08 55 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/157776982-e839e8ec-007a-443a-ae85-a45bad5b9d13.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.13.33

**Comment by SlRvb** [comment]
Oh wow good catch! I did some dumb css stuff 🤦‍♀️ Should be fixed now! 1c63100

**Comment by Missionary2112** [comment]
Thank you! You're awesome!!

**Comment by Borber** [comment]
What screenshot software are you using, it looks very nice
