### ISSUE TITLE
Highlight within inline code messes up with Dataview

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#82]
### Describe the bug
Using highlight format within inline code will conflict with Dataview
e.g. `==text==` 

**Expected behavior**
`==text==` should not pop up the Dataview error in Preview mode

### To Reproduce
1. Type any text
2. Highlight the text: `==text==`
3. Inline code the highlighted text: ``==text==``
4. See Dataview error notification

### Screenshots
- Preview mode
![2022-03-11 at 01 34 40 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/157974080-46bd4ec1-3318-4786-9dab-3a74f69909c4.jpg)

- Edit mode
![2022-03-11 at 01 34 46 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/157974084-737d79ae-ba95-42b8-b0b1-0767b34c8964.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.13.33

**Comment by SlRvb** [comment]
Hmm, I don't think this is a theme error. I don't think I have any special code + highlight syntax styling🤔 

You might want to change your dataview prefix to avoid this.

**Comment by Missionary2112** [comment]
Oh yeah, I just adjusted `Inline Query Prefix` in Dataview setting. It's fine now. Thanks.
