### ISSUE TITLE
[Bug] The quick preview of the Better footnote plugin does not display

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#83]
### Describe the bug
The quick preview of the Better footnote plugin does not display

### Screenshots

> I moved the cursor to footnote, but it didn't show up because of the screenshot software

![image](https://user-images.githubusercontent.com/30563826/158009656-642ea3ae-9cf6-4090-993f-d25fa3567356.png)

Normal situation :
![image](https://user-images.githubusercontent.com/30563826/158009785-70caf739-1be8-487b-a6f6-9762fb8e34d7.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.13.33

**Comment by SlRvb** [comment]
I can't seem to recreate this error, the footnotes seem to pop up okay for me 🤔

![Obsidian_1qdE7CqbVp](https://user-images.githubusercontent.com/54087190/158303006-4aa4e3bf-a188-47f0-98f1-eaabc6d390e8.gif)

**Comment by Borber** [comment]
> I can't seem to recreate this error, the footnotes seem to pop up okay for me 🤔
> 
> ![Obsidian_1qdE7CqbVp](https://user-images.githubusercontent.com/54087190/158303006-4aa4e3bf-a188-47f0-98f1-eaabc6d390e8.gif)


You try using footnotes in an unordered list
![image](https://user-images.githubusercontent.com/30563826/158314253-e6f4a576-293a-42f1-97b5-5a4401b29d23.png)

**Comment by Borber** [comment]
Default theme:

![image](https://user-images.githubusercontent.com/30563826/158314507-782f2e07-a646-44a6-8ad2-b248965c7dca.png)

**Comment by Borber** [comment]
https://we.tl/t-56KKqMcTvU  

This is my configuration that I packaged, and I have the above problem, can you please help me to find out what the problem is?

**Comment by SlRvb** [comment]
So I've updated the theme 211e686, I've applied the neon list css to the indentation lines *only* if you toggle on
`Note Elements > Lists > Remove List Border Lines` and should avoid this issue with the Better Footnotes Plugin 👍🏽

![Obsidian_uJgvK2CMlA](https://user-images.githubusercontent.com/54087190/159154901-c91d6e0e-f8f7-49b1-a88a-0ac3a5a85bb5.gif)

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/159173561-b525646c-395f-4d5c-8d7f-dfffab83595a.png)


![image](https://user-images.githubusercontent.com/30563826/159173587-a31ad7a4-bf06-4613-a5e9-c40bc77a2ce4.png)

Your lines have a glow around them, but mine don't. I would like to know how to set it, I have Neon Lines turned on

**Comment by SlRvb** [comment]
This is fixed now right @Borber?

**Comment by Borber** [comment]
> 

yes!
