### ISSUE TITLE
[Bug] The obsidian-hover-editor plugin style display error

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#84]
### Describe the bug
With the obsidian-hover-editor plugin, the display is incorrect, and the line height of elements becomes abnormal.

**Expected behavior**
Normal display:
![image](https://user-images.githubusercontent.com/30563826/158018600-6bcf7b44-3efb-4c48-aeaf-d8584431baa8.png)

### To Reproduce
1. Install the obsidian-hover-editor plugin
2. set default mode as match current view
3. Hold down ctrl and place the cursor on the double chain

### Screenshots
![image](https://user-images.githubusercontent.com/30563826/158018562-3b6054b1-c767-4370-9d14-a62786679fa6.png)

![image](https://user-images.githubusercontent.com/30563826/158018564-a5d56dee-e6d8-42b9-9e28-65e244b442e0.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.13.33

**Comment by SlRvb** [comment]
Oooh right yeah, popovers used to target images, so I hadn't excluded the `<img>` for editor elements which is why the spacing was horribly off. Should be fixed now a070a52, thanks for letting me know about this issue!

**Comment by Borber** [comment]
> Oooh right yeah, popovers used to target images, so I hadn't excluded the `<img>` for editor elements which is why the spacing was horribly off. Should be fixed now [a070a52](https://github.com/SlRvb/Obsidian--ITS-Theme/commit/a070a52e978d52c1043271972e8b63ea02629d21), thanks for letting me know about this issue!

Perfect solution, great
