### ISSUE TITLE
[Bug] ligatures display problems

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#86]
### Describe the bug
The ligatures is displayed normally in the list, but the hyphen is not converted in the normal text.

### Screenshots

![image](https://user-images.githubusercontent.com/30563826/158093720-a695c00d-4b68-4d18-bc6b-3dd58a43ba65.png)

![image](https://user-images.githubusercontent.com/30563826/158093549-57e1a75c-6ad3-4e79-87b6-2c859cb999ab.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.13.33

**Comment by SlRvb** [comment]
Oops, it was some old css I hadn't fixed in a while. Nice catch! Should apply ligatures everywhere properly now c4c935c

**Comment by Borber** [comment]
> Oops, it was some old css I hadn't fixed in a while. Nice catch! Should apply ligatures everywhere properly now [c4c935c](https://github.com/SlRvb/Obsidian--ITS-Theme/commit/c4c935c902737cc40f8c8211a01bae4c960c484f)

![image](https://user-images.githubusercontent.com/30563826/158297504-477bbcb8-d791-4d52-b1f7-ccdaf7debaee.png)
I think there's still a bit of a problem

![image](https://user-images.githubusercontent.com/30563826/158297580-01059f5a-bebf-4ada-b0ed-aad1c9a29e3f.png)

**Comment by Borber** [comment]
My bad, now running very well, love you

![image](https://user-images.githubusercontent.com/30563826/158298011-e84f436a-7f39-49c8-9fd6-68439928838f.png)
