### ISSUE TITLE
[Bug] Strange thin lines appear in the list

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#87]
### Screenshots
![image](https://user-images.githubusercontent.com/30563826/158299066-6373ae0a-56bf-4c4e-9040-d3d5add30bc9.png)

Using themes in the example library also has this problem
![image](https://user-images.githubusercontent.com/30563826/158299237-83ebbe5f-a789-4e8c-9ccf-d7a4a53b4547.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.14.0

**Comment by SlRvb** [comment]
Yeah the insider update added Indentation Guides into core. You can disable them in the `Settings > Editor > Display > Show Indentation Guides`

**Comment by Borber** [comment]
Solved
