### ISSUE TITLE
[Bug] Error in image layout in live preview mode

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#88]
### Describe the bug
Error in image layout in live preview mode

### Screenshots
![image](https://user-images.githubusercontent.com/30563826/158828911-991109cb-a6eb-4c31-a879-a13bfc20ff28.png)

![image](https://user-images.githubusercontent.com/30563826/158828945-7c5c8c7c-b756-480a-b526-e95baf96fd9c.png)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.14.1

**Comment by SlRvb** [comment]
So I've added the option to get image grid in LP using callouts: 02fe1e3. So you don't really need the img-grid class for it.

**Comment by Borber** [comment]
> So I've added the option to get image grid in LP using callouts: [02fe1e3](https://github.com/SlRvb/Obsidian--ITS-Theme/commit/02fe1e32c44340361d23b18ef9b9902dbf62205a). So you don't really need the img-grid class for it.

Do I need to turn it on manually?
