### ISSUE TITLE
[FR] Beautify excalidraw?

### ISSUE THREAD

**Issue by Borber** [SlRvb/Obsidian--ITS-Theme#89]
Can we beautify excalidraw? Make it more in line with the ITS style

![image](https://user-images.githubusercontent.com/30563826/158961474-0a2c53a3-f62c-41c0-b4b2-5f242e701a6f.png)

**Comment by SlRvb** [comment]
Done 😉 975a0f1

![Obsidian_68fuiLE9YI](https://user-images.githubusercontent.com/54087190/158975339-8eb6f59a-faca-45d8-83cf-9642868bc69e.png)
![433uSfHH32](https://user-images.githubusercontent.com/54087190/158975352-8d5bea14-99db-4d38-8019-7b7bdb2e57c3.png)

**Comment by Borber** [comment]
Perfect, you are my hero
