### ISSUE TITLE
Table columns don't align correctly

### ISSUE THREAD

**Issue by psychsatani** [SlRvb/Obsidian--ITS-Theme#9]
Normally with advanced tables plugin selected and no theme enabled, in edit mode the vertical lines are aligned properly, making it look like a clean table. But when I enable ITS plugin this is gone and tinkering around with alignment has not fixed this. This issue should be clearer with the video I am attaching. 

Again, I can't repeat enough how much I love the theme and am thankful for it. 

https://user-images.githubusercontent.com/78266798/120420062-360dbe80-c381-11eb-885b-ffbb4c60ac45.mov

**Comment by SlRvb** [comment]
Oh no! Luckily, it wasn't too much of a hassle to figure out what went wrong, so it this should be fixed in the update I pushed out now!

**Comment by psychsatani** [comment]
Yes this is fixed thank you!
