### ISSUE TITLE
Something wrong with checkbox

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#90]
### Describe the bug
The format of checkbox is incorrect: the vertical line cut the sentence.

**Expected behavior**
The checkbox & the vertical line should not cut the sentence

### To Reproduce
1. Create checkbox
2. See error

### Screenshots
- Editing View
![2022-03-18 at 02 24 03 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/158976710-1f1d5ebf-5c48-4540-809b-b4df8d4f4836.jpg)

- Reading View
![2022-03-18 at 02 23 55 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/158976699-9779d99f-8beb-4004-be32-d171605e03f3.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.14.2

**Comment by Borber** [comment]
Are you still using the old  editor?

**Comment by Missionary2112** [comment]
I am using everything up-to-date. In Live Preview mode, I do not see the vertical line after the checkbox. I also tested Legacy Editor and the error still persists in Reading mode.

**Comment by Borber** [comment]
You're right, the vertical lines in reading mode do show up incorrectly

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/159109212-8711e531-9a6c-4dc8-9600-b4d68ec5c8e6.png)

**Comment by SlRvb** [comment]
I think I've fixed it with this update: 6e51415. Do let me know if that fixes it 🙏🏽

**Comment by Missionary2112** [comment]
Yes, It looks wonderful now. Thank you!
