### ISSUE TITLE
Image Position: Center is not working!

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#91]
### Describe the bug
Embedded Image cannot be center. `![[file.png|center]]` does not center the image. However, `![[file.png|ctr]]` does center. 

**Expected behavior**
The image should be centered when I used `![[file.png|center]]`

### To Reproduce
1. Embed an image file
2. Enter `center` → `![[file.png|center]]`
4. See error in Reading View: the image is still on the left, not rendering in the center. 

### Screenshots
- Editing View
![2022-03-21 at 10 41 00 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/159415495-857023f3-9e4e-4c1e-ae7b-18b66b12b80b.jpg)

- Reading View
![2022-03-21 at 10 41 12 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/159415588-9a5c3e84-d35c-4134-bb82-a99aa8e0304d.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.14.2

### Additional context
When I position an image whether to left / right / center, I would like the text to be rendered below the image instead of side-by-side with the image. Is that possible ?

- Editing View
![2022-03-21 at 10 45 25 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/159416121-5bba34a5-ca89-4ee9-b89f-a46c3e70b563.jpg)

- Reading View
![2022-03-21 at 10 45 48 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/159416145-a37ea2ae-f2b7-412d-ac16-8424c648d8c3.jpg)

**Comment by SlRvb** [comment]
I think I've fixed the center issues 9b723f1, could you update and see if it helped?

**Comment by SlRvb** [comment]
For text below the floating images are you asking for captions?

**Comment by Missionary2112** [comment]
Thanks, it works now.

**Comment by SlRvb** [comment]
I'm not sure what the additional context is asking for, so I think this issue is solved. If not, do reopen it or open another issue regarding the additional context stuff.
