### ISSUE TITLE
[Bug] List does not render lines correctly with tasks

### ISSUE THREAD

**Issue by stecydube** [SlRvb/Obsidian--ITS-Theme#92]
Using list and/or task item does not always have the vertical lines properly displayed.

For example:

```
Some text

- [ ] Something
- [ ] Something

Some Text

- [ ] Something
    - Something
```
 produces

![image](https://user-images.githubusercontent.com/5737502/159706448-ec0ebe96-8a02-48b5-a08c-7ea440dc3036.png)

As a solution, maybe have the checkboxes in column 1, in line with the regular text paragraph?

![image](https://user-images.githubusercontent.com/5737502/159707944-2680e52d-65de-4bc5-a9a8-8ed7ab0d4027.png)

On windows 10, obsidian 0.13.33

**Comment by Borber** [comment]
Current recommended configuration: 

![image](https://user-images.githubusercontent.com/30563826/159725088-60cd4ebb-7edc-481d-a91d-566a67ab321e.png)
![image](https://user-images.githubusercontent.com/30563826/159725351-442e29e2-b87d-42ea-b0e8-7005fddd3fbd.png)
![image](https://user-images.githubusercontent.com/30563826/159726119-cc2c90f8-0d9f-4d2d-b4f2-fcf597ccb371.png)

Results: 
![image](https://user-images.githubusercontent.com/30563826/159726331-8fa8d59c-c8b3-4b27-a92c-5231cd16907d.png)
I think it's perfect.

**Comment by stecydube** [comment]
hmmm, odd, I don't have the "Show Indentation Guides" under Editor...

![image](https://user-images.githubusercontent.com/5737502/159750456-e753eeb6-621c-465f-b578-ed63f33435ea.png)

**Comment by Borber** [comment]
> hmmm, odd, I don't have the "Show Indentation Guides" under Editor...
> 
> ![image](https://user-images.githubusercontent.com/5737502/159750456-e753eeb6-621c-465f-b578-ed63f33435ea.png)

Oh, and this is a new feature in 0.14

**Comment by SlRvb** [comment]
Yeah my css was updated for 0.14 because the changes broke the css in that same way... which means I broke it for those not using 0.14 yet 🙃🙃

**Comment by Borber** [comment]
> Yeah my css was updated for 0.14 because the changes broke the css in that same way... which means I broke it for those not using 0.14 yet 🙃🙃

But it's worth it, because the new version of the style is really cool

**Comment by stecydube** [comment]
Ok, I'll wait until 0.14 comes out.

**Comment by SlRvb** [comment]
I've added a toggle in the mean time under `Note Elements > Checkboxes > Pre v0.14 Checkbox Alignment Fix` that should hopefully fix that. Do let me know if it helps :)

46f17226d602d01f2dfbc31732dcb962c7776155

**Comment by stecydube** [comment]
That is so perfect 😀
Thank you very much !
