### ISSUE TITLE
Better Footnote does not work anymore

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#93]
### Describe the bug
Better Footnote plug-in used to work fine. But now it does not work in bullet list.

**Expected behavior**
The reference number should display the footnote once hovered, regardless of format. 

### To Reproduce
1. Create a bullet list
2. Create a footnote anywhere in the bullet list
3. Hover a cursor over the reference number in Reading mode
4. See error: it does not display the footnote

### Screenshots
- Sentence without a bullet list
![2022-03-24 at 01 35 13 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/159876343-500f1c0e-10bd-4756-a2a7-3b10e49aab07.jpg)

- Sentence with a bullet list
![2022-03-24 at 01 35 21 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/159876377-94d1aeb7-a27f-4791-b531-18b553df1e4e.jpg)

### OS
Where does the bug occur?

- [X] Desktop
- [ ] Mobile

Obsidian Version: v0.14.2

### Additional context
It's funny that if you hover over the reference number of sentence without a bullet list and then immediately to the one with the bullet list (hover 1 then 2), the footnote actually popped up. 
![2022-03-24 at 01 42 43 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/159876850-de0b33b3-3a96-4f14-902f-cb79d4f6a36f.jpg)

**Comment by SlRvb** [comment]
Hmm, I believe I removed that neon bullet code that messed it up #83. Even with an update that isn't fixed?

**Comment by Missionary2112** [comment]
It only works in Neon bullet code when I enable "Remove List Border Lines". But with the cost of aesthetic look. I really enjoy the vertical lines. 🙏 Looking forwards to use better footnote with Neon bullets in the future.

**Comment by SlRvb** [comment]
Yeah, it should work far better in v0.14 with the indentation guides, so hopefully that drops some time soon :)
