### ISSUE TITLE
The embedded image cannot be rendered to `right`

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#94]
### Describe the bug
The embedded image cannot be rendered to the right `![test|right|400](https://shrtm.nu/VsRM)` 

**Expected behavior**
The image should be rendered to the right

### To Reproduce
1. Embed an image link
2. Add `![test|right|400](https://shrtm.nu/VsRM)`
3. See error

### Screenshots
- Editing view
![2022-03-26 at 02 11 51 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/160232989-93b1772d-7076-4777-b7a9-5e72b32333a0.jpg)

- Reading view
![2022-03-26 at 02 12 48 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/160233001-9b7b7681-b888-4300-a14c-87ff23b30883.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.14.2

**Comment by SlRvb** [comment]
Oops, my fix for publish broke it, but I think it should work again now. 015b613

**Comment by SlRvb** [comment]
If this isn't fixed, do feel free to reopen the issue.
