### ISSUE TITLE
[Bug] with S-Checkboxes : DevTools failed to load source map

### ISSUE THREAD

**Issue by namtrah** [SlRvb/Obsidian--ITS-Theme#98]
### Describe the bug
When I start obsidian, I get the following error:

```
DevTools failed to load source map: Could not parse content for app://obsidian.md/S%20-%20Checkboxes.css.map: Unexpected end of JSON input
```
I am not at all sure if this is an error or not, still it is not nice to have.

**Comment by SlRvb** [comment]
Hmmm, could you see if deleting the /*# sourceMappingURL=... */` at the end and seeing if that helps? I've found a way to get rid of that while loading my stuff and if that works I'll be fixing it for my stuff 🙈
