### ISSUE TITLE
[Bug] Kanban extension does not render properly with ITS Theme

### ISSUE THREAD

**Issue by jasal82** [SlRvb/Obsidian--ITS-Theme#99]
### Describe the bug
Kanban extension does not render properly. Tags are currently configured as inline-block with text align centered which does not work well with long tags spanning multiple lines in the Kanban cards. They also have a dark background color which shouldn't be the case. The tag markers on the bottom of the cards use `.text-dl` for the foreground color which is not overridden in the theme.

### To Reproduce
- Install Kanban extension
- Create a board and add a few cards with long tags

### Screenshots
![image](https://user-images.githubusercontent.com/43233047/161525293-bf4e6606-9f2b-47f5-88e2-857427fd4e5a.png)

### OS
Where does the bug occur?

- [x] Desktop
- [?] Mobile

Obsidian Version: 0.14.2

**Comment by jasal82** [comment]
Yes exactly. A toggle to left align tags would be great to fix the bottom tag. And I'm not sure where that dark background color of the upper tag is coming from since it's rendering without background color outside of the Kanban board. Also I'd like to know if something can be done about the display of the `a.tag` because I'd rather have it begin in the line that says 'create tasks` and then wrap to the next line. The computed `display` style says `block` and cannot be changed in the developer tools. I don't know what is happening there but I guess that's a problem of Kanban itself because it happens with other themes as well.

**Comment by jasal82** [comment]
This is what I get with the default theme

![image](https://user-images.githubusercontent.com/43233047/161544348-60d50c90-aa70-4b66-a8d7-a561df582a9c.png)

**Comment by jasal82** [comment]
After giving the wrapping issue some more thought I'm pretty sure that it's because of the hyphen which serves as wrapping indicator and the slashes don't. So that's probably a more general problem and nothing to be fixed in the theme.

**Comment by SlRvb** [comment]
> And I'm not sure where that dark background color of the upper tag is coming from since it's rendering without background color outside of the Kanban board. 

This is the default styling for tags in preview mode, but I can add options to have it display as just colored text.

> Also I'd like to know if something can be done about the display of the `a.tag` because I'd rather have it begin in the line that says 'create tasks' and then wrap to the next line. The computed `display` style says `block` and cannot be changed in the developer tools. I don't know what is happening there but I guess that's a problem of Kanban itself because it happens with other themes as well.

I can try to see if I can do something with this and get it to work inline 🤔

**Comment by SlRvb** [comment]
I've added the toggle for simple looking tags under `Note Elements > Tags > Colored Text Tags` and you can change the text position to align left using the `Note Elements > Tags > Tag Text Alignment` dropdown. 191c765

**Comment by SlRvb** [comment]
If this isn't fixed, do feel free to reopen this issue.
